### ISSUE TITLE
Add automated metric support

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#106]
Spring has a module called actuator which allows metric collection.
If we would add support for that, we could check how many messages/requests/responses have been sent, how long it took, and check whether errors have occurred. Server owners could use these metrics and export them to prometheus and visualize them with Grafana or other tools.

![grafana](https://user-images.githubusercontent.com/1579362/47302329-8812d300-d621-11e8-863e-c012197d51da.png)

Are you interested in adding that to this project?
(I might be able to contribute the necessary code for that as well)

**Comment by yidongnan** [comment]
Look forward to your PR
