### ISSUE TITLE
Expose service availability to actuator

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#110]
It would be nice, if clients would report offline/online services to the actuator health endpoint.

The same also applies to the server, but the grpc library does not yet expose that value to other beans:
https://github.com/grpc/grpc-java/issues/4992

I'm not sure, whether/when I can PR that feature.

**Comment by ST-DDT** [comment]
Waiting for upstream changes

**Comment by asarkar** [comment]
I'm new to gRPC, and this project, but curious how would "offline/online" status be determined? Channel state?

**Comment by ST-DDT** [comment]
That might work for the client-side. I need to take a closer look at this.

**Comment by ST-DDT** [comment]
Might be useful in combination with https://github.com/spring-projects/spring-boot/issues/14022
(aka not getting your application killed if a grpc client is unable to connect)
