### ISSUE TITLE
Release the current version

### ISSUE THREAD

**Issue by Brantner** [yidongnan/grpc-spring-boot-starter#112]
Could you please make a new minor release with the current codebase? We really need the fix in https://github.com/yidongnan/grpc-spring-boot-starter/commit/04bec965a4526b6ecc5f25af815d872f47228ff4 to retain the order of interceptors. I'll be glad to help in that if needed.

**Comment by ST-DDT** [comment]
I also would like to recommend an official release to my colleagues. Currently I use a self-made one, but the acceptance is low. I will continue with more features after the release.

Sorry for the trouble.

**Comment by yidongnan** [comment]
I will release a new version now.

**Comment by yidongnan** [comment]
https://oss.sonatype.org/#nexus-search;gav~net.devh~~2.1.0.RELEASE~~

**Comment by ST-DDT** [comment]
Thanks!
