### ISSUE TITLE
Which test framework should we use?

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#115]
I thought about adding a test project that can be used to automatically test all features of this library, to ensure there are no hidden breakages if new features are added or existing features changed.

Would you prefer JUnit 4.12 based tests or are you okay with the new JUnit 5 (JUpiter) tests?

(There isn't that much of a difference, but the new version uses a different package and is slightly more flexible due to using Java 8 features)

**Comment by yidongnan** [comment]
I have not used junit 5 in any project. what advice do you have? If you think that JUnit 5 is OK,  I think we can also try it.

**Comment by ST-DDT** [comment]
I added a test project with JUnit 5 in https://github.com/yidongnan/grpc-spring-boot-starter/pull/113#issuecomment-433455114.

**Comment by ST-DDT** [comment]
I guess this issue is solved for now.
