### ISSUE TITLE
What is the function of healthServiceEnabled?

### ISSUE THREAD

**Issue by littileAn** [yidongnan/grpc-spring-boot-starter#123]
What is the function of healthServiceEnabled? Health Service Enabled failed when it was true, but I don't know where my code failed to make healthServiceEnabled

**Comment by ST-DDT** [comment]
The `healthServiceEnabled` controlls whether the health service is available on your server or not. It is enabled by default.

It can be used as followed:

````text
$ ./grpcurl -plaintext localhost:9090 list
TestService
grpc.health.v1.Health
grpc.reflection.v1alpha.ServerReflection
$ ./grpcurl -plaintext localhost:9090 list grpc.health.v1.Health
Check
$ ./grpcurl -plaintext -d '{"service":"TestService"}' localhost:9090 grpc.health.v1.Health/Check
{
  "status": "SERVING"
}
````

> Health Service Enabled failed when it was true, but I don't know where my code failed to make healthServiceEnabled

Does your server fail to start with this option enabled? Do you have a stacktrace? Which version of grpc are you using?

**Comment by ST-DDT** [comment]
@littileAn Does that explain your question?
If yes, please close the issue.
If no, please leave a comment what remains unclear.

**Comment by littileAn** [comment]
@ST-DDT thank you
