### ISSUE TITLE
Missing Spring configuration meta data since 2.0.0

### ISSUE THREAD

**Issue by mweirauch** [yidongnan/grpc-spring-boot-starter#128]
As the title says, `META-INF/spring-configuration-metadata.json` is missing from the client and server autoconfigure projects.

**Comment by yidongnan** [comment]
It seems that after gradle 4.6 and later, we need to use the ``annotationProcessor ``

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-annotation-processor
