### ISSUE TITLE
Please provide a security example

### ISSUE THREAD

**Issue by RealDude** [yidongnan/grpc-spring-boot-starter#134]
It would be great if someone could provide a basic-auth security example (server and client).

**Comment by ST-DDT** [comment]
The auth code is already there, iirc it just hasnt been released yet. It might be available as snapshot though. I will try to optimize its code some more soon.

You can look at the junit tests to have a working example:
* [`AnnotatedSecurityWithBasicAuthTest`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/test/grpc/security/AnnotatedSecurityWithBasicAuthTest.java)
* [`AnnotatedSecurityConfiguration`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/test/grpc/config/AnnotatedSecurityConfiguration.java)
* [`WithBasicAuthSecurityConfiguration`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/test/grpc/config/WithBasicAuthSecurityConfiguration.java)

The last config can be simplified a bit:
* if you have already configured spring security for web apps the you only need the `GrpcAuthenticationReader` on the server side
* the client does not need the custom address factory, its only there for testing. You can use a `GlobalClientInterceptorConfigurer` to register the `basicAuthInterceptor` instead.

**Comment by ST-DDT** [comment]
I created a PR which adds a standalone example. #138
