### ISSUE TITLE
Publicly host javadocs

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#144]
What do you think about publicly hosting the javadocs?

IIRC there should be some hosters that provide that service for free for open source projects or you can use your own page for that.

**Comment by yidongnan** [comment]
This is a good suggestion, we can first find out which service providers provide hosting services, and whether it can automatically update javadoc through CI.

**Comment by ST-DDT** [comment]
How about this page:
https://www.javadoc.io/

It automatically host javadoc pages for all artifacts on maven central

[![Client-Javadocs](https://www.javadoc.io/badge/net.devh/grpc-client-spring-boot-autoconfigure.svg?label=Client-Javadoc)](https://www.javadoc.io/doc/net.devh/grpc-client-spring-boot-autoconfigure)
[![Server-Javadocs](https://www.javadoc.io/badge/net.devh/grpc-server-spring-boot-autoconfigure.svg?label=Server-Javadoc)](https://www.javadoc.io/doc/net.devh/grpc-server-spring-boot-autoconfigure)

````md
[![Client-Javadocs](https://www.javadoc.io/badge/net.devh/grpc-client-spring-boot-autoconfigure.svg?label=Client-Javadoc)](https://www.javadoc.io/doc/net.devh/grpc-client-spring-boot-autoconfigure)
[![Server-Javadocs](https://www.javadoc.io/badge/net.devh/grpc-server-spring-boot-autoconfigure.svg?label=Server-Javadoc)](https://www.javadoc.io/doc/net.devh/grpc-server-spring-boot-autoconfigure)
````

**Comment by yidongnan** [comment]
This looks nice

**Comment by ST-DDT** [comment]
Should I create a PR for that or do you want to commit it directly?
Should we include a link to common preemptively?

**Comment by yidongnan** [comment]
I submit directly and add common link

**Comment by ST-DDT** [comment]
Looks good. If we add more badges, then we might have to split it to multiple lines.
