### ISSUE TITLE
Also build with Java 11 to ensure compatiblity

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#146]
Java 8 will be EOL very soon, so we should configure travis to also run the tests with java 11 (OpenJDK because of LTS support?).

Since we are a library it is probably fine to continue to compile to Java 8, but we should ensure that we are Java 11 compatible.

I already tried running the build process with Java 11, but I got some strange errors that are probably gradle related. I also tested using the latest release with an Java 11 Runtime, that worked perfectly fine for me.

**Comment by yidongnan** [comment]
Support java 11 from gradle 5.0, maybe we need to upgrade to gradle 5.0 first. 
https://docs.gradle.org/5.0/release-notes.html#java-11-runtime-support

**Comment by ST-DDT** [comment]
Unfortunately I'm not familiar with gradle so I cannot help very much with an gradle upgrade.

**Comment by yidongnan** [comment]
I will try to upgrade gradle to 5.0

**Comment by yidongnan** [comment]
I tried to upgrade gradle to 5.0, but I found a bug in the provider dependency pass, which has been fixed in this PR gradle/gradle#7840, we need to wait for the next version
