### ISSUE TITLE
[BUG] Uppercase B causing wrong evaluation of condition, breaks basic auth

### ISSUE THREAD

**Issue by GregorEeckels** [yidongnan/grpc-spring-boot-starter#161]
There is a minor Bug in the Class BasicGrpcAuthenticationReader at Line 50.
The condition` !header.toLowerCase().startsWith(PREFIX)` will never evaluate to true if 
`PREFIX = "Basic "`. The upper case B is the problem.
This can be easily fixed by updating the `BASIC_AUTH_PREFIX = "Basic "` to `BASIC_AUTH_PREFIX="basic "` in the SecurityConstants class

**Comment by yidongnan** [comment]
The ``PREFIX`` constant is always equal to ``basic ``
````java
String PREFIX = BASIC_AUTH_PREFIX.toLowerCase()
````

**Comment by GregorEeckels** [comment]
Yes indeed. I missed that. Can be closed.
