### ISSUE TITLE
About maximum size

### ISSUE THREAD

**Issue by silentbalanceyh** [yidongnan/grpc-spring-boot-starter#163]
Hi, I met an issue in our application that came from gRpc as following:

```
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 14035314
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:387)
	at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:267)
	at io.grpc.internal.MessageDeframer.request(MessageDeframer.java:161)
	at io.grpc.internal.AbstractStream$TransportState.requestMessagesFromDeframer(AbstractStream.java:205)
	at io.grpc.netty.NettyServerStream$Sink$1.run(NettyServerStream.java:100)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Does there exist some parameter configuration for this issue ?

**Comment by ST-DDT** [comment]
I'm not sure on which side this error occurs (client or server). Depending on which side this error occurs you have to check either [`GrpcChannelProperties`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java) or [`GrpcServerProperties`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java). 

The property is probably named: `maxInboundMessageSize`.

IIRC the default limit was introduced in gRPC 1.16(?).

Please note that the `maxInboundMetadataSize` property was only added recently to gRPC netty and we don't have a property for that yet (but I assume that it isn't a problem in this case).
You can still configure it using [`GrpcChannelConfigurer`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/GrpcChannelConfigurer.java)s or [`GrpcServerConfigurer`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/GrpcServerConfigurer.java)s.

**Comment by silentbalanceyh** [comment]
Could you provide some GrpcServerConfigurer or GrpcChannelConfigurer
We used this library that referenced the code you provided as following:

The server: 

```java
@GrpcService(UnityServiceGrpc.class)
public class IpcService extends UnityServiceGrpc.UnityServiceImplBase {

    private static final Logger LOGGER = LoggerFactory.getLogger(IpcService.class);

    @Override
    public void unityCall(final IpcRequest request,
                          final StreamObserver<IpcResponse> responseObserver) {
        final JsonObject envelop = Ux.Rpc.json(request);
        final String address = envelop.getString(Constants.ADDRESS);
        final JsonObject data = envelop.getJsonObject(Constants.DATA);
        final JsonObject result = new JsonObject();
        try {
            final JsonObject invoked = IpcSelector.init(address).invoke(data);
            result.mergeIn(invoked, true);
            responseObserver.onNext(Ux.Rpc.response(result));
        } catch (final WebException ex) {
            Log.error(LOGGER, ex);
            result.mergeIn(ex.toJson(), true);
            responseObserver.onNext(Ux.Rpc.response(result));
        } catch (final Throwable ex) {
            Log.jvm(LOGGER, ex);
            responseObserver.onError(ex);
        } finally {
            responseObserver.onCompleted();
        }
    }
}
```

The client

```java
public class ApprovalResource {
    @GrpcClient(("MbORG"))
    private Channel orgChannel;
    @GrpcClient("MbENV")
    private Channel envChannel;
    @GrpcClient("ImaModal")
    private Channel modelChannel;
```

**Comment by ST-DDT** [comment]
@silentbalanceyh Does this answer your question?

**Comment by ST-DDT** [comment]
Feel free to comment if you have any more questions related to this.
