### ISSUE TITLE
咨询下这个对比Feign性能上提升大吗

### ISSUE THREAD

**Issue by Rainbowboys** [yidongnan/grpc-spring-boot-starter#173]
搭建了一个demo,试用 ab 并发测试下，没有发现性能上优与Fegin Http，是需要调整参数吗？

**Comment by yidongnan** [comment]
gRPC-java 的性能可以直接用 https://github.com/grpc/grpc-java/tree/master/benchmarks 测试就行。项目目前仅仅是对gRPC-java做了一些封装，一定程度上简化使用。
