### ISSUE TITLE
Run on Random Ports?

### ISSUE THREAD

**Issue by pluttrell** [yidongnan/grpc-spring-boot-starter#174]
Is there a way to configure the gRPC listener to run on a random port? And then a way to inject what that random port at runtime is so that we can use it to configure a client `Channel`? 

The use case for this is to do unit/integration testing using the actual server and endpoints without having to manage which points are reserved for what in our build environment, as well as enable concurrent runs of the unit tests. 

Spring Boot provides this support out of the box for `RestController`'s, ([docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications)) with the following example:
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
```
And then you can access that port with the following ([docs](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html#howto-discover-the-http-port-at-runtime)):
```
public class SomeTests {
  @LocalServerPort
  int port;
}
```

Or it can auto-configure the `WebTestClient` as follows ([docs](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-testing-with-running-server)):
```
public class SomeTests {
  @Autowired
  private WebTestClient webTestClient;
}
```

**Comment by yidongnan** [comment]
You can set `@SpringBootTest(properties = "grpc.server.port=0")` to use a random port.
Currently, the random ports can be access through `grpcServerProperties.getPort()`

**Comment by ST-DDT** [comment]
I thought about possible solutions for this:

### 1. Let the users "implement" it themselves

This can be done with a little bit of a trick.

````java
@SpringBootTest(properties = "grpc.server.port=0")
````

and an additional config file:

````java
@Configuration
@AutoConfigureBefore(GrpcClientAutoConfiguration.class)
@AutoConfigureAfter(GrpcServerAutoConfiguration.class)
@EnableConfigurationProperties(GrpcChannelsProperties.class)
public class TestConfig {

    @Autowired
    private GrpcServerProperties serverProperties;

    @Autowired 
    private GrpcChannelsProperties channelsProperties;

    @PostConstruct
    public void init() {
        channelsProperties.getChannel("test").setAddress("static://localhost:"+serverProperties.getPort());
    }

}
````

I haven't actually tested this variant yet, but "it should work".

### 2. Provide 1. in an another library

Basically add a new `grpc-spring-boot-starter-test` library that provides the above config class.
Plus maybe an annotation to make it more flexible/configurable (channel names)...

### 3. Use grpc functions to let it discover itself

We could add a `TestNameResolverProvider` or `LocalNameResolverProvider` that would automatically map it to the correct server.
Then all you have to do is configure the client like this and the rest would work natively:

````properties
grpc.client.myClient.address=test:
````

The necessary classes could be added to either `grpc-server-spring-boot-starter/autoconfigure` or `grpc-spring-boot-starter-test`. (It would be very light weight so there shouldn't be any issues with either of them.)

Maybe it is also possible to use some trickery and push it to `grpc-testing`, but this would be more difficult to implement then, I guess.

### 4. Ask the users to use inProcess clients/servers

This would avoid port clashes in general.

Related: #176 

-------------------------------------------------

@pluttrell @yidongnan What do you think of those suggestions? Which would you prefer?

**Comment by yidongnan** [comment]
In most scenarios, using inProcess clients/servers should be sufficient. If you really need to get a random port, I tend to provide a `grpc-spring-boot-starter-test` library.

**Comment by ST-DDT** [comment]
Related #222 - Using port 0 and an in-process setup might help here, if the actual network is not part of the tests.

**Comment by ST-DDT** [comment]
This is mostly already possible with custom some config, so I move this to the next version v2.5.0. Unless there's an objection

**Comment by ST-DDT** [comment]
@pluttrell Does the current feature set fulfill your requirements? Or do you need the randomized port based connection?

**Comment by ST-DDT** [comment]
I delay this to 2.6.0. Because the possibly easiest solution to this problem is using the `NameResolverRegistry` which I will start utilizing in #237 (v2.6.0).

**Comment by Fleshgrinder** [comment]
One problem I’ve seen with **1.** is that the randomly selected port gRPC decides to use might still be in use if you work in an environment like Jenkins where things are not totally isolated.

**Comment by ST-DDT** [comment]
> One problem I’ve seen with 1. is that the randomly selected port gRPC decides to use might still be in use if you work in an environment like Jenkins where things are not totally isolated.

There is nothing I can do about that. We only use free ports, but we cannot reserve them for our application thus it will fail if another application steals the port in between the port selection and the server starting up.

**Comment by Fleshgrinder** [comment]
That's clear, the comment was more a FYI for anyone coming here from a search. Other than the mentioned issue it works great.
