### ISSUE TITLE
Ability to configure in-process client / server in config file

### ISSUE THREAD

**Issue by internetstaff** [yidongnan/grpc-spring-boot-starter#176]
I just switched to this project from the "other" grpc-spring-boot-starter as it appears much more robust. So, thanks! :)

My unit test code is already cleaner, however it seems like there may be room for improvement.  I am implementing a @Configuration class that creates GrpcChannelFactory and GrpcServerFactory @Beans using InProcessChannelFactory and InProcessGrpcServerFactory. This works. However, I'm wondering if it makes sense to allow a grpc.server and grpc.client option that would enable inprocess. The "other" grpc-spring-boot-starter allows this, so there's no code required to switch to in-process: the test profile just configures it.

It might be nice if such a flag also disabled any incompatible configuration, such as security.

If I'm missing a way to do this, please let me know - but I used the existing test examples to figure this method out. :)

**Comment by ST-DDT** [comment]
> My unit test code is already cleaner, however it seems like there may be room for improvement. I am implementing a @configuration class that creates GrpcChannelFactory and GrpcServerFactory @beans using InProcessChannelFactory and InProcessGrpcServerFactory. This works. However, I'm wondering if it makes sense to allow a grpc.server and grpc.client option that would enable inprocess.

Do you want the inprocess-server/client configuration as an addition to the (netty) server/client or as a configurable replacement.

Example:

1. server.inProcessName=foobar (additional)
2. server.bindAddress=inprocess:/foobar (replacement)

Another possibility would be using a `@GrpcTestConfiguration` annotation that would automatically create the inprocess server/client beans, which then would replace the netty ones.

If we decide on adding it in addition to the netty ones how would you choose the netty/inprocess in the `@GrpcClient` annotation?
One option would be
````java
@GrpcClient(value="test", clientFactory="inProcessGrpcClientFactory")
````
But that would look really bulky.

Another option would be moving that flag to the config:

````yaml
grpc:
  client:
    test:
      clientFactory: inProcessGrpcClientFactory
      address: test
````

> It might be nice if such a flag also disabled any incompatible configuration, such as security.

* Disable incompatible configuration, well we could remove the thrown exception from the inProcess setup classes.
* Disable security flag: No. AFAICT there isn't such an option in spring-security-web either. The only way to disable security is either actually removing it or adding some kind of dev users or anonymous user.

**Comment by internetstaff** [comment]
I don't personally have much use for having an in-process server/client in addition to a netty server/client, but it seems like the flexibility wouldn't be bad. :)

Being able to configure it with just a flag in the config as you've shown above seems like the simplest method.

Thanks!

**Comment by ST-DDT** [comment]
Work in progress.
Currently I have planned to use the address property on the client side for this:

````properties
grpc.client.myService.address=inProcess:foobar
grpc.server.inProcessName=foobar
````

That way there won't be any collisions with the other services from the config. Under the covers it still uses an entirely different path.

**Comment by ST-DDT** [comment]
Added via #222
