### ISSUE TITLE
Run server on multiple ports

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#181]
https://github.com/grpc/grpc-java/pull/5067

Recently grpc-java added the ability to run a single server on multiple ports (Might be available with grpc 1.19). Should we add support for it in our library as well?

Example use cases might include:
* Use specific access roles based on the used server address. Address A is WWW-public, Address B is only accessible from within the network and thus can be used for privileged operations. (Accessible via `Attributes` with key `TRANSPORT_ATTR_LOCAL_ADDR`)

**Comment by ST-DDT** [comment]
[grpc-java v1.19.0](https://github.com/grpc/grpc-java/milestone/32)

**Comment by yidongnan** [comment]
> Should we add support for it in our library as well?

+1

**Comment by ST-DDT** [comment]
This is mostly already possible with GrpcServerConfigurer and I want to rething my current design proposal some more, so I move this to the next version v2.5.0. Unless there's an objection

**Comment by ST-DDT** [comment]
Removed it from the 2.5.0 milestone.
I don't have a good feeling with implementing this just like this.
Waiting for an actual usecase.

**Comment by ST-DDT** [comment]
Running on multiple ports doesnt help you with separating internal and public services as both ports would serve all services.

From a security perspective you would have to run different grpc servers. This is already possible, but not out of the box. Similar to spring-web that behaves in a similar fashion.

If you have an idea how to easily do this with spring please tell me.
