### ISSUE TITLE
Is there a global config for all servers?

### ISSUE THREAD

**Issue by andcuevas** [yidongnan/grpc-spring-boot-starter#183]
I would like to know if there is an alternative way to configure all the servers on the client side, instead of using grpc.client.$server_name.some_property
I'm working in a project where the list of server names might be big and I would like to configure all the servers with one property or if this is not possible maybe do it in the code.

**Comment by ST-DDT** [comment]
Currently there is no way to do this via property/config. However, I plan to add this feature. Do you have a suggestion how to add/implement such a feature?

There is a way to do it via code though: [`GrpcChannelConfigurer`](https://static.javadoc.io/net.devh/grpc-client-spring-boot-autoconfigure/2.2.1.RELEASE/net/devh/boot/grpc/client/channelfactory/GrpcChannelConfigurer.html)

**Comment by andcuevas** [comment]
You have default properties in GrpcChannelProperties.DEFAULT.
If that instance could first look the presence of a global property, if the global property is not there use the default that is hard coded.

**Comment by ST-DDT** [comment]
Work in progress.

**Comment by ST-DDT** [comment]
See #198 for the implementation
