### ISSUE TITLE
Drop support for the deprecated security.certificatePath and maxMessageSize server properties

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#190]
The properties have been deprecated in 2.1.0 and should be removed.

(Or we could wait a little bit longer)

**Comment by ST-DDT** [comment]
@yidongnan Should we remove them or wait till a later release?

**Comment by yidongnan** [comment]
@ST-DDT I think it's okay to remove it in 2.3.0. This configuration property has been marked deprecated for a long time.
