### ISSUE TITLE
Security configured for PLAINTEXT_UPGRADE

### ISSUE THREAD

**Issue by galleog** [yidongnan/grpc-spring-boot-starter#199]
NettyChannelFactory tries to configure SSL even for NegotiationType#PLAINTEXT_UPGRADE. I suppose it should do it only for NegotiationType#TLS.

**Comment by ST-DDT** [comment]
It looks like I made a mistake there. Confirmed Bug.

Javadocs:
> https://grpc.io/grpc-java/javadoc/io/grpc/netty/NegotiationType.html#PLAINTEXT_UPGRADE

> Use the HTTP UPGRADE protocol for a plaintext (non-SSL) upgrade from HTTP/1.1 to HTTP/2.

I'll fix it ASAP.

**Comment by ST-DDT** [comment]
I created a PR to fix this issue: #200
