### ISSUE TITLE
Cannot disable autoconfiguration for spring security

### ISSUE THREAD

**Issue by jacobk** [yidongnan/grpc-spring-boot-starter#205]
It doesn't seem possible to opt out from the auto configuration in `GrpcSecurityAutoConfiguration` (conditional on `AuthenticationManager` bean).

I tried to add `GrpcSecurityAutoConfiguration` to the list of excludes for auto configuration but spring boot complaints
> The following classes could not be excluded because they are not auto-configuration classes

(I tried both using `spring.autoconfigure.exclude` property and directly in `@SpringBootApplication(exclude ... )` 

The application in question is using spring security but it won't be using it for the gRPC parts.

**Comment by jacobk** [comment]
FWIW it's possible to exclude the client security
```spring:
    autoconfigure:
      exclude: net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration``` (intellij even autocompletes it, not sure in how they are different in setup)

**Comment by ST-DDT** [comment]
The main difference is that the one class is mentioned as auto configuration while the other is used as import. I will have a look at that soon. Maybe i can improve that behaviour.

**Comment by ST-DDT** [comment]
IIRC the only requirement for using security is implementing a AuthenticationReader. The simplest ones can either return null or an AnonymousAuthenticationToken.

Could you describe your usecase for having security enabled (for web?) but not for grpc?

**Comment by jacobk** [comment]
I tried to stub out the AuthenticationReader  like you suggest, but it caused some issue with CustomUserDetails that we have (I can look into what exactly later). 

The use case is that we ate only exposing gRPC internally on a separate port, on a private network. The same app is exposing a public rest api that is using spring security.

**Comment by yidongnan** [comment]
This seems to be able to set `GrpcSecurityAutoConfiguration` to the `@AutoConfiguration` class instead of using the `@import` , which allows the user to manually exclude in `@SpringBootApplication`
