### ISSUE TITLE
貌似项目demo跑不起来 

### ISSUE THREAD

**Issue by dazi005** [yidongnan/grpc-spring-boot-starter#21]
@Autowired
    private ConsulDiscoveryProperties properties;

    @Autowired
    private GrpcServerProperties grpcProperties;

    @PostConstruct
    public void init() {
        this.properties.getTags().add("grpc=" + grpcProperties.getPort());
    }

**Comment by dazi005** [comment]
grpcProperties  里边的 get 方法都没

**Comment by yidongnan** [comment]
@dazi005  使用的 lombok 自动生成的 get set 方法。 你可以看 GrpcServerProperties 类上的注解 @Data

**Comment by yidongnan** [comment]
@dazi005  https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples
增加了相应的文档描述
