### ISSUE TITLE
Release v2.3.0

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#210]
IMO we should release the 2.3.0 version after #209 is merged.

The remaining open issues assigned to [2.3.0](https://github.com/yidongnan/grpc-spring-boot-starter/milestone/1) will take some time and would just delay the current release some more (they will be moved to 2.4.0)
* #174 - Requires adding a new module, and is not a critical issue
* #176 - Requires a rework of some internals and thus should be done along with the grpc update to 1.19.0

The following issues were not assigned to 2.3.0 yet (now targetting 2.4.0):

* #181 - Requires an update to 1.19.0
* #203 - Would break compatibility with earlier versions and I would like to have at least one version that supports them.

Are there any other issues/features that should be fixed/implemented before the release?

Changelog for v2.3.0

* Updated the documentation (#178, #186)
* Improve keepAlive support (#177)
* Fix wrong usage of EquivalentAddressGroups in static address resolver (#179, #184)
* Update to grpc 1.18 (#182)
* Use shaded netty by default (#182)
* Improve javadoc (#188)
* Use the property from the sleuth docs (`spring.sleuth.scheduled.enabled` -> `spring.sleuth.grpc.enabled`) (#192)
* Move trace configuration (#194, #195)
* Some deprecated server properties have been removed (#190)
* Add support for global client properties (#183, #198) 
* Fix broken PLAINTEXT_UPGRADE support (#199, #200)
* Improve error messages during client injection (#201)
* Update example dependencies (#204)
* Move security configuration (#205, #208)

**Comment by yidongnan** [comment]
`2.3.0.RELEASE` is already available at [Maven Central](https://search.maven.org/search?q=net.devh)

**Comment by ST-DDT** [comment]
Thanks
