### ISSUE TITLE
Method  is unimplemented

### ISSUE THREAD

**Issue by Abily** [yidongnan/grpc-spring-boot-starter#216]
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method lib.Greeter/SayHello2 is unimplemented

syntax = "proto3";

//import "usermodel.proto";
//import "ServerBean.proto";

option java_multiple_files = true;
option java_package = "com.linshen.grpc.lib";
option java_outer_classname = "GreeterProto";
option objc_class_prefix = "GT";
//package tensorflow.serving;

package lib;

// The greeter service definition.
service Greeter {
    // Sends a greeting
    rpc SayHello ( HelloRequest) returns (  HelloReply ) {}

    rpc SayHello2 ( HelloRequest) returns (  HelloReply ) {}

}
// The request message containing the user's name.
message HelloRequest {
    string name = 1;
}
// The response message containing the greetings

message HelloReply {
    int32 ret = 1;
    string msg = 2;
    string data = 3;
    string tid = 4;
}

**Comment by ST-DDT** [comment]
You forgot to add the actual question you want to ask.

**Comment by ST-DDT** [comment]
Closing due to missing feedback.
