### ISSUE TITLE
@GrpcClient(value = "local-grpc-server")  @PostConstruct

### ISSUE THREAD

**Issue by 991697456** [yidongnan/grpc-spring-boot-starter#227]
@GrpcClient(value = "local-grpc-server")  @PostConstruct 同时使用异常，@PostConstruct注解的方法在@GrpcClient(value = "local-grpc-server")之前执行造成空指针

**Comment by yidongnan** [comment]
@991697456 在#158 中已经修复了这个问题，已经包含在 `2.2.0.RELEASE` 版本中。我们推荐你升级到最新的版本，新版本中提供了更好的稳定性和更多的特性。如果你使用的是 spring boot 1.x ，我们会在`1.4.1.RELEASE` 基础之上修复这个问题。

@ST-DDT We can fix this problem on the 1.4.x branch. I looked at the code in this section. There is no distinction between the spring boot version. It should be possible to pass the cherry pick or copy the relevant code to that branch.

**Comment by ST-DDT** [comment]
FYI: [Spring Boot 1.x EOL Aug 1st 2019](https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019)

**Comment by yidongnan** [comment]
@991697456 我们已经在 `1.4.2.RELEASE` 中修复了这个问题，你可以升级到新版本。鉴于 `Spring Boot 1.x` 马上就要 EOL，我们也建议你升级到 `Spring Boot 2.x` 的版本，这样可以使用我们 2.x 的版本（目前的最新版是 `2.4.0.RELEASE` ), 2.x 的版本在提供更多特性的同时，提供了更好的稳定性。

**Comment by 991697456** [comment]
谢谢支持！你们的建议我们会尽量采纳




------------------ 原始邮件 ------------------
发件人: "Michael Zhang"<notifications@github.com>; 
发送时间: 2019年6月4日(星期二) 中午1:54
收件人: "yidongnan/grpc-spring-boot-star"<grpc-spring-boot-starter@noreply.github.com>; 
抄送: "崔宝玉"<991697456@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yidongnan/grpc-spring-boot-starter] @GrpcClient(value ="local-grpc-server")  @PostConstruct (#227)




@991697456 我们已经在 1.4.2.RELEASE 中修复了这个问题，你可以升级到新版本。鉴于 Spring Boot 1.x 马上就要 EOL，我们也建议你升级到 Spring Boot 2.x 的版本，这样可以使用我们 2.x 的版本（目前的最新版是 2.4.0.RELEASE ), 2.x 的版本在提供更多特性的同时，提供了更好的稳定性。

**Comment by 991697456** [comment]
dear master
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 请教您一个问题：
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 由于过滤器比拦截器先执行,那么过滤器是如何把request参数传递下去呢? 这个的原理是什么？
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; （过程：我是拦截器获取请求body,由于 使用 HttpServletRequestWrapper，filter做了回写，这样我可以在controller中requestbody参数了）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yidongnan/grpc-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2019年5月16日(星期四) 下午3:16
收件人:&nbsp;"yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"崔宝玉"<991697456@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yidongnan/grpc-spring-boot-starter] @GrpcClient(value = "local-grpc-server")  @PostConstruct (#227)




FYI: Spring Boot 1.x EOL Aug 1st 2019

**Comment by ST-DDT** [comment]
This seems to be a new and unrelated question. Please open a new issue for it and provide the requested context information.
