### ISSUE TITLE
你好,非常感谢你们开发的这一套grpc-consul框架,我现在遇到一些问题

### ISSUE THREAD

**Issue by JasonWeeber** [yidongnan/grpc-spring-boot-starter#231]
我们在与go团队合作的过程中,go团队使用的gprc并没有使用gRPC.port这个tag,所以我重写了一个类来实现,这还不是比较困难的,现在的问题是go团队在做服务注册时使用的是http2+protocbuf,所以他们服务注册与实现都是一套协议与接口,但是我们服务注册是http1+json,服务的实现是http2+protobuf,这样就很难兼容,有什么好方法么,
邮箱:wenbin.zhu@taojiji.com
谢谢

**Comment by yidongnan** [comment]
服务注册都是调用 consul 的 api，而服务实现可以说是完全独立的逻辑，不太明白你所说的很难兼容的点。

**Comment by geercode** [comment]
consul可以开启http服务

**Comment by JasonWeeber** [comment]
我这边已经解决了这个问题了,通过配置consul的management-port,同时需要开启register-management
配置文件如下
# spring 配置
spring:
  cloud:
    consul:
      # 服务发现
      discovery:
        enabled: true
        health-check-path: /actuator/health
        # 注意java会把.转换成- 这个问题在处理kafka topic时也出现过
        service-name: java.micro.srv.bimsg
        instance-id: java.micro.srv.bimsg
        # 这个也要配,不然会使用机器名
        prefer-ip-address: true
        # 业务端口
        port: 9090
        # 健康检查端口
        management-port: 80
      port: 8500
      host: 192.168.30.33
    # 启动了注册管理,才会使用management-port进行健康检查,这个一定要是true
    service-registry:
      auto-registration:
        register-management: true
