### ISSUE TITLE
咨询支持其他注册中心

### ISSUE THREAD

**Issue by YiLanZhongShanXiao** [yidongnan/grpc-spring-boot-starter#232]
因为项目原因，注册中心使用阿里开源的nacos，请问后期会不会提供nacos的支持。另外，要扩展支持其他服务发现，应该怎样接入。

**Comment by yidongnan** [comment]
这里我们先调研看一下，目前项目跟 eureka 和 consul 的集成分别是以 metadata 和 tag 的形式，具体代码可以参考  [GrpcMetadataEurekaConfiguration.java](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java)  和 [GrpcMetadataEurekaConfiguration.java](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java)

**Comment by hc-romens** [comment]
> 因为项目原因，注册中心使用阿里开源的nacos，请问后期会不会提供nacos的支持。另外，要扩展支持其他服务发现，应该怎样接入。

我们也在尝试nacos+springboot+gRPC的组合。

**Comment by ST-DDT** [comment]
This might already be possible. If you use this library https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery#%E5%85%B3%E4%BA%8E-nacos-starter-%E6%9B%B4%E5%A4%9A%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9%E4%BF%A1%E6%81%AF

On the server side you have to configure the nacos metadata via the nacos properties. Set `...gRPC.port` to your gRPC port.

On the client side just use the target's service name as client name or configure the address like this: `discovery:///service-name` and you are ready to run.

-------------------

If you can find something like a nacos metadata customizer in that library I could add direct support for it.

**Comment by ST-DDT** [comment]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/685

**Comment by yidongnan** [comment]
Use [NacosRegistration.java](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosRegistration.java#L111) to configure nacos metadata. I will support this feature soon.
