### ISSUE TITLE
INTERNAL: http2 exception

### ISSUE THREAD

**Issue by 991697456** [yidongnan/grpc-spring-boot-starter#234]
hello master:

````txt
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
	at com.paic.gsd.cmd.pdns.grpc.tasks.TasksGrpc$TasksBlockingStub.sendLDNS(TasksGrpc.java:594)
	at com.paic.gsd.test.main(test.java:25)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by 991697456** [comment]
大师您好！我的java编写的客户端，访问go编写的Grpc服务端，出现以上异常，请教一下

**Comment by ST-DDT** [comment]
This might be related to this:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/README.md#issues-with-ssl-during-tests

Grpc-java client/channel/stub assumes that the server uses TLS for the service. You might need to set `grpc.client.clientname.negotiationType=PLAINTEXT` or at least review it.

**Comment by 991697456** [comment]
hi:master
  //创建指定服务的连接通道
  ManagedChannel channel =ManagedChannelBuilder
    .forAddress(grpcServerUrl, grpcServerPort)
    .usePlaintext().build();
  

 这里创建channel时已经使用了PLAINTEXT

 ------------------ 原始邮件 ------------------
  发件人: "ST-DDT"<notifications@github.com>;
 发送时间: 2019年6月1日(星期六) 凌晨0:43
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
This might be related to this:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/README.md#issues-with-ssl-during-tests
 
Grpc-java client/channel/stub assumes that the server uses TLS for the service. You might need to set grpc.client.clientname.negotiationType=PLAINTEXT or at least review it.

**Comment by ST-DDT** [comment]
If you create the `ManagedChannel` like that, then you don't actually use this library, do you? AFAICT thats plain grpc-java.

If you use the grpc-client-spring-boot-starter library then all you have to is

````java
@GrpcClient("tasks")
TasksBlockingStub tasksStub;

tasksStub.sendLDNS(...);
````
And configure the properties via `grpc.client.tasks.`.

-----------

Could you please post your main method/class? This allows me to analyse what might have gone wrong.

Grpc-java supports three different connection modes: `TLS`, `PLAINTEXT` and `PLAINTEXT_UPGRADE`. Have you tried them all?

**Comment by 991697456** [comment]
public static void main(String[] args) {
  ManagedChannel channel =ManagedChannelBuilder
    .forAddress("192.168.1.98", 18080)
    .usePlaintext().build();
  TasksBlockingStub tasksBlockingStub = TasksGrpc.newBlockingStub(channel);
  LocalDnsEntity localDnsEntity = new LocalDnsEntity("jhhjk","1.1.1.1","北京","上海","on","adjkhjakj");
  LDNS ldns = assembleLDNSDto(localDnsEntity);
  Feedback feedback = tasksBlockingStub.sendLDNS(ldns);
      
 }
 
 
 public  static LDNS assembleLDNSDto(LocalDnsEntity localDnsEntity) {//注意通讯骨架文件不接受set(null)
  com.paic.gsd.cmd.pdns.grpc.tasks.LDNS.Builder build = LDNS.newBuilder();
  if(!StringUtils.isEmpty(localDnsEntity.getISP())) {
   build.setCarrier(localDnsEntity.getISP());
  }else {
   build.setCarrier(LineConstants.DEFAULT_LINE);
  }
  if(!StringUtils.isEmpty(localDnsEntity.getProvince())) {
   build.setProvince(localDnsEntity.getProvince());
  }else {
   build.setProvince(LineConstants.DEFAULT_LINE);
  }
  if(!StringUtils.isEmpty(localDnsEntity.getLocalDnsIpCode())) {
   build.setUuid(localDnsEntity.getLocalDnsIpCode());
  }
  if(!StringUtils.isEmpty(localDnsEntity.getLocalDnsIp())) {
   build.setIp(localDnsEntity.getLocalDnsIp());
  }
        if(!CollectionUtils.isEmpty(localDnsEntity.getCreditIps())) {
         build.addAllCreditIp(localDnsEntity.getCreditIps());
        }
        build.setStatus(localDnsEntity.getStatus());
  return build.build();
 }

  

 

 ------------------ 原始邮件 ------------------
  发件人: "ST-DDT"<notifications@github.com>;
 发送时间: 2019年6月1日(星期六) 凌晨1:20
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
If you create the ManagedChannel like that, then you don't actually use this library, do you? AFAICT thats plain grpc-java.
 
If you use the grpc-client-spring-boot-starter library then all you have to is
 @GrpcClient("tasks") TasksBlockingStub tasksStub; tasksStub.sendLDNS(...);
 
And configure the properties via grpc.client.tasks..
 
 
Could you please post your main method/class? This allows me to analyse what might have gone wrong.
 
Grpc-java supports three different connection modes: TLS, PLAINTEXT and PLAINTEXT_UPGRADE. Have you tried them all?

**Comment by 991697456** [comment]
我这边依据从zookeeper 获取的节点信息来动态创建channel的，因此我放弃使用注解的形势：@GrpcClient("tasks")，将对应的channel放入内存中，后续匹配使用发送到指定的服务端


  

 ------------------ 原始邮件 ------------------
  发件人: "我自己的邮箱"<991697456@qq.com>;
 发送时间: 2019年6月1日(星期六) 凌晨1:24
 收件人: "yidongnan/grpc-spring-boot-starter"<reply@reply.github.com>;
 
 主题: 回复： [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

  
  public static void main(String[] args) {
  ManagedChannel channel =ManagedChannelBuilder
    .forAddress("192.168.1.98", 18080)
    .usePlaintext().build();
  TasksBlockingStub tasksBlockingStub = TasksGrpc.newBlockingStub(channel);
  LocalDnsEntity localDnsEntity = new LocalDnsEntity("jhhjk","1.1.1.1","北京","上海","on","adjkhjakj");
  LDNS ldns = assembleLDNSDto(localDnsEntity);
  Feedback feedback = tasksBlockingStub.sendLDNS(ldns);
      
 }
 
 
 public  static LDNS assembleLDNSDto(LocalDnsEntity localDnsEntity) {//注意通讯骨架文件不接受set(null)
  com.paic.gsd.cmd.pdns.grpc.tasks.LDNS.Builder build = LDNS.newBuilder();
  if(!StringUtils.isEmpty(localDnsEntity.getISP())) {
   build.setCarrier(localDnsEntity.getISP());
  }else {
   build.setCarrier(LineConstants.DEFAULT_LINE);
  }
  if(!StringUtils.isEmpty(localDnsEntity.getProvince())) {
   build.setProvince(localDnsEntity.getProvince());
  }else {
   build.setProvince(LineConstants.DEFAULT_LINE);
  }
  if(!StringUtils.isEmpty(localDnsEntity.getLocalDnsIpCode())) {
   build.setUuid(localDnsEntity.getLocalDnsIpCode());
  }
  if(!StringUtils.isEmpty(localDnsEntity.getLocalDnsIp())) {
   build.setIp(localDnsEntity.getLocalDnsIp());
  }
        if(!CollectionUtils.isEmpty(localDnsEntity.getCreditIps())) {
         build.addAllCreditIp(localDnsEntity.getCreditIps());
        }
        build.setStatus(localDnsEntity.getStatus());
  return build.build();
 }

  

 

 ------------------ 原始邮件 ------------------
  发件人: "ST-DDT"<notifications@github.com>;
 发送时间: 2019年6月1日(星期六) 凌晨1:20
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
If you create the ManagedChannel like that, then you don't actually use this library, do you? AFAICT thats plain grpc-java.
 
If you use the grpc-client-spring-boot-starter library then all you have to is
 @GrpcClient("tasks") TasksBlockingStub tasksStub; tasksStub.sendLDNS(...);
 
And configure the properties via grpc.client.tasks..
 
 
Could you please post your main method/class? This allows me to analyse what might have gone wrong.
 
Grpc-java supports three different connection modes: TLS, PLAINTEXT and PLAINTEXT_UPGRADE. Have you tried them all?

**Comment by 991697456** [comment]
------------------ 原始邮件 ------------------
  发件人: "ST-DDT"<notifications@github.com>;
 发送时间: 2019年6月1日(星期六) 凌晨0:43
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
This might be related to this:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/README.md#issues-with-ssl-during-tests
 
Grpc-java client/channel/stub assumes that the server uses TLS for the service. You might need to set grpc.client.clientname.negotiationType=PLAINTEXT or at least review it.

**Comment by ST-DDT** [comment]
From the code example it looks like you did everything alright. If you tried all connection/negotiationType i have mentioned then there might be an actual bug in either of the libraries and You might need to repeat your question in the grpc-java issuetracker: https://github.com/grpc/grpc-java/issues

Which version of grpc-java are you using?

Grpc-java and thus this library supports custom NameResolvers. You could wrap your zookerper logic in one of them. Have a look at these examples for a hint on how to implement them: https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver
Or if you post the logic I could try to implement it for you.

**Comment by 991697456** [comment]
我本地起一个客户端，一个服务端，通讯是没问题的，但是当我连接对方用Go编写的服务端，（此服务端是在服务器上运行的，我的是本地电脑），当我把我的服务也部署到服务器，还是会出现 INternal http2 excePtion

  

 ------------------ 原始邮件 ------------------
  发件人: "我自己的邮箱"<991697456@qq.com>;
 发送时间: 2019年6月1日(星期六) 凌晨2:00
 收件人: "yidongnan/grpc-spring-boot-starter"<reply@reply.github.com>;
 
 主题: 回复： [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "ST-DDT"<notifications@github.com>;
 发送时间: 2019年6月1日(星期六) 凌晨0:43
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
This might be related to this:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/README.md#issues-with-ssl-during-tests
 
Grpc-java client/channel/stub assumes that the server uses TLS for the service. You might need to set grpc.client.clientname.negotiationType=PLAINTEXT or at least review it.

**Comment by 991697456** [comment]
确切的讲，我并没有引入grpc-java我使用的是    <groupId>net.devh</groupId>
    <artifactId>grpc-spring-boot-starter</artifactId>
    <version>1.4.1.RELEASE</version> 附带的jar包，这里面的grpc-core-1.12.0.jar，
 对于zookeeper动态实现创建channel我这边实现是没问题的，
  
  
  

 

 ------------------ 原始邮件 ------------------
  发件人: "ST-DDT"<notifications@github.com>;
 发送时间: 2019年6月1日(星期六) 凌晨2:04
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
From the code example it looks like you did everything alright. If you tried all connection/negotiationType i have mentioned then there might be an actual bug in either of the libraries and You might need to repeat your question in the grpc-java issuetracker: https://github.com/grpc/grpc-java/issues
 
Which version of grpc-java are you using?
 
Grpc-java and thus this library supports custom NameResolvers. You could wrap your zookerper logic in one of them. Have a look at these examples for a hint on how to implement them: https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver
Or if you post the logic I could try to implement it for you.

**Comment by yidongnan** [comment]
> 本地起一个客户端，一个服务端，通讯是没问题的，但是当我连接对方用Go编写的服务端，（此服务端是在服务器上运行的，我的是本地电脑），当我把我的服务也部署到服务器，还是会出现 INternal http2 excePtion

你这里的意思是本地使用 java 编写客户端、服务端能正常通讯，但调用远程的服务器（golang 或者 java 编写）的都存在这样的问题？

> 确切的讲，我并没有引入grpc-java我使用的是    <groupId>net.devh</groupId>
    <artifactId>grpc-spring-boot-starter</artifactId>
    <version>1.4.1.RELEASE</version> 附带的jar包，这里面的grpc-core-1.12.0.jar，
 对于zookeeper动态实现创建channel我这边实现是没问题的，

这个项目只是在 grpc-java 上做了一些封装，简化跟 spring 体系的搭配使用，对于上面的问题，你可以试试直接依赖 grpc-java，使用最基础的方式创建 Channel，看是否存在同样的问题？ @991697456

**Comment by 991697456** [comment]
我尝试了只引入grpc-java创建channel连接，还是存在上述问题：
 
附属测试代码以及异常信息：
 

 public static void main(String[] args) {
  ManagedChannel channel =ManagedChannelBuilder
    .forAddress("X.X.X.X", 18080).usePlaintext()
    .build();
  TasksBlockingStub tasksBlockingStub = TasksGrpc.newBlockingStub(channel);
  LocalDnsEntity localDnsEntity = new LocalDnsEntity("jhhjk","1.1.1.1","北京","上海","on","adjkhjakj");
  LDNS ldns = assembleLDNSDto(localDnsEntity);
  Feedback feedback = tasksBlockingStub.sendLDNS(ldns);
      
 }
 
 
 public  static LDNS assembleLDNSDto(LocalDnsEntity localDnsEntity) {//注意通讯骨架文件不接受set(null)
  com.paic.gsd.cmd.pdns.grpc.tasks.LDNS.Builder build = LDNS.newBuilder();
  if(!StringUtils.isEmpty(localDnsEntity.getISP())) {
   build.setCarrier(localDnsEntity.getISP());
  }else {
   build.setCarrier(LineConstants.DEFAULT_LINE);
  }
  if(!StringUtils.isEmpty(localDnsEntity.getProvince())) {
   build.setProvince(localDnsEntity.getProvince());
  }else {
   build.setProvince(LineConstants.DEFAULT_LINE);
  }
  if(!StringUtils.isEmpty(localDnsEntity.getLocalDnsIpCode())) {
   build.setUuid(localDnsEntity.getLocalDnsIpCode());
  }
  if(!StringUtils.isEmpty(localDnsEntity.getLocalDnsIp())) {
   build.setIp(localDnsEntity.getLocalDnsIp());
  }
        if(!CollectionUtils.isEmpty(localDnsEntity.getCreditIps())) {
         build.addAllCreditIp(localDnsEntity.getCreditIps());
        }
        build.setStatus(localDnsEntity.getStatus());
  return build.build();
 }
 
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: http2 exception
 at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
 at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
 at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
 at com.paic.gsd.cmd.pdns.grpc.tasks.TasksGrpc$TasksBlockingStub.sendLDNS(TasksGrpc.java:594)
 at com.paic.gsd.test.main(test.java:26)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
 at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
 at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
 at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
 at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:748)

  




------------------ 原始邮件 ------------------
发件人: "Michael Zhang"<notifications@github.com>; 
发送时间: 2019年6月2日(星期天) 中午12:04
收件人: "yidongnan/grpc-spring-boot-star"<grpc-spring-boot-starter@noreply.github.com>; 
抄送: "崔宝玉"<991697456@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)



 
本地起一个客户端，一个服务端，通讯是没问题的，但是当我连接对方用Go编写的服务端，（此服务端是在服务器上运行的，我的是本地电脑），当我把我的服务也部署到服务器，还是会出现 INternal http2 excePtion
 
你这里的意思是本地使用 java 编写客户端、服务端能正常通讯，但调用远程的服务器（golang 或者 java 编写）的都存在这样的问题？
  
确切的讲，我并没有引入grpc-java我使用的是 net.devh
grpc-spring-boot-starter
1.4.1.RELEASE 附带的jar包，这里面的grpc-core-1.12.0.jar，
对于zookeeper动态实现创建channel我这边实现是没问题的，
 
这个项目只是在 grpc-java 上做了一些封装，简化跟 spring 体系的搭配使用，对于上面的问题，你可以试试直接依赖 grpc-java，使用最基础的方式创建 Channel，看是否存在同样的问题？ @991697456

**Comment by ST-DDT** [comment]
I also found this question with an answer on stackoverflow: https://stackoverflow.com/questions/55649096/not-able-to-connect-to-grpc-server-getting-first-received-frame-was-not-setting/55655555#55655555

According to that link: 

> Hex dump for first 5 bytes: 485454502f

Contains `HTTP/` in the content which might indicate that you tried contacting a HTTP/1 web server. Are you sure that the server details received from zookeeper refer to an grpc service? Maybe you need to use a different port?

**Comment by 991697456** [comment]
我这边使用zookeeper 只是获取一些节点信息，它并没有参与到grpc service的过程中
  

 

 ------------------ 原始邮件 ------------------
  发件人: "ST-DDT"notifications@github.com;
 发送时间: 2019年6月2日(星期天) 晚上8:06
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
I also found this question with an answer on stackoverflow: https://stackoverflow.com/questions/55649096/not-able-to-connect-to-grpc-server-getting-first-received-frame-was-not-setting/55655555#55655555
 
According to that link:
  
Hex dump for first 5 bytes: 485454502f
 
Contains HTTP/ in the content which might indicate that you tried contacting a HTTP/1 web server. Are you sure that the server details received from zookeeper refer to an grpc service? Maybe you need to use a different port?

**Comment by 991697456** [comment]
Thank you for all your support！问题已经解决：原因是对方go项目部署的环境端口：被Nginx端口占用（18080），造成我这边客户端调用的不是Grpc体系，而是其他项目（默认是http1.1）,出现此异常：INTERNAL: http2 exception 
  

 

 ------------------ 原始邮件 ------------------
  发件人: "ST-DDT"<notifications@github.com>;
 发送时间: 2019年6月2日(星期天) 晚上8:06
 收件人: "yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com>;
 抄送: "崔宝玉"<991697456@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [yidongnan/grpc-spring-boot-starter] INTERNAL: http2 exception(#234)

 

 
I also found this question with an answer on stackoverflow: https://stackoverflow.com/questions/55649096/not-able-to-connect-to-grpc-server-getting-first-received-frame-was-not-setting/55655555#55655555
 
According to that link:
  
Hex dump for first 5 bytes: 485454502f
 
Contains HTTP/ in the content which might indicate that you tried contacting a HTTP/1 web server. Are you sure that the server details received from zookeeper refer to an grpc service? Maybe you need to use a different port?
