### ISSUE TITLE
Switch to NameResolverRegistry

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#237]
In grpc-java a new client side feature as introduced, namely the `NameResolverRegistry`.

These registry allows the registration of spring-initialized/populated `NameResolverProvider` beans, which greatly simplifies the interoperatability of these custom components.

However using this class would break backwards compatibility with earlier versions of grpc-java (including grpc-java 1.20 and earlier).

@yidongnan Shall we use this feature or shall we wait? Maybe wait one release (-> 2.6.0)?

* https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java#L129
* https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcDiscoveryClientAutoConfiguration.java#L43
* Some `NameResolver.Factory`s and all `NameresolverProvider`s

**Comment by ST-DDT** [comment]
Related: #238

**Comment by yidongnan** [comment]
I think we can wait one release,  we can use this feature in 2.6.0.

**Comment by ST-DDT** [comment]
TODO: Improve configurability of default scheme.

**Comment by ST-DDT** [comment]
Work in progress
