### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#239]
I plan to extend the documentation for this project and split it into separate pages.

Now, the question is which feature should we use for that purpose?
The GitHub Pages using the `/docs` folder or the github wiki feature?

Example-GitHub Pages:
https://st-ddt.github.io/grpc-spring-boot-starter/
~~I don't have an example wiki yet:~~
~~https://github.com/ST-DDT/grpc-spring-boot-starter/wiki~~

-----------------------

At the moment, I have the following topics in mind:

- [x] Index
- Server
  - [x] Getting Started
  - [x] Configuration
  - [x] Contextual Data / Scoped Beans
  - [x] Testing the Service
  - [x] Security
- Client
  - [x] Getting Started
  - [x] Configuration
  - [x] Security
- [x] Spring Boot Actuator / Metrics Support
- [x] Brave-Tracing / Spring Cloud Sleuth Support
- [ ] Others setups
- [x] Trouble-Shooting
- [x] Example Projects
- [x] Version Overview
- [x] Benchmarking
- [x] Contributing

Anything missing? Or should I change some of the topics?

**Comment by yidongnan** [comment]
It looks so great, is there any way to support other languages?

**Comment by ST-DDT** [comment]
Using a quick search I found this page: https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/

I haven't tried it though. I also considered a flat approach `/en/index.md` which encodes the language in the path. I'll probably try both variants. It might take a while though.

**Comment by ST-DDT** [comment]
Progress ~50%

**Comment by ST-DDT** [comment]
~80%

**Comment by asarkar** [comment]
Can you add a section about monitoring, please? The current docs have _"Automatic metric support (micrometer/actuator based)"_ which is as vague as they come.

**Comment by ST-DDT** [comment]
> Can you add a section about monitoring, please? The current docs have _"Automatic metric support (micrometer/actuator based)"_ which is as vague as they come. What metrics are collected by default?

That's a good idea. I'll add it to the list.

> How do we disable metrics collection (actually it should be opt-in, not opt-out, but that doesn't seem to be case based on the above statement).

First of all, having the actuator libs on your CP is optional and we don't include them in our transitive dependencies. If those libs aren't present, then this library won't collect any metrics. But if the libs are present, then I follow the spring-boot-actuator default and just collect the metrics. Do you have an example for a library where it is explicit opt-in?

**Comment by ST-DDT** [comment]
@asarkar: I finished the [Actuator / Metrics](https://st-ddt.github.io/grpc-spring-boot-starter/actuator) page.



Would you mind reviewing that page? Does it explain everything you need/want to know?

I will extend that page as soon as I have added the grpc thread pool metrics.

**Comment by asarkar** [comment]
@ST-DDT thanks for the quick turnaround. I'll review the changes later today and provide my feedback, if any. Regarding thread pool metrics, you may want to take a look at the project I linked to above, it already captures those. Of course, you can also do it without referring to my project, but it might save you time.

**Comment by asarkar** [comment]
> Do you have an example for a library where it is explicit opt-in?

Actuator is more intrusive than some people like, there is an open ticket for that too. Since metrics collection is a cross-cutting concern, and can degrade performance is done wrong, I think enabling is by default is sort of imposing. Also, actuator does more than just metrics collection; simply it's presence may not necessarily indicate the consent to start monitoring calls.

I think the metrics should be a separate module, and not conflated with the core, whose purpose is to get started quickly and easily. If someone adds `grpc-spring-boot-metrics-starter` explicitly to classpath, there's no doubt about what they have in mind.

**Comment by asarkar** [comment]
@ST-DDT I reviewed the metrics page and it looks good. I've couple of minor comments:

1. Method and service names: I suggest clarifying whether the names are from the proto files or the Java code. Conventionally, method names in proto files start with capital letter whereas Java method names start with small letter.
2. `gprc.client.processing.duration`: The description says server, probably a copy-paste error.

**Comment by ST-DDT** [comment]
> `gprc.client.processing.duration`: The description reads a little confusing, as if the timing is for the server. Rephrasing it might help.

@asarkar Like this?

> - `grpc.client.processing.duration`: The total time from sending the call to the server until its completion. This includes network delay.
> - `grpc.server.processing.duration`: The total time taken for the server to complete the call.

Or what would you suggest?

**Comment by asarkar** [comment]
`grpc.client.processing.duration`: Why not simply, "The total time taken for the client to complete the call, including network delay."?

**Comment by ST-DDT** [comment]
Fixed

**Comment by ST-DDT** [comment]
IMO we should first release 2.5.0 and then we can start merging this beast.

@yidongnan Should we release version 2.5.0 after merging the two new/open PRs, or do you want to add some more features first?

**Comment by yidongnan** [comment]
@ST-DDT OK，My wife delivered a baby last month, there are still a lot of things to deal with recently, but I will complete these reviews and release 2.5.0 as soon as possible.

**Comment by ST-DDT** [comment]
Congratulations. Thanks for your time.

**Comment by yidongnan** [comment]
Thanks 😄

**Comment by ST-DDT** [comment]
TODO: Server unit test documentation - add note regarding auto configuration and bean discovery

**Comment by ST-DDT** [comment]
TODO: Add requirements for using actuator (e.g. webserver), its impacts (e.g. additional ports)

https://st-ddt.github.io/grpc-spring-boot-starter/actuator

Ref: https://github.com/yidongnan/grpc-spring-boot-starter/issues/251#issuecomment-521242234

**Comment by ST-DDT** [comment]
@horiadruliac FYI: I extended the [server testing page](https://st-ddt.github.io/grpc-spring-boot-starter/server/testing)

**Comment by ST-DDT** [comment]
@towe75 FYI: I extended the [actuator page](https://st-ddt.github.io/grpc-spring-boot-starter/actuator). Feedback welcome.

**Comment by ST-DDT** [comment]
@yidongnan slightly off topic, but can you bump the version to `2.6.0-SNAPSHOT` again? Then I will create a PR for the docs.

**Comment by ST-DDT** [comment]
Will be implemented via #274
