### ISSUE TITLE
Random grpc ports, when server restart, client can't update service instance info

### ISSUE THREAD

**Issue by alienxt** [yidongnan/grpc-spring-boot-starter#240]
DiscoveryClientNameResolver.isNeedToUpdateServiceInstanceList() just only check service's host and port. If server config static server port and random grpc port, the client will not connect to the server.

**Comment by ST-DDT** [comment]
You are right. We will fix it in the next release.

**Comment by ST-DDT** [comment]
I created a draft with a potential fix #241 . Please verify whether it fixes the issue for you.
