### ISSUE TITLE
address: dns:///grpctest 当grpctest后端动态增加了服务节点后.负载均衡始终分配不到新增加的服务节点上

### ISSUE THREAD

**Issue by yanfulei** [yidongnan/grpc-spring-boot-starter#245]
使用address: dns:///grpctest后
1.当前grpctest后端有2个服务节点
2.当我在grpctest后端增加一个节点变为3个节点后
3.第三个节点始终无法被访问到
4.是不是有dns刷新的方法

**Comment by yanfulei** [comment]
必须重启整个服务节点,或者重启client后,才能是三个服务节点同时工作

**Comment by ST-DDT** [comment]
The dns resolver is provided by [grpc-java](https://github.com/grpc/grpc-java) so you might have to repeat your question there. 
IIRC there is no way to refresh the NameResolver. However it will refresh them, if an existing server becomes unavailable.

According to https://github.com/grpc/grpc-java/issues/2514 it is not possible to trigger it manually but you can cofigure `MAX_CONNECTION_AGE` to re-resolve the addresses. But of course this has other side effects.

**Comment by yanfulei** [comment]
MAX_CONNECTION_AGE 在哪儿设置

**Comment by yanfulei** [comment]
@ST-DDT MAX_CONNECTION_AGE 在哪儿设置
