### ISSUE TITLE
[Feature Request] Change `AuthenticatingServerInterceptor` to be defined as an interface instead of concrete class in the autoconfiguration class.

### ISSUE THREAD

**Issue by pluttrell** [yidongnan/grpc-spring-boot-starter#249]
`GrpcServerSecurityAutoConfiguration` defines three beans, one of which is:
```
@Bean
@ConditionalOnMissingBean
public AuthenticatingServerInterceptor authenticatingServerInterceptor(final AuthenticationManager authenticationManager, final GrpcAuthenticationReader authenticationReader) {
    return new AuthenticatingServerInterceptor(authenticationManager, authenticationReader);
}
```
Note that `AuthenticatingServerInterceptor` is a concrete class, so if you want to override it, you must do all of the following: (1) exclude `GrpcServerSecurityAutoConfiguration` from auto configuration, (2) define your own configuration class that provides the other two beans and the interceptor that you'd prefer and (3) define your interceptor. 

But if this bean definition were changed to an interface, then all we'd need to do to override it is to define our own bean of that interface type and then the `@ConditionalOnMissingBean` would prevent the default implementation from being added to the `ApplicationContext`.

**Comment by ST-DDT** [comment]
This is a good idea!

**Comment by ST-DDT** [comment]
Like this: #250 ?

**Comment by pluttrell** [comment]
Yep.
