### ISSUE TITLE
What's the reason for AuthenticatingServerInterceptor's attaching/detaching of the gRPC Context?

### ISSUE THREAD

**Issue by pluttrell** [yidongnan/grpc-spring-boot-starter#252]
I'm working on creating a replacement for the `AuthenticatingServerInterceptor` for use with Reactive Spring Security. 

As you'd expect new Interceptor does the same Spring authentication process, but then it just places the resulting `Authentication` instance in the gRPC Context. Then on **each** Reactive stream definition, the user must provide a new _Reactive_ Context instance to the `subscriberContext` as described [here](https://docs.spring.io/spring-security/site/docs/5.2.0.M3/reference/htmlsingle/#jc-erms). A _Reactive_ Context can be easily created by calling `ReactiveSecurityContextHolder.withAuthentication(..)`, where the `Authentication` instance is retrieved from the gRPC Context. For example:
```
.subscriberContext(
    ReactiveSecurityContextHolder.withAuthentication(
           {your-Context.Key-instance}.get()
    )
)
```

I see that `AuthenticatingServerInterceptor` attaches and detaches the gRPC context in six places. I'm assuming it's doing this to activate the current `SecurityContext` for the active thread, since `SecurityContextHolder` is likely to be using `ThreadLocal` storage. My questions is: Is there any other reason it does this attaching and detaching? 

Since the new Interceptor doesn't use the non-reactive `SecurityContextHolder` anywhere, it seams logical to remove the attaching and detaching, which significantly simplifies the implementation.

**Comment by ST-DDT** [comment]
The grpc context has nothing to do with the spring (security) context.
My current implementation simply attaches the authentication to both the grpc-context and spring-security-context.

````java
final Context previous = this.context.attach();
try {
    SecurityContextHolder.getContext().setAuthentication(this.authentication);
    log.debug("onMessage - Authentication set");
    super.onMessage(message);
} finally {
    SecurityContextHolder.clearContext();
    this.context.detach(previous);
    log.debug("onMessage - Authentication cleared");
}
````

Spring doesn't care at all about the value in the grpc-context, but the implementor of the grpc-service class is inside the grpc code and thus might want to access the authentication using grpc's style.

As for whether grpc-context should/can be accessed or has special requirements please ask this question in the reactive grpc-java repo and link it here.

**Comment by pluttrell** [comment]
@ST-DDT Thanks for the additional clarification.

> Are you referring to #250 ? It still attaches them both. Just separated into different classes for reusability.

No, I hadn't actually looked at the implantation before adding this question. I have however since, and added a comment regarding such.
