### ISSUE TITLE
YAML kebab case not working on inProcessName

### ISSUE THREAD

**Issue by internetstaff** [yidongnan/grpc-spring-boot-starter#253]
I ran into this upgrading to 2.4.0 and moving my in-process and keepalive configs from code to config files.

I'm using a lot of client and server properties in yaml files, and all of them appear to be working except inProcessName/in-process-name.  I have to use camel case for it to be set properly. 

I haven't found an obvious cause yet.

**Comment by ST-DDT** [comment]
I can reproduce this error and will PR a fix soon.

**Comment by ST-DDT** [comment]
I just created the fix PR #254 . I explained the (stupid) cause of the bug there.^^

Thanks for reporting this.

**Comment by internetstaff** [comment]
thanks!
