### ISSUE TITLE
Testing using the grpc-spring-boot-starter?

### ISSUE THREAD

**Issue by horiadruliac** [yidongnan/grpc-spring-boot-starter#269]
My application must add an entity to the database and restore all elements.

Whilst testing, should I create my own separate client class and use the @GrpcClient annotation to help me 'wire' it in my test class? Should I create the Stub in the testing class? 
What would be the easiest implementation?

In the documentation for testing offered by SD-DDT (https://st-ddt.github.io/grpc-spring-boot-starter/server/testing#unit-tests) it is recommended to just autowire the Service Implementation, but if I annotate my service class implementation with "@GrpcService", IntelliJ writes that it could not autowire (in the test class).

--

* Spring (boot): 2.1.6
* grpc-spring-boot-starter: latest
* java: version + architecture (64bit?) 11

**Comment by ST-DDT** [comment]
From your description I assume that you want to test the server side.

> Whilst testing, should I create my own separate client class and use the @GrpcClient annotation to help me 'wire' it in my test class? Should I create the Stub in the testing class?

IMO there is no benefit in creating a container class for the client, just inject it directly to the test as done in this [example](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/security/ConcurrentSecurityTest.java#L70).

> What would be the easiest implementation?

The easiest solution is writing unit tests, as it contains far less variables.
The link you have copied refers to the right location.

> In the documentation for testing offered by ST-DDT (https://st-ddt.github.io/grpc-spring-boot-starter/server/testing#unit-tests) it is recommended to just autowire the Service Implementation, but if I annotate my service class implementation with "@GrpcService", IntelliJ writes that it could not autowire (in the test class).

The  `@GrpcService` annotation on the service class doesn't have any influence on your unit tests, it is only relevant if you run the server (or integration tests).
During tests spring does not automatically perform any auto configuration, thus you have to define the beans yourself. See this libraries tests: The [test classes](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/security/ConcurrentSecurityTest.java#L61) declare a [config](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/config/ServiceConfiguration.java#L29) that explicitly creates the required beans / [services](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/server/TestServiceImpl.java#L41).

I will [extend the documentation](https://github.com/yidongnan/grpc-spring-boot-starter/issues/239#issuecomment-521213437) with a hint regarding this matter.

Does this answer your question?

**Comment by horiadruliac** [comment]
In terms of test class annotations. Would @ExtendWith and @ContextConfiguration (where I specify the configuration class that points to the properties) work similarily to the ones mentioned in the [example](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/security/ConcurrentSecurityTest.java#L70). ("@Slf4j, @SpringBootTest, @SpringJUnitConfig, @DirtiesContext). (I am using JUnit 5)

**Comment by ST-DDT** [comment]
* `@Slf4j` for logging only (lombok)
* [`@SpringBootTest`](https://github.com/spring-projects/spring-boot/blob/287caa210b25712b14b1b3ae6c1e9ffc4b991315/spring-boot-project/spring-boot-test/src/main/java/org/springframework/boot/test/context/SpringBootTest.java#L80-L82) ~= `@ExtendWith(SpringExtension.class)` + spring bootstrap
* [`@SpringJUnitConfig`](https://github.com/spring-projects/spring-framework/blob/master/spring-test/src/main/java/org/springframework/test/context/junit/jupiter/SpringJUnitConfig.java#L56) ~= `@ContextConfiguration(...)` + `@ExtendWith(SpringExtension.class)`
* `@DirtiesContext` not needed for unit tests (ensures that the server grpc server shuts down after each test)

I'm not sure whether all our tests actually need all of their annotations.
Maybe I should check that the next time I touch the test.

> I am using JUnit 5

This library uses the same.

**Comment by horiadruliac** [comment]
Ok!
Thank you for the explanation.

So in order to test a gRPC service (let's say an "addElement" Service), I will have to add the `@GrpcClient("local-grpc-server")` with the corresponding Stub declaration. But when I do that it will give a NullPointerException (from the line where I perform the addition method using the Stub, which seems to be Null). Does that mean that I need to perform any other configuration for the client?
I annotated the test with `@ContextConfiguration(classes = {Config.class}`). (should I add a bean corresponding to the client inside the mentioned class?)

**Comment by ST-DDT** [comment]
> So in order to test a gRPC service (let's say an "addElement" Service), I will have to add the `@GrpcClient("local-grpc-server")` with the corresponding Stub declaration.

Only if you do integration tests.

>  But when I do that it will give a NullPointerException (from the line where I perform the addition method using the Stub, which seems to be Null). Does that mean that I need to perform any other configuration for the client?
I annotated the test with @ContextConfiguration(classes = {Config.class}). (should I add a bean corresponding to the client inside the mentioned class?)

For the `@grpcClient` annotation to work you need a [`GrpcClientBeanPostProcessor`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java) [`@Bean` definition](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java#L64).

----------------------------------------------------------

This is an example grpc service unit test.

**MyServiceService**

````java
public class MyServiceService extends MyServiceGrpc.MyServiceImplBase {

    @Autowired
    private OtherDependency foobar;

    @Override
    public void ping(PingRequest request, ResponseObserver<RingResponse> resposneObserver) {
        PingResponse response = PingResponse.newBuilder()
                .setResponseText(request.getRequestText())
                .setCounter(foobar.getCount())
                .build();
        responseObserver.onNext(response);
        responseObserver.onComplete();
    }

}
````

**MyServiceUnitTest**

````java
@SpringBootTest
@SpringJUnitConfig(classes = MyServiceTestConfiguration.class)
public class MyServiceUnitTest {

    @Autowired
    private MyServiceService service;

    @Test
    void testPing() {
        PingRequest request = PingRequest.newBuilder()
                .setMessage("PingTest")
                .build();
        StreamRecorder<PingResponse> responseObserver = StreamRecorder.create();
        service.ping(request, responseObserver);
        if (!responseObserver.awaitCompletion(5, TimeUnit.SECONDS);
            fail("The call did not terminate in time");
        }
        assertNull(responseObserver.getError());
        List<PingResponse> results = responseObserver.getValues().size();
        assertEquals(1, results.size());
        PingResponse response = results.get(0);
        assertEquals(PingResponse.newBuilder()
                .setResponseText("PingTest")
                .setCounter(1337)
                .build(), response);
        }

}
````

**MyServiceTestConfiguration**

````java
@Configuration
public class MyServiceTestConfiguration {

    @Bean
    OtherDependency foobar() {
        // return Mockito.mock(OtherDependency.class);
    }

    @Bean
    MyServiceService service() {
        return new MyService();
    }

}
````

**Comment by horiadruliac** [comment]
That was very helpful!
Thank you!

**Comment by ST-DDT** [comment]
Is everything clear now or do you have any further questions?

**Comment by horiadruliac** [comment]
That's alright!
Cheers for the help!
