### ISSUE TITLE
正式版Spring Cloud Alibaba Nacos作为注册中心没办法调用

### ISSUE THREAD

**Issue by jimmy384** [yidongnan/grpc-spring-boot-starter#271]
Spring Cloud Alibaba 发布正式版后包名换了
old package
org.springframework.cloud.alibaba.nacos.NacosDiscoveryProperties;
org.springframework.cloud.alibaba.nacos.registry.NacosRegistration;

new package
com.alibaba.cloud.nacos.NacosDiscoveryProperties;
com.alibaba.cloud.nacos.registry.NacosRegistration;

GrpcMetadataNacosConfiguration包名对不上自动配置不生效，导致没有向注册中心设置metadata记录grpc端口，导致调用不了。

**Comment by ST-DDT** [comment]
Thanks for reporting this incompatibility to us, we will fix it in the next release.

Which version are you using? in 2.5.1 (2.5.0) we changed the logic to default to the specified server port if the grpc port metadata value is not present.

**Comment by jimmy384** [comment]
I use 2.5.0.

**Comment by jimmy384** [comment]
> Thanks for reporting this incompatibility to us, we will fix it in the next release.
> 
> Which version are you using? in 2.5.1 (2.5.0) we changed the logic to default to the specified server port if the grpc port metadata value is not present.



> Thanks for reporting this incompatibility to us, we will fix it in the next release.
> 
> Which version are you using? in 2.5.1 (2.5.0) we changed the logic to default to the specified server port if the grpc port metadata value is not present.

I use 2.5.0.

**Comment by ST-DDT** [comment]
Is https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-alibaba-cloud/ the new project/artifact?
Did they announce the package change somewhere?

**Comment by jimmy384** [comment]
> Is https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-alibaba-cloud/ the new project/artifact?
> Did they announce the package change somewhere?

Here is the new project/artifact
https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-alibaba-dependencies/2.1.0.RELEASE
In https://github.com/alibaba/spring-cloud-alibaba Version control guidelines section, they made a slight mention about version, but I can't find announcement about package changes. I know package changes from some articles. https://blog.csdn.net/weixin_43970890/article/details/95060885

**Comment by ST-DDT** [comment]
Will be fixed with #279
