### ISSUE TITLE
Upgrade stack to support java 11

### ISSUE THREAD

**Issue by ndaqjn** [yidongnan/grpc-spring-boot-starter#278]
It's impossible to use this on a stack with java 11. I get warnings and unmarshalling problems.
These are my current versions for the key components, which matches the project.
```
        <grpc.version>1.22.2</grpc.version>
        <protobuf.version>3.8.0</protobuf.version>
        <spring.version>2.1.6.RELEASE</spring.version>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
```
When running the application I get the following on the server side
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/jonn/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

And on the client
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/jonn/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom([Ljava/lang/String;[Lcom/google/protobuf/Descriptors$FileDescriptor;)Lcom/google/protobuf/Descriptors$FileDescriptor;

```

In parallell I've tried the following version combination that seems to work

```
        <grpc.version>1.23.0</grpc.version>
        <protobuf.version>3.9.0</protobuf.version>
        <spring.version>2.1.7.RELEASE</spring.version>
```

My hope is that the project could switch to these later versions.

**Comment by ST-DDT** [comment]
Which version of grpc-spring-boot-starter are you using?

> protobuf-java-3.6.1.jar

According to your logs you seem to use an outdated version of protobuf. Please check your dependency tree for its source.

I use this library with java 11 and dont have any issues with it.

**Comment by ndaqjn** [comment]
```
            <groupId>net.devh</groupId>
            <artifactId>grpc-spring-boot-starter</artifactId>
            <version>2.5.1.RELEASE</version>
```

**Comment by ST-DDT** [comment]
That version uses protobuf 3.8.0 
https://search.maven.org/artifact/net.devh/grpc-server-spring-boot-starter/2.5.1.RELEASE/jar
Can you paste your dependency tree? I assume you get the outdated protobuf version somewhere else.

**Comment by ndaqjn** [comment]
I agree, thanks for pointing that out.

 The original request still stands though. Either update the versions or make the dependencies "provided". The enforcer plugin will barf otherwise.

**Comment by ST-DDT** [comment]
Updated dependencies in #279

-------------

> The enforcer plugin will barf otherwise.

What exactly does the enforce plugin do/What it is used for?
