### ISSUE TITLE
Mocking grpc client during testing another service 

### ISSUE THREAD

**Issue by sanchesfrolov** [yidongnan/grpc-spring-boot-starter#282]
I have a service which contains a stub marked @GrpcClient annotation.
Actually, my service looks like an example from your Getting Started [page](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/getting-started#client-project):
```
@Service
public class FoobarService {

    @GrpcClient("myService")
    private MyServiceBlockingStub myServiceStub;

    public String receiveGreeting(String name) {
        HelloRequest request = HelloRequest.newBuilder()
                .setName(name)
                .build()
        return myServiceStub.sayHello(request).getMessage();
    }

```
}

So my question is what is the best way to test  receiveGreeting method and mock a call of the myServiceStub.sayHello method ?
I can't do it just by mocking MyServiceBlockingStub class because it is final and gprc framework authors say it is Ok and recommend this [approach  ](https://github.com/grpc/grpc-java/tree/v1.13.x/examples#unit-test-examples), but it is not suitable in my case.

**Comment by ST-DDT** [comment]
The inprocess approach works like this:

1) Add the following dependencies to your project:

````xml
<dependency>
  <groupId>net.devh</groupId>
  <artifactId>grpc-server-spring-boot-starter</artifactId>
  <version>2.5.1.RELEASE</version>
  <scope>test</scope>
</dependency>
````

2) Then set these properties on your test class (adjust the client name according to your needs)

````properties
# Enable inProcess server
grpc.server.inProcessName=test
# Disable external server
grpc.server.port=-1
# Configure the client to connect to the inProcess server
grpc.client.inProcess.address=in-process:test
````

3) Then add your fake/test server bean to your `@TestConfiguration`

**Comment by harjis** [comment]
I had a bit trouble understanding what this exactly means. I was able to get somekind of setup to work which can be seen [here](https://github.com/harjis/grpc-service-client-demo/blob/master/src/test/kotlin/com/example/grpcserviceclientdemo/app/grpc_clients/WorkflowWithStarterTest.kt). It might not be _the optimal way_ to do this but at least it's a working one :D

**Comment by ST-DDT** [comment]
I will try to add the relevant parts to the documentation and maybe add them to the examples too.

**Comment by ST-DDT** [comment]
I added a PR that adds client/stub testing documentation. #329

**Comment by Gregory-Berkman-Imprivata** [comment]
Is it still impossible to mock a `blockingStub` ? Mockito2 allows for final classes to be mocked. Is there a more graceful option to mock a `blockingStub`?

**Comment by ST-DDT** [comment]
Yes, you can use Mockito to mock the stub, but according to grpc-java you aren't supposed to because you might change the underlying logic. (It's probably safe for blocking unary calls though, but using a InProcessServer is probably as easy as that)

https://github.com/grpc/grpc-java/blob/f6c2d221e2b6c975c6cf465d68fe11ab12dabe55/stub/src/main/java/io/grpc/stub/AbstractStub.java#L43-L44

**Comment by ST-DDT** [comment]
Have you checked our documentation yet: [client-testing](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/testing.html)
