### ISSUE TITLE
双向流怎么做呢？比如推送消息到客户端

### ISSUE THREAD

**Issue by viphyy** [yidongnan/grpc-spring-boot-starter#289]

**Comment by ST-DDT** [comment]
Sorry for the delay, currently I'm very busy and thus slow at responding.

The following might help you:
https://github.com/grpc/grpc-java/blob/master/services/src/main/java/io/grpc/services/HealthServiceImpl.java#L82-L114

**Comment by ST-DDT** [comment]
Does this help you? If not feel free to ask additional questions here.
