### ISSUE TITLE
Add support for Spring Boot 2.2 and Kotlin Coroutines

### ISSUE THREAD

**Issue by mattdkerr** [yidongnan/grpc-spring-boot-starter#290]
**The problem**

Spring Boot 2.2 is now available generally, and has better support for Kotlin and coroutines. There is also a gRPC solution for building messages as Kotlin lambdas, and for coroutines support, called Kroto+ (https://github.com/marcoferrer/kroto-plus/tree/master/example-project). Integrating these two is not really possible without making changes directly in the grpc-spring-boot-starter code.

**The solution**

I would like to see updating Spring Boot dependency to 2.2, as well as supporting non-builder, lambda style Kotlin idiomatic approach to creating requests and responses, within this library.

**Alternatives considered**

There is another gRPC Kotlin library that is less featured, called grpc-kotlin: https://github.com/rouzwawi/grpc-kotlin. Or it could be implemented more directly, without using an external library.

**Additional context**

Kotlin data classes are extremely simple compared to Java ones, and by default are easier to work with. Because of this, the builder pattern doesn't exist in Kotlin and is a detriment to working in the language efficiently. Additionally, using coroutines to suspend and resume threads during long waiting operations like I/O, causes the gRPC server service APIs to stop working in most conditions.

**Comment by ST-DDT** [comment]
I will bump the dependencies soon.

Is there an incompatibility with the old library and spring-boot 2.2?

What has to be changed for this none-builder based kotlin to work?

As for the corutines and the suspend or long running IO. You probably either need to add @Async to the method or change grpc's internal executor pool (on the builder) to support that otherwise you exhaust it. I haven't tried either yet though.

**Comment by mattdkerr** [comment]
I don’t think there is a Spring Boot upgrade issue, however I haven’t been able to test it. The upgrade to latest of this library causes my custom SSL key file password code to break, and it will take some time to remove the passwords from the files to resolve not having that ability.

Regarding the DSL it uses to hide the builder, it needs another dependency and a new item added to the protoc plugin setup to run after the main grpc-java. I’m not aware of anything else.

**Comment by ST-DDT** [comment]
> The upgrade to latest of this library causes my custom SSL key file password code to break, and it will take some time to remove the passwords from the files to resolve not having that ability.

With the new `Resource` URL feature for the files you could move the decryption to the resource loader. See #262 for examples.

> There is also a gRPC solution for building messages as Kotlin lambdas, and for coroutines support, called Kroto+ (https://github.com/marcoferrer/kroto-plus/tree/master/example-project). Integrating these two is not really possible without making changes directly in the grpc-spring-boot-starter code.

> as well as supporting non-builder, lambda style Kotlin idiomatic approach to creating requests and responses, within this library.

Mind explaining the necessary changes? What is missing for that?

**Comment by ST-DDT** [comment]
Updated to spring-boot v2.2.0 in #291

**Comment by mattdkerr** [comment]
Thanks for the update- when would you be able to make a 2.6.0 release? In the mean-time I've updated to Boot 2.2 with using this library's 2.5.1 release, and I will give Kroto Plus a spin to see if it needs any special support after all.

**Comment by ST-DDT** [comment]
@yidongnan Anything that you would like to include in [v2.6.0](https://github.com/yidongnan/grpc-spring-boot-starter/milestone/4)? From my side everything is ready.

**Comment by yidongnan** [comment]
@ST-DDT I added a Chinese document and it can be completed this weekend.

**Comment by mattdkerr** [comment]
I’d like to have 1.24.2 of gRPC but it could be in a point release (2.6.1)

**Comment by yidongnan** [comment]
2.6.0 just released~

**Comment by marcoferrer** [comment]
I just stumbled on to this issue and wanted to offer any assistance if needed. No sure what strategy is being considered for adding support but I have used the existing kroto plus stubs with another public spring grpc framework. Any feedback or concerns is completely welcomed.

**Comment by ST-DDT** [comment]
> No sure what strategy is being considered for adding support

I'm not sure what is needed to add support...

**Comment by mattdkerr** [comment]
Nothing is needed, as it turns out my issue is within Kroto Plus (and is only on Windows platform). I will move on to their repo for resolution.
