### ISSUE TITLE
Grpc怎么做服务端的限流？

### ISSUE THREAD

**Issue by liujiawinds** [yidongnan/grpc-spring-boot-starter#298]
比如服务端的最大处理能力为10000qps，但有可能在忙时出现15000 qps 的情况，每秒多出的 5000 目前会堆积在内存里面，最终导致 OOM，不知道各位是怎么处理这个问题的？

**Comment by ST-DDT** [comment]
This question should rather be asked in the [grpc-java](https://github.com/grpc/grpc-java/issues) repository. If you link the question to this issue and it gets answered, then I might be able to add a default implementation for it.

I found [this](https://github.com/danielbryantuk/ambassador-java-rate-limiter/blob/master/src/main/java/io/datawire/ambassador/ratelimiter/simpleimpl/RateLimitServer.java) example that demonstrates a rate limited service impl. If you move this rate limiting logic to an interceptor you could protect your entire server without extra code in your grpc service impls.

**Comment by liujiawinds** [comment]
@ST-DDT Thanks for reply. I've tried to apply the bucket4j rate limit in my server-side application as you linked above. But it can't stop the memory explode, even if I set the rate limit threshold to 100qps. My interceptor code: 

`@GRpcGlobalInterceptor
public class RateLimitInterceptor implements ServerInterceptor {
    private static final Logger LOG = LoggerFactory.getLogger(RateLimitInterceptor.class);

    @Value("${rate-limit.threshold}")
    private long threshold;

    @Value("${rate-limit.window-ms}")
    private long windowMs;

    @Value("${rate-limit.check-interval-ms}")
    private long interval;

    private Bucket bucket;

    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
        LOG.info("Now token left: {}.", bucket.getAvailableTokens());
        while(!bucket.tryConsume(1)) {
            LOG.info("Throttling reached, please slow down the client side send rate or adjust the configuration.");
            try {
                TimeUnit.MILLISECONDS.sleep(interval);
            } catch (InterruptedException e) {
                LOG.error("Throttling interrupted.", e);
            }
        }
        return next.startCall(call, headers);
    }

    @PostConstruct
    private void initialBucket() {
        Bandwidth limit = Bandwidth.simple(threshold, Duration.ofMillis(windowMs));
        this.bucket = Bucket4j.builder().addLimit(limit).build();
    }
}
`
The messages didn't throttled and ate all the memory JVM occupied. 
![image](https://user-images.githubusercontent.com/1757754/68836856-45251100-06f6-11ea-84b4-bce5512e8470.png)

**Comment by ST-DDT** [comment]
You either have a [typo](https://www.javadoc.io/doc/net.devh/grpc-server-spring-boot-autoconfigure/latest/net/devh/boot/grpc/server/interceptor/GrpcGlobalServerInterceptor.html) in your example or you are using a different library.

Instead of sleeping you have to close the call.
Im not sure but the [`RESOURCE_EXHAUSTED`](https://grpc.github.io/grpc-java/javadoc/io/grpc/Status.Code.html#RESOURCE_EXHAUSTED) might be the correct response code.

**Comment by ST-DDT** [comment]
IMO this should be solved in the upstream issue.
