### ISSUE TITLE
Problem following the guide

### ISSUE THREAD

**Issue by AnakinPt** [yidongnan/grpc-spring-boot-starter#299]
I followed your guide to create a small server and when I try to execute the gRPC test call, I get this:
PS C:\workspaces\grpc-server> grpcurl --plaintext -d '{"name": "test"}' localhost:9090 Simple.SayHello
Error invoking method "Simple.SayHello": error getting request data: invalid character 'n' looking for beginning of object key string

I'm using the same versions you are using, and I copied the code from the examples/cloud-server.

Can you help me with this, please?

Thanks

**Comment by AnakinPt** [comment]
Just found the answer in here: https://yidongnan.github.io/grpc-spring-boot-starter/en/trouble-shooting#transport-failed
My configuration was wrongly set.

**Comment by Dergash** [comment]
Encountered the exact same error and I don't believe there is anything related in the troubleshooting section.
It appears `grpcurl` tool used in documentation for requests to the server requires escaping when launched from windows cmd:
```sh
# Documentation (single quote, non-escaped double quotes, whitespace)
grpcurl --plaintext -d '{"name": "test"}' localhost:9090 net.devh.boot.grpc.example.MyService/sayHello
# Parse error
Error invoking method "net.devh.boot.grpc.example.MyService/sayHello": error getting request data: invalid character '\'' looking for beginning of value
```
```sh
# Windows cmd
grpcurl --plaintext -d "{\"name\":\"test\"}" localhost:9090 net.devh.boot.grpc.example.MyService/sayHello
# No error
{
  "message": "Hello ==> test"
}
```
See possibly related https://github.com/fullstorydev/grpcurl/issues/106
