### ISSUE TITLE
net.devh.boot.grpc.client.nameresolver.DiscoveryClientNameResolver No servers found for cloudtrace.googleapis.com

### ISSUE THREAD

**Issue by quan-nh** [yidongnan/grpc-spring-boot-starter#304]
**The context**

I have an app with these dependencies.
```
    implementation 'net.devh:grpc-client-spring-boot-starter:2.6.0.RELEASE'
    implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'
    implementation 'io.zipkin.brave:brave-instrumentation-grpc:5.9.1'
    implementation 'org.springframework.cloud:spring-cloud-gcp-starter-logging'
    implementation 'org.springframework.cloud:spring-cloud-gcp-starter-trace'
```
The app run on GCP & I want to use gcp trace, follow this guide https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-trace/index.html.

**The question**

net.devh.boot.grpc.client.nameresolver.DiscoveryClientNameResolver class show this error(?)
`No servers found for cloudtrace.googleapis.com` & no trace is recorded in Stackdriver Trace. The Stackdriver Trace API is already enabled, so I thing maybe there is a conflict with `spring-cloud-gcp-starter-trace` library (as cloudtrace should be handled by that lib, not grpc client)?

**Stacktraces and logs**

**The application's environment**

Which versions do you use?
* Spring (boot): 2.2.1.RELEASE
* grpc-java: 1.25.0
* grpc-spring-boot-starter:2.6.0.RELEASE
* java: 11 (64bit)

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment]
AFAICT the most likely cause of this issue is that `cloudtrace.googleapis.com` fails to specify a schema and thus on how to resolve that target/name.
Grpcs dns resolver has a prio of 5 , which is the default in plain grpc. But if a discovery client (prio 6) is present in springs application context, then grpc will use that one instead.

See also
https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration#choosing-the-target
And
https://github.com/yidongnan/grpc-spring-boot-starter/issues/300

**Comment by quan-nh** [comment]
I think this is what `spring-cloud-gcp-starter-trace` do related to this issue https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java

Do you have any suggestion on fixing this issue?

**Comment by ST-DDT** [comment]
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L143

````diff
- return ManagedChannelBuilder.forTarget("cloudtrace.googleapis.com")
+ return ManagedChannelBuilder.forTarget("dns:///cloudtrace.googleapis.com")
````

**Comment by ST-DDT** [comment]
I created a [PR at grpc-java](https://github.com/grpc/grpc-java/pull/6499) that details the usage expectations of the `MangagedChannelBuilder#forTarget(String)` method. Once that is merged I will create PRs for the libraries that fail to specify the `dns` scheme themselves.

**Comment by ST-DDT** [comment]
I created a PR over at GCP that will fix this issue:
https://github.com/spring-cloud/spring-cloud-gcp/pull/2085
