### ISSUE TITLE
有没有使用nacos作服务注册中心的demo

### ISSUE THREAD

**Issue by wangyingwei001** [yidongnan/grpc-spring-boot-starter#307]
有没有使用nacos作服务注册中心的demo

**Comment by ST-DDT** [comment]
Unfortunately not, but it behaves mostly like nacos with http clients.

**Comment by kekenaer** [comment]
介绍上说支付nacos，有没有集成的例子，同求

**Comment by ST-DDT** [comment]
Unfortunately not. I am not familiar with nacos, but AFAICT all you have to do is replacing the eureka lib from the cloud demo with the nacos lib.
Unfortunately, I don't time to explore that library discovery service myself, but I appreciate any help with adding such a demo.

**Comment by kekenaer** [comment]
> Unfortunately not. I am not familiar with nacos, but AFAICT all you have to do is replacing the eureka lib from the cloud demo with the nacos lib.
> Unfortunately, I don't have time to explore that library/discovery service for now, but I appreciate any help with adding such a demo.

感谢您的邮件回复，我这边已经解决！整合非常简单！感谢你们的starter！我发表了整合方法：有兴趣的同学可以看下：
https://blog.csdn.net/qq_35875671/article/details/106012835

**Comment by suveng** [comment]
@ST-DDT  i can do that or i am doing that, writing another demo , base on the blog in the comment

**Comment by xieyucan** [comment]
整合nacos的example，已经提了PR等待作者合并。
https://github.com/xieyucan/grpc-spring-boot-starter/tree/dev/examples/cloud-grpc-server-nacos
https://github.com/xieyucan/grpc-spring-boot-starter/tree/dev/examples/cloud-grpc-client-nacos
