### ISSUE TITLE
客户端报错 

### ISSUE THREAD

**Issue by wangyingwei001** [yidongnan/grpc-spring-boot-starter#308]
io.grpc.StatusRuntimeException: UNAVAILABLE: Name resolver net.devh.springboot.autoconfigure.grpc.client.DiscoveryClientNameResolver@7c04566b returned an empty list

**Comment by ST-DDT** [comment]
The description of the error is a little bit short. Is it possible that the error is related to:

https://yidongnan.github.io/grpc-spring-boot-starter/en/trouble-shooting#client-fails-to-resolve-domain-name

**Comment by ST-DDT** [comment]
Closing due to missing feedback.
