### ISSUE TITLE
DiscoveryClientNameResolver leak and performance issue.

### ISSUE THREAD

**Issue by wangzw** [yidongnan/grpc-spring-boot-starter#311]
An object leak case has detected recently in out system. grpc-spring-boot-starter version is 2.4.0 and I believe it also exists on master branch. Grpc version is 1.20.0.

Eclipse Memory Analyzer give the following report.

<img width="1092" alt="屏幕快照 2019-12-13 14 40 08" src="https://user-images.githubusercontent.com/1254826/70775929-b835ac00-1db6-11ea-9476-c8e83d9cdeb7.png">
<img width="1049" alt="屏幕快照 2019-12-13 14 40 22" src="https://user-images.githubusercontent.com/1254826/70775936-bcfa6000-1db6-11ea-84d2-a66855f29d11.png">

In method `DiscoveryClientResolverFactory::newNameResolver`,  a `DiscoveryClientNameResolver` is created and add into a list and never removed and cause the leak. 

And things get worse because `DiscoveryClientNameResolver` hold a reference of `Listener` which is a member of `ManagedChannelImpl`, cause `ManagedChannelImpl` leak even if it is shutdown.

A quick fix it that we set listener of `DiscoveryClientNameResolver` to null in method of shutdown and remove `DiscoveryClientNameResolver` from `DiscoveryClientResolverFactory`.

But there is also a performance issue related to `DiscoveryClientNameResolver` when there are many `DiscoveryClientNameResolver`. Each resolver send a request to Eureka to update instance list every 10 seconds even if they are about to resolve the same service. From the above resolver leak case, our Eureka was almost out of service under high workload.

**Comment by ST-DDT** [comment]
Confirmed, i will push a PR with a fix soon.

**Comment by ST-DDT** [comment]
#312 (quick fix) ready for review

**Comment by josephxxz** [comment]
内存泄漏确实存在，但是性能问题似乎是和`DiscoveryClientResolver`无关的。
gRPC的channel每次建立连接（Idle时会断开连接）都会创建新的`NameResolver`，`DiscoveryClientResolverFactory`从来不释放它创建过的`DiscoveryClientResolverFactory`，造成内存泄漏，这个问题只要在创建`NameResolver`时传给它一个shutdown时调用的Runnable，Runnable清理它在Factory中的记录，就解决了。把代码跟Factory混在一块不合适。
心跳是 `DiscoveryClient`负责的， `DiscoveryClient`在整个应用中只有一个，心跳频率是配置决定的，和有多少`NameResolver`也没关系，从 `DiscoveryClient`查询服务列表也是在内存里面查的，这一整块代码的修改看起来改太过了。

**Comment by ST-DDT** [comment]
Fixed via #320 

@yidongnan Could you release v2.6.2 ?

**Comment by yidongnan** [comment]
@ST-DDT v2.6.2 has been released
