### ISSUE TITLE
整合mq有demo吗

### ISSUE THREAD

**Issue by Zxxjgp** [yidongnan/grpc-spring-boot-starter#315]
有没有整合在grpc里面整合消息队列

**Comment by ST-DDT** [comment]
For questions not directly related to grpc-spring-boot-starter/gRPC-Java, please use [stackoverflow](https://stackoverflow.com/questions/tagged/grpc-java).
Also, if question is not grpc-spring-boot-starter/gRPC-Java implementation specific, consider using [grpc.io](https://groups.google.com/forum/#!forum/grpc-io)

You can use grpc as a message queue, but it does not support any kind of persistence or delayed delivery. For more information refer to client/server/bidi-streaming: https://grpc.io/docs/guides/concepts/

**Comment by Zxxjgp** [comment]
写写

**Comment by ST-DDT** [comment]
@yidongnan

**Comment by Zxxjgp** [comment]
打错字应该是谢谢
