### ISSUE TITLE
如何在server端的方法中获取请求的ip

### ISSUE THREAD

**Issue by nullornot** [yidongnan/grpc-spring-boot-starter#321]
试过用interceptor把ip放到context，在方法中获取不到。

**Comment by ST-DDT** [comment]
Does your interceptor look roughly like this:

````java
@GrpcGlobalServerInterceptor
public class MetadataProvidingGrpcServerInterceptor implements ServerInterceptor {

    public static final Context.Key<SocketAddress> CLIENT_ADDRESS = Context.key("client-address");

    @Override
    public <ReqT, RespT> Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
        SocketAddress clientAddress = call.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR);
        return Contexts.interceptCall(Context.current().withValue(CLIENT_ADDRESS, clientAddress), call, headers, next);
    }

}
````

Then you should be able to access the clientAddress like this:

````java
MetadataProvidingGrpcServerInterceptor.CLIENT_ADDRESS.get();
````

**Comment by nullornot** [comment]
The problem was solved  one minute before i received the email hh.
I found the key must be modify by static final.
Thanks for your reply!






| |
张康杰
|
|
nullornot@163.com
|
签名由网易邮箱大师定制
在2020年1月13日 17:20，ST-DDT<notifications@github.com> 写道：

Does your interceptor look roughly like this:

@GrpcGlobalServerInterceptorpublicclassMetadataProvidingGrpcServerInterceptorimplementsServerInterceptor {

    publicstaticfinalContext.Key<SocketAddress>CLIENT_ADDRESS= Context.key("client-address");

    @Overridepublic<ReqT, RespT>Listener<ReqT>interceptCall(ServerCall<ReqT, RespT>call, Metadataheaders, ServerCallHandler<ReqT, RespT>next) {
        SocketAddress clientAddress = call.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR);
        returnContexts.interceptCall(Context.current().withValue(CLIENT_ADDRESS, clientAddress), call, headers, next);
    }

}

Then you should be able to access the clientAddress like this:

MetadataProvidingGrpcServerInterceptor.CLIENT_ADDRESS.get();
