### ISSUE TITLE
如何配合etcd实现分布式

### ISSUE THREAD

**Issue by chenyu9390** [yidongnan/grpc-spring-boot-starter#323]
基于etcd实现负载均衡和服务发现,能提供给demo吗

**Comment by ST-DDT** [comment]
Have you tried https://github.com/spring-cloud-incubator/spring-cloud-etcd yet?
That libs looks a bit dated though.

**Comment by ST-DDT** [comment]
We won't implement a library/Example ourselves that uses etcd for service discovery as that would be outside of the scope of this project.

You could try to request this feature from either grpc-java or spring-boot directly.
