### ISSUE TITLE
Security is enabled but this implementation does not support Security!

### ISSUE THREAD

**Issue by Jarvis8099** [yidongnan/grpc-spring-boot-starter#324]
**Server enabled Security, configure SSL why prompt ”Security is enabled but this implementation does not support Security!“ ？**

**Comment by ST-DDT** [comment]
Which version of grpc-spring-boot-starter are you using?
Please fill in the missing information from the issue template.
[question](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/.github/ISSUE_TEMPLATE/question.md) / [bug_report](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

[AbstractGrpcServerFactory](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java#L140) throws this exception, but that method is usually overwritten by subclasses.

Also I'm not sure what/why you are asking.
Is the exception message not understandable?

**Comment by ST-DDT** [comment]
Closing due to missing feedback.
