### ISSUE TITLE
Support configuring certificates from a String instead of a Resource

### ISSUE THREAD

**Issue by internetstaff** [yidongnan/grpc-spring-boot-starter#325]
**The problem**

I'm working on a solution that's deployed as containers to different environments in AWS ECS. We have different internal CAs for each environment, so the CA cert, key, and service cert all need to be different per environment. 

We'd also generally prefer not to embed and expose private keys in the container, nor to require rebuilding containers to rotate them.

We do use AWS Parameter Store via Spring Cloud to encrypt and inject secrets.

I don't see a Spring Resource type we could use to easily retrieve the certs/keys. However, if we could specify these as strings, it'd be trivial.  I'm not sure how you'd want to do this cleanly - separate parameters, or checking a Resource for an InputStream and falling back to seeing if it's a string certificate.

It's entirely possible there's already a trivial solution to this that I'm overlooking. :)

**The solution**

Allow configuring e.g. trust-cert-collection, private-key, and certificate-chain as strings in addition to Resources.

**Alternatives considered**

I'm currently accomplishing this via a GrpcChannelConfigurer. This works, but requires duplicating code from NettyChannelFactory.configureSecurity() to provide an SslContext.

Thanks!

**Comment by ST-DDT** [comment]
Does https://github.com/yidongnan/grpc-spring-boot-starter/pull/262 -> `Example usage` help you?

**Comment by ST-DDT** [comment]
I'm not sure but maybe your spring-cloud-aws implementation contains already contains a `ProtocolResolver` for this:
https://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.2.0.M2/reference/html/#_resource_handling
https://cloud.spring.io/spring-cloud-static/spring-cloud-aws/2.1.0.RELEASE/single/spring-cloud-aws.html#_resource_handling

Not sure which library you are using exactly. If it doesn't have an implementation already, you should ask them whether they could add one.

**Comment by internetstaff** [comment]
Thanks for the quick response!

Using a ProtocolResolver could work, writing a custom resolver still seems a bit cumbersome for something that could be so simple.  I actually fiddled with that first and was unable to make it work. I think I'm unclear as to how you'd ensure it was registered prior to the config being applied to GrpcChannelProperties.

I'm not aware of Spring Cloud having a ProtocolResolver for Parameter Store, only for S3. :(

**Comment by ST-DDT** [comment]
> Using a ProtocolResolver could work, but writing a custom resolver still seems a bit cumbersome for something that could be so simple.

Thats true, but that doesn't seem to be a major usecase, otherwise spring would have integrated it long ago.

> I actually fiddled with that first and was unable to make it work.

I'll have a look at it. Which input format would you like to use?

> I think I'm unclear as to how you'd ensure it was registered prior to the config being applied to GrpcChannelProperties.

If you define the bean `static` it should be earlier than the rest. As an alternative your could try to move it to its own (spring-boot auto-) configuration and annotate it with `@AutoConfigureBefore(GrpcClientAutoConfiguration(?))` to force it to be loaded very early.

>I'm not aware of Spring Cloud having a ProtocolResolver for Parameter Store, only for S3. :(

Try asking them whether they could add one, maybe they have another useful idea.

**Comment by internetstaff** [comment]
> Thats true, but that doesn't seem to be a major usecase, otherwise spring would have integrated it long ago.

Perhaps. I suspect most people just inject a keystore and be done with it, since it the way it's done historically. Maybe we could encourage better key management? :)

Marking the ProtocolResolver static didn't help. :(

> I'll have a look at it. Which input format would you like to use?

I'm using the exact same PEM/PKCS8 formats, only I'm using them either inline in an application.yaml (for testing) or letting Spring Cloud pull from Parameter Store.  It literally boils down to the difference between resource.GetInputStream() and (in my case) IOUtils.toInputStream(string, UTF8). So close ...

Ex:

```
         try (InputStream trustCertCollectionStream = IOUtils.toInputStream(trustCertCollection, StandardCharsets.UTF_8.name())) {

            sslContextBuilder.trustManager(trustCertCollectionStream);

          } catch (IOException | RuntimeException e) {
            throw new IllegalArgumentException("Failed to create SSLContext (TrustStore)", e);
          }
```


> Try asking them whether they could add one, maybe they have another useful idea.

A good idea, in general!  Unfortunately Spring Cloud AWS seems practically dead these days. :(

**Comment by ST-DDT** [comment]
Thanks for the input. I will try to use that as the base.

> > Try asking them whether they could add one, maybe they have another useful idea.
> 
> A good idea, in general! Unfortunately Spring Cloud AWS seems practically dead these days. :(

In https://stackoverflow.com/questions/54050702/why-integrating-spring-cloud-application-with-the-aws-parameter-store-return-no

There is a screenshot containing something like `aws-param-store:/` could you debug into your application and check which `ProtocolResolver`s are available inside the `ResourceLoader`?

Do you have `spring-cloud-config` somewhere in your dependencies? Maybe that is another place to put/ask for the `ProtocolResolver`.

**Comment by ST-DDT** [comment]
I modified my `AnnotatedSecurityWithCertificateTest` and it did use the custom `ProtocolResolver`:

````java
package net.devh.boot.grpc.test.security;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ResourceLoaderAware;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.DefaultResourceLoader;
import org.springframework.core.io.ProtocolResolver;
import org.springframework.core.io.Resource;
import org.springframework.core.io.ResourceLoader;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;

import lombok.extern.slf4j.Slf4j;
import net.devh.boot.grpc.test.config.AnnotatedSecurityConfiguration;
import net.devh.boot.grpc.test.config.BaseAutoConfiguration;
import net.devh.boot.grpc.test.config.ServiceConfiguration;
import net.devh.boot.grpc.test.config.WithCertificateSecurityConfiguration;

@Slf4j
@SpringBootTest(properties = {
        "grpc.server.security.enabled=true",
        "grpc.server.security.certificateChain=data:file:src/test/resources/certificates/server.crt",
        "grpc.server.security.privateKey=data:file:src/test/resources/certificates/server.key",
        "grpc.server.security.trustCertCollection=data:file:src/test/resources/certificates/trusted-clients-collection",
        "grpc.server.security.clientAuth=REQUIRE",

        "grpc.client.GLOBAL.address=localhost:9090",
        "grpc.client.GLOBAL.security.authorityOverride=localhost",
        "grpc.client.GLOBAL.security.trustCertCollection=file:src/test/resources/certificates/trusted-servers-collection",
        "grpc.client.GLOBAL.security.clientAuthEnabled=true",

        "grpc.client.test.security.certificateChain=file:src/test/resources/certificates/client1.crt",
        "grpc.client.test.security.privateKey=file:src/test/resources/certificates/client1.key",

        "grpc.client.noPerm.security.certificateChain=file:src/test/resources/certificates/client2.crt",
        "grpc.client.noPerm.security.privateKey=file:src/test/resources/certificates/client2.key"
})
@SpringJUnitConfig(
        classes = {AnnotatedSecurityWithCertificateTest.Config.class, ServiceConfiguration.class,
                BaseAutoConfiguration.class, AnnotatedSecurityConfiguration.class,
                WithCertificateSecurityConfiguration.class})
@DirtiesContext
public class AnnotatedSecurityWithCertificateTest extends AbstractSecurityTest {

    public AnnotatedSecurityWithCertificateTest() {
        log.info("--- AnnotatedSecurityWithCertificateTest ---");
    }

    @Configuration
    public static class Config {

        @Bean
        public DataProtocolResolver customProtocol() {
            return new DataProtocolResolver();
        }

    }

    @Slf4j
    public static class DataProtocolResolver implements ProtocolResolver, ResourceLoaderAware {

        @Override
        public void setResourceLoader(final ResourceLoader resourceLoader) {
            if (resourceLoader instanceof DefaultResourceLoader) {
                ((DefaultResourceLoader) resourceLoader).addProtocolResolver(this);
            } else {
                log.warn("Unable to register the 'data:' resource protocol to this kind of ResourceLoader: "
                        + "{} (not a DefaultResourceLoader)", resourceLoader);
            }
        }

        @Override
        public Resource resolve(final String location, final ResourceLoader resourceLoader) {
            if (location == null || !location.startsWith("data:")) {
                return null;
            }
//            return null; // Use this to make the test fail
            return resourceLoader.getResource(location.substring(5));
        }

    }

}
````

-------------------------------------

I also tried it in a separate project and it still worked as expected:

````java
@SpringBootConfiguration
@AutoConfigureBefore(GrpcServerAutoConfiguration.class)
public class ResourceConfiguration {

    @Bean
    static DataProtocolResolver dataProtocolResolver() {
        return new DataProtocolResolver();
    }

}
````

Did you forget to add the spring-boot annotation-processor?

````groovy
dependencies {
    annotationProcessor("org.springframework.boot:spring-boot-autoconfigure-processor")
````

**Comment by internetstaff** [comment]
Thanks for your efforts.

I tried both auto-configuration w/ the processor and manually importing the config. I even tried using your above code directly instead of my own. :)

I never got a "data:" value to map to anything but a ClassPathContextResource. It looks like GrpcChannelProperties is always initialized well before Spring creates the DataProtocolResolver despite several different gymnastic attempts. :)

The main two differences I see are 1) I'm using the parameter store bootstrap and 2) I've actually only tried modifying the Channel side so far. (I did try @AutoConfigureBefore(GrpcClientAutoConfiguration.class)

At some point, this potential cure is worse than the disease.  It'd be great if we could set these directly as String parameters, but otherwise as non-optimal as they are, custom Configurers seem more obvious and a lower bar than a config-time custom Protocol Resolver, which seems sparsely documented by Spring.

**Comment by ST-DDT** [comment]
I have one last suggestion for you to try:

Use an [`ImportBeanDefinitionRegistrar`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/ImportBeanDefinitionRegistrar.html)
An example implementation can be found on: `@EnableConfigurationProperties`.
I assume the spring-cloud storage lib uses something similar to register their beans early.

Or maybe you can something like `@AutoConfigureBefore(SpringCloudAutoConf...)` or `@AutoConfigureOrder(either lowest or highest)`.

For more hints I have to redirect you to the spring-(boot-(cloud))-developers or Stackoverflow.

---------------

At least for now, I won't add a string parameter for those `Resource` parameters.

**Comment by ST-DDT** [comment]
I created an upstream issue, maybe they can solve this issue or at least document how to register it "early" enough. https://github.com/spring-projects/spring-framework/issues/24760
