### ISSUE TITLE
how to config a loadBalancer for client ?

### ISSUE THREAD

**Issue by yunbanlongwu** [yidongnan/grpc-spring-boot-starter#326]
how to config a loadBalancer for client ?

**Comment by ST-DDT** [comment]
AFAICT This library does not provide any config options regarding load balancing.

But you can use a GrpcChannelConfigurer or a similar interface to configure various parts of your application.

So maybe the answer to your question would be: The same way you do it in grpc-java.

What do you wish to achieve? Maybe we could add an option for it.

Could you write a code snippet that demonstrates your required behavior using grpc-java? Then I could modify it for the usage with spring.

**Comment by yunbanlongwu** [comment]
Thanks for your reply, I'm newly for grpc, i find the way use GrpcChannelConfigurer to config, and i also found the default LoadBalancingPolicy has bean reset to "round_robin" in net.devh.boot.grpc.client.config.GrpcChannelProperties.getDefaultLoadBalancingPolicy(), so it's not necessary for me to change it.
but i feel the balancer provided by grpc is not such powerful, such as not support weight...

**Comment by upcwangying** [comment]
@yunbanlongwu  see `io.grpc.LoadBalancer`
