### ISSUE TITLE
Support gRPC Java version 1.26.0+

### ISSUE THREAD

**Issue by mattdkerr** [yidongnan/grpc-spring-boot-starter#327]
**The problem**

If you upgrade to gRPC Java 1.26.0 the GrpcClient annotated stub is no longer able to construct itself. It throws a NoSuchMethod exception for the constructor.

**The solution**

Revert back to 1.25.x

**Alternatives considered**

An alternative methodology of constructing this class by reflection is needed.

**Additional context**

upgraded this library’s dependencies in branch patch-1 to use 1.27.1 of grpc-java, but now i'm getting a ton of errors with this sort of exception: java.lang.NoSuchMethodException: net.devh.boot.grpc.test.proto.TestServiceGrpc$TestServiceStub.<init>(io.grpc.Channel)

**Comment by ST-DDT** [comment]
Thanks for reporting this issue. I haven't noticed this issue, probably because my interface specs/libs are generated using an older version of grpc. I will have a look at this and fix it ASAP.

**Comment by ST-DDT** [comment]
I created a PR that fixes this issue. Expect a new release soon.

**Comment by mattdkerr** [comment]
Fantastic. I gave it a try myself but couldn’t figure it out. It looked like the accessibility changed on the classes, but not in a way that should have broken it.

**Comment by ST-DDT** [comment]
Grpc-Java (the grpc-protoc-plugin) doesn't generate the constructor anymore that we previously accessed. At first, I considered using the other constructor, but the `private`/internal classifier made me change my mind. I hope the static methods won't change anytime soon.^^

````diff
    public static final class SimpleStub extends io.grpc.stub.AbstractAsyncStub<SimpleStub> {

-     private SimpleStub(io.grpc.Channel channel) {
-       super(channel);
-     }

      private SimpleStub(io.grpc.Channel channel, io.grpc.CallOptions callOptions) {
        super(channel, callOptions);
      }

      [...]

    }
````

**Comment by mattdkerr** [comment]
Do you think a PR against grpc-Java is a better alternative? Could this be an accidental bug on their side? I wonder if they are aware of folks using the library’s generated code in this way.

Another thought- if a PR over there could be made to avoid needing reflection altogether, what would that look like (feature wise)? It seems to me that touching class internals is bound to be a recurring problem long term.

**Comment by ST-DDT** [comment]
> Another thought- if a PR over there could be made to avoid needing reflection altogether, what would that look like (feature wise)? It seems to me that touching class internals is bound to be a recurring problem long term.

I thought about that this morning.
Maybe something like `<T extends AbstractStub<T>> createStub(Class<T> stubType, Channel channel)` hopefully in a class of the library and not inside the generated code...
But I didn't have time to thing about it in depth. Do you have a recommendation? Or should we start by opening an issue over at grpc-java?

**Comment by mattdkerr** [comment]
I think that’s a good idea (creating an issue there)- the folks there would probably have their own thoughts as to what would work well for them and accomplish the goal. Just laying out the problem with the solution we have here and how it could just happen again could get them to think about their changes a bit differently going forward.

**Comment by mattdkerr** [comment]
For now though, proceeding with your PR’s approach is fine. I do need this change to unblock some time sensitive work.

**Comment by ST-DDT** [comment]
Done: https://github.com/grpc/grpc-java/issues/6744
