### ISSUE TITLE
Specifying interceptors per channel

### ISSUE THREAD

**Issue by jgarcia-sqsp** [yidongnan/grpc-spring-boot-starter#336]
**The context**

Trying to apply specific interceptors for clients of different services. Have a client for service A and a client for service B. I'd like to use an interceptor to attach a custom header for both clients, but each header should be different for each client.

**The question**

How can I do this while using the GrpcClient annotation to create my clients? I see the way to add interceptors is to use the GrpcGlobalClientInterceptor annotation on an interceptor, but this will add it to all created channels.

Is there a way to specify which interceptors to apply to a channel?

**Stacktraces and logs**

N/A

**The application's environment**

Which versions do you use?
* Spring (boot): 2.1.11.RELEASE
* grpc-java: 1.27.1
* grpc-spring-boot-starter: 2.7.0.RELEASE
* java: jdk 11 64-bit

**Additional information**

N/A

**Comment by ST-DDT** [comment]
There are basically two ways to do this:

1) The first one is probably the easiest one:

You simply define a `ClientInterceptor` bean without the global annotation and then reference it in the [`@GrpcClient#interceptors`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClient.java#L100) field.

2) The second one is requires slightly more configuration:

You create a [`StubTransformer`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/StubTransformer.java#L38) bean and use it to add the interceptor to the stub.

If you need the interceptor for adding (something like) credentials then you could use [this as an example](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java#L150-L157).

**TODO for me:** Add cross references to the docs:
- [client/getting-started#components/ClientInterceptor](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/getting-started#explaining-the-client-components) -> [client/configuration##new section](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration)
- [client/getting-started#components/StubTransformer](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/getting-started#explaining-the-client-components) -> [client/configuration#stubtransformer](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration#stubtransformer)

**Comment by jgarcia-sqsp** [comment]
Great! Thanks for the examples.
