### ISSUE TITLE
Simplify usage of GlobalClientInterceptorConfigurers

### ISSUE THREAD

**Issue by bgulowaty** [yidongnan/grpc-spring-boot-starter#338]
**The context**

I want to provide custom `GlobalClientInterceptor` (instead of using `@GrpcGlobalClientInterceptor` annotation) by implementing my own `GlobalClientInterceptorConfigurer`.

**The bug**

`GlobalClientInterceptorRegistry.init` method is annotated with Spring's `@PostConstruct` which makes it invoke just after `GlobalClientInterceptorRegistry` bean creation. 

App specific beans are created later, therefore my custom `GlobalClientInterceptorConfigurer` is not picked up at the registry creation time. 

```
public class GlobalClientInterceptorRegistry implements ApplicationContextAware {
(...)
    @PostConstruct
    public void init() {
        final Map<String, GlobalClientInterceptorConfigurer> map =
                this.applicationContext.getBeansOfType(GlobalClientInterceptorConfigurer.class);
        for (final GlobalClientInterceptorConfigurer globalClientInterceptorConfigurer : map.values()) {
            globalClientInterceptorConfigurer.addClientInterceptors(this);
        }
    }
(...)
}
```

**Stacktrace and logs**

```
2020-03-10 12:54:29.859 DEBUG [webapp,,,] 20021 --- [           main] otationGlobalClientInterceptorConfigurer : Registering GlobalClientInterceptor: metricCollectingClientInterceptor (net.devh.boot.grpc.client.metric.MetricCollectingClientInterceptor@c4ca86a)
(...)
2020-03-10 12:54:37.485 DEBUG [webapp,,,] 20021 --- [           main] c.s.sens.webapp.grpc.GrpcConfiguration   : Creating my custom interceptor configurer
```
**Steps to Reproduce**

1. Register your own interceptor through `GlobalClientInterceptorConfigurer`
2. Run the app and see its not registered

Part of configuration:
```
  @Bean
  GlobalClientInterceptorConfigurer myCustomConfigurer() {
    log.debug("Creating my custom interceptor configurer");
    return registry -> {
      log.debug("Registering my custom interceptor");
      registry.addClientInterceptors(new TimeoutInterceptor(() -> Duration.ofSeconds(10)));
    };
  }


  @RequiredArgsConstructor
  private static class TimeoutInterceptor implements ClientInterceptor {

    private final GrpcTimeoutConfig config;

    @Override
    public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(
        MethodDescriptor<ReqT, RespT> method, CallOptions callOptions, Channel next) {
      return next.newCall(method, callOptions.withDeadline(config.getDeadline()));
    }
  }
```

**The application's environment**

Which versions do you use?
* Spring (boot): 2.2.4.RELEASE
* grpc-java: 1.27.1
* grpc-spring-boot-starter: 2.6.2.RELEASE
* java: version + architecture (64bit?): OpenJDK Runtime Environment Zulu11.35+13-CA (build 11.0.5+10-LTS) (64 bit)

**Comment by ST-DDT** [comment]
Thanks for your detailed bugreport.
Unfortunately I have very little free time at the moment, so I will have a look at it in detail next week at the earliest

**Comment by ST-DDT** [comment]
One way to address this is moving that bean to a separate spring-boot auto `@Configuration` that is annotated with `@AutoConfigureBefore(GrpcClientAutoConfiguration.class)`. But I haven't tested that.

**Comment by ST-DDT** [comment]
I found this code in the examples, which works as expected:

https://github.com/yidongnan/grpc-spring-boot-starter/blob/93d2efb0ecb515c2bc7a27e19144ba2e52a475dc/examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/GlobalClientInterceptorConfiguration.java#L27-L36

I will try to simplify the process/config a bit (I'm not sure how, though).

**Comment by ST-DDT** [comment]
I move this enhancement to the release after the spring-boot 2.3.0 update
