### ISSUE TITLE
在服务器侧如何手动对client端的连接进行管理，例如对客户端链接进行检测、记录、断开等操作？

### ISSUE THREAD

**Issue by Bernard10060** [yidongnan/grpc-spring-boot-starter#339]
如题。

**Comment by ST-DDT** [comment]
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://github.com/yidongnan/grpc-spring-boot-starter/issues/339

The easiest solution is probably using a `ServerInterceptor`. The ServerInterceptor has access to the call itself. I'm not sure what you wish to achieve in detail, but the following examples might help you.

* The [`ExceptionTranslatingServerInterceptor`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/ExceptionTranslatingServerInterceptor.java#L59-L68) that is part of the security/authentication mechansim.
* The [`MetricCollectingServerInterceptor`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerInterceptor.java#L137) gathers statistics related to the grpc calls.

Does this help you?

**Comment by ST-DDT** [comment]
If you have additional questions feel free to ask them below or in a new issue.
