### ISSUE TITLE
为什么报错呢？

### ISSUE THREAD

**Issue by rjzou** [yidongnan/grpc-spring-boot-starter#34]
:examples:grpc-lib:extractIncludeProto[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.1.3.RELEASE.pom:852:1: 尾随节中不允许有内容。

**Comment by rjzou** [comment]
还有我的项目[https://www.google.com.hk/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png](url)

**Comment by yidongnan** [comment]
@rjzou 能否提供详细的错误信息？或者构建一个demo来演示这个错误？

**Comment by rjzou** [comment]
你再看下这个 https://pan.baidu.com/s/1gfFYKoj

**Comment by rjzou** [comment]
[sts] -----------------------------------------------------
[sts] Starting Gradle build for the following tasks: 
[sts]      build
[sts] -----------------------------------------------------
Parallel execution with configuration on demand is an incubating feature.
:examples:compileJava UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:processResources
:examples:processResources UP-TO-DATE
:examples:classes UP-TO-DATE
:examples:jar
:grpc-client-spring-boot-autoconfigure:processResources UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:compileJava
:grpc-server-spring-boot-autoconfigure:processResources UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:compileJava
:grpc-client-spring-boot-starter:processResources UP-TO-DATE
:grpc-client-spring-boot-starter:sourceJar
:examples:jar UP-TO-DATE
:examples:assemble UP-TO-DATE
:examples:compileTestJava UP-TO-DATE
:examples:processTestResources UP-TO-DATE
:examples:testClasses UP-TO-DATE
:examples:test UP-TO-DATE
:examples:check UP-TO-DATE
:examples:build UP-TO-DATE
:grpc-server-spring-boot-starter:processResources UP-TO-DATE
:grpc-server-spring-boot-starter:sourceJar UP-TO-DATE
:grpc-server-spring-boot-starter:processTestResources UP-TO-DATE
:examples:cloud-eureka-server:compileJava
:grpc-client-spring-boot-starter:sourceJar UP-TO-DATE
:grpc-client-spring-boot-starter:processTestResources UP-TO-DATE
:examples:grpc-lib:extractIncludeProto[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.1.3.RELEASE.pom:852:1: 尾随节中不允许有内容。
 UP-TO-DATE
:examples:grpc-lib:extractProto UP-TO-DATE
:examples:grpc-lib:generateProto UP-TO-DATE
:examples:grpc-lib:compileJava[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
 UP-TO-DATE
:examples:grpc-lib:processResources UP-TO-DATE
:examples:grpc-lib:classes UP-TO-DATE
:examples:grpc-lib:jar[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
 UP-TO-DATE
:examples:cloud-grpc-client:processResources UP-TO-DATE
:examples:cloud-grpc-client:processTestResources UP-TO-DATE
:examples:cloud-grpc-server:processResources UP-TO-DATE
:examples:cloud-grpc-server:processTestResources UP-TO-DATE
:examples:grpc-lib:assemble UP-TO-DATE
:examples:grpc-lib:extractIncludeTestProto[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.1.3.RELEASE.pom:852:1: 尾随节中不允许有内容。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
 UP-TO-DATE
:examples:grpc-lib:extractTestProto UP-TO-DATE
:examples:grpc-lib:generateTestProto UP-TO-DATE
:examples:grpc-lib:compileTestJava UP-TO-DATE
:examples:grpc-lib:processTestResources UP-TO-DATE
:examples:grpc-lib:testClasses UP-TO-DATE
:examples:grpc-lib:test UP-TO-DATE
:examples:grpc-lib:check UP-TO-DATE
:examples:grpc-lib:build UP-TO-DATE
:examples:local-grpc-client:processResources UP-TO-DATE
:examples:local-grpc-client:processTestResources UP-TO-DATE
:examples:local-grpc-server:processResources UP-TO-DATE
:examples:local-grpc-server:processTestResources UP-TO-DATE
[Fatal Error] spring-cloud-build-1.1.3.RELEASE.pom:852:1: 尾随节中不允许有内容。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
:examples:cloud-eureka-server:compileJava UP-TO-DATE
:examples:cloud-eureka-server:processResources UP-TO-DATE
:examples:cloud-eureka-server:classes UP-TO-DATE
:examples:cloud-eureka-server:findMainClass
:examples:cloud-eureka-server:jar
:grpc-server-spring-boot-autoconfigure:compileJava UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:classes UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:jar UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:javadoc
:grpc-server-spring-boot-starter:compileJava UP-TO-DATE
:grpc-server-spring-boot-starter:classes UP-TO-DATE
:grpc-server-spring-boot-starter:jar UP-TO-DATE
:grpc-server-spring-boot-starter:compileTestJava UP-TO-DATE
:grpc-server-spring-boot-starter:testClasses UP-TO-DATE
:grpc-server-spring-boot-starter:test UP-TO-DATE
:grpc-server-spring-boot-starter:check UP-TO-DATE
:examples:cloud-grpc-server:compileJava
:grpc-server-spring-boot-autoconfigure:javadoc UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:javadocJar UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:sourceJar UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:signArchives SKIPPED
:grpc-server-spring-boot-autoconfigure:assemble UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:compileTestJava UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:processTestResources UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:testClasses UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:test UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:check UP-TO-DATE
:grpc-server-spring-boot-autoconfigure:build UP-TO-DATE
:grpc-server-spring-boot-starter:javadoc UP-TO-DATE
:grpc-server-spring-boot-starter:javadocJar UP-TO-DATE
:grpc-server-spring-boot-starter:signArchives SKIPPED
:grpc-server-spring-boot-starter:assemble UP-TO-DATE
:grpc-server-spring-boot-starter:build UP-TO-DATE
:examples:local-grpc-server:compileJava
:examples:cloud-eureka-server:bootRepackage[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。

:grpc-client-spring-boot-autoconfigure:compileJava UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:classes UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:jar[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
 UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:javadoc UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:javadocJar UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:sourceJar UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:signArchives SKIPPED
:grpc-client-spring-boot-autoconfigure:assemble UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:compileTestJava UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:processTestResources UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:testClasses UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:test UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:check UP-TO-DATE
:grpc-client-spring-boot-autoconfigure:build UP-TO-DATE
:grpc-client-spring-boot-starter:compileJava UP-TO-DATE
:grpc-client-spring-boot-starter:classes UP-TO-DATE
:grpc-client-spring-boot-starter:jar UP-TO-DATE
:grpc-client-spring-boot-starter:javadoc UP-TO-DATE
:grpc-client-spring-boot-starter:javadocJar UP-TO-DATE
:grpc-client-spring-boot-starter:signArchives SKIPPED
:grpc-client-spring-boot-starter:assemble UP-TO-DATE
:grpc-client-spring-boot-starter:compileTestJava UP-TO-DATE
:grpc-client-spring-boot-starter:testClasses UP-TO-DATE
:grpc-client-spring-boot-starter:test UP-TO-DATE
:grpc-client-spring-boot-starter:check UP-TO-DATE
:grpc-client-spring-boot-starter:build UP-TO-DATE
:examples:cloud-grpc-client:compileJava[Fatal Error] spring-cloud-build-1.2.2.RELEASE.pom:882:6: 文档中根元素后面的标记必须格式正确。
[Fatal Error] spring-data-releasetrain-Hopper-SR5.pom:145:6: 不允许有匹配 "[xX][mM][lL]" 的处理指令目标。
[Fatal Error] spring-cloud-build-1.1.3.RELEASE.pom:852:1: 尾随节中不允许有内容。

:examples:local-grpc-server:compileJava UP-TO-DATE
:examples:local-grpc-client:compileJava
:examples:cloud-eureka-server:assemble
:examples:cloud-eureka-server:compileTestJava UP-TO-DATE
:examples:cloud-eureka-server:processTestResources UP-TO-DATE
:examples:cloud-eureka-server:testClasses UP-TO-DATE
:examples:cloud-eureka-server:test UP-TO-DATE
:examples:cloud-eureka-server:check UP-TO-DATE
:examples:cloud-eureka-server:build
:examples:local-grpc-server:classes UP-TO-DATE
:examples:local-grpc-server:findMainClass
:examples:local-grpc-server:jar
:examples:local-grpc-server:bootRepackage
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
[Fatal Error] spring-cloud-build-1.1.3.RELEASE.pom:852:1: 尾随节中不允许有内容。
:examples:local-grpc-server:assemble
:examples:local-grpc-server:compileTestJava UP-TO-DATE
:examples:local-grpc-server:testClasses UP-TO-DATE
:examples:local-grpc-server:test UP-TO-DATE
:examples:local-grpc-server:check UP-TO-DATE
:examples:local-grpc-server:build
:examples:local-grpc-client:compileJava UP-TO-DATE
:examples:local-grpc-client:classes UP-TO-DATE
:examples:local-grpc-client:findMainClass
:examples:local-grpc-client:jar
:examples:local-grpc-client:bootRepackage
:examples:cloud-grpc-server:compileJava UP-TO-DATE
:examples:cloud-grpc-server:classes UP-TO-DATE
:examples:cloud-grpc-server:findMainClass
:examples:cloud-grpc-server:jar
:examples:local-grpc-client:assemble
:examples:local-grpc-client:compileTestJava UP-TO-DATE
:examples:local-grpc-client:testClasses UP-TO-DATE
:examples:local-grpc-client:test UP-TO-DATE
:examples:local-grpc-client:check UP-TO-DATE
:examples:local-grpc-client:build
:examples:cloud-grpc-server:bootRepackage
:examples:cloud-grpc-client:compileJava UP-TO-DATE
:examples:cloud-grpc-client:classes UP-TO-DATE
:examples:cloud-grpc-client:findMainClass
:examples:cloud-grpc-client:jar
:examples:cloud-grpc-client:bootRepackage
:examples:cloud-grpc-server:assemble
:examples:cloud-grpc-server:compileTestJava UP-TO-DATE
:examples:cloud-grpc-server:testClasses UP-TO-DATE
:examples:cloud-grpc-server:test UP-TO-DATE
:examples:cloud-grpc-server:check UP-TO-DATE
:examples:cloud-grpc-server:build
:examples:cloud-grpc-client:assemble
:examples:cloud-grpc-client:compileTestJava UP-TO-DATE
:examples:cloud-grpc-client:testClasses UP-TO-DATE
:examples:cloud-grpc-client:test UP-TO-DATE
:examples:cloud-grpc-client:check UP-TO-DATE
:examples:cloud-grpc-client:build

BUILD SUCCESSFUL

Total time: 6.237 secs
[sts] -----------------------------------------------------
[sts] Build finished succesfully!
[sts] Time taken: 0 min, 6 sec
[sts] -----------------------------------------------------


这是全部grpc-spring-boot-starter build 的输出

**Comment by yidongnan** [comment]
@rjzou 直接 ./gradlew build 的这个项目吗？

**Comment by rjzou** [comment]
是的，我是在eclipse 里面 build的，(使用gradlew.bat build 一样  windows)。

**Comment by rjzou** [comment]
有结果了吗？是什么原因？

**Comment by yidongnan** [comment]
@rjzou 我在window的命令行下直接 gradle build 并没有发现你所说的问题

**Comment by rjzou** [comment]
帮忙看下是什么问题的，你下载一个eclipse试试。

**Comment by yidongnan** [comment]
@rjzou 这个和是不是eclipse 没什么关系。你不是说直接命令行编译也是这样的错误吗。建议检查本地相关环境配置
