### ISSUE TITLE
Add support for Micrometer metric counters based on status code.

### ISSUE THREAD

**Issue by jbf154** [yidongnan/grpc-spring-boot-starter#341]
**The problem**

Currently, you can get timer metrics based on status codes and query them in something like prometheus.  Would be nice to have separate response counters for each status code tagged as well.  The use case is to be able to keep a running count of failures to trend and report on.

**The solution**

Use a `java.util.function.Function` lambda to cache the pre-built `Counter` objects like it is currently being done for `Timer` objects (see `AbstractMetricCollectingInterceptor`)

I'm happy to help if you'd like.

**Comment by ST-DDT** [comment]
I'm not sure whether I get you. Could you explain this in more detail please?

AFAICT you wish to count the number of error responses similar to those HTTP 4xx/5xx responses in default web calls.
Well, that's not how grpc works. The responseCounter only counts "successful" messages. If the call is not successful, then the call is ended without a message and only the error frame(?) is sent (which is counted by the timer already).
Or do you wish to count the (successful) messages that end up in a error state?

**Comment by jbf154** [comment]
Perhaps we need a new counter then.  I am looking at `MetricCollectingClientCallListener`.  Here you have the `onClose` method which receives the `Status` object as a parameter.  Could we add another status-code-tagged `Counter` here so that we can tell how many calls were closed with a particular `Status`?  

Right now the only insight available into the status code is via timer metrics (like `grpc_server_processing_duration_seconds_count`) but this isn't really that useful.  Errors can be processed very quickly and take very little time, so you can't tell _how many_ are actually happening.  This is interesting to see because there may be issues downstream from the gRPC service that result in these particular statuses (for example, `UNKNOWN`, `DEADLINE_EXCEEDED`, `RESOURCE_EXHAUSTED`, `INTERNAL`, etc.)

**Comment by ST-DDT** [comment]
All `Timer`s also implicitly contain a `Counter`:

````txt
grpc_server_processing_duration_seconds_count{method="GetAllItems",methodType="UNARY",service="MyService",statusCode="INTERNAL",} 3.0
grpc_server_processing_duration_seconds_sum{method="GetAllItems",methodType="UNARY",service="MyService",statusCode="INTERNAL",} 0.026518137
````
`/actuator/metrics/grpc.server.processing.duration`
![metrics](https://user-images.githubusercontent.com/1579362/77071342-260ff600-69ec-11ea-8ea8-f170b4187d7d.png)
`/actuator/metrics/grpc.server.processing.duration?tag=statusCode:INTERNAL`
![error-metrics](https://user-images.githubusercontent.com/1579362/77071486-6b342800-69ec-11ea-9075-50a0a558d6c9.png)

**Comment by jbf154** [comment]
Geez, I'm not sure why I didn't realize that!  Thanks for pointing that out.  I will close this issue.

**Comment by GitHub4Sandip** [comment]
> Perhaps we need a new counter then. I am looking at `MetricCollectingClientCallListener`. Here you have the `onClose` method which receives the `Status` object as a parameter. Could we add another status-code-tagged `Counter` here so that we can tell how many calls were closed with a particular `Status`?
> 
> Right now the only insight available into the status code is via timer metrics (like `grpc_server_processing_duration_seconds_count`) but this isn't really that useful. Errors can be processed very quickly and take very little time, so you can't tell _how many_ are actually happening. This is interesting to see because there may be issues downstream from the gRPC service that result in these particular statuses (for example, `UNKNOWN`, `DEADLINE_EXCEEDED`, `RESOURCE_EXHAUSTED`, `INTERNAL`, etc.)

Hi
I am looking for a case where I could do a count of categorization of errors like Database, Timeout Out etc... out of these Unexpected errors from the the down stream services. Appreciate if you could provide some code examples

**Comment by ST-DDT** [comment]
This is currently not supported.
You can implement the logic yourself by replacing all occurrences of `Status.Code` in `MetricCollectingServerCallListener` and the related classes with `Status` and then use the timer function to implement your custom status.cause =>tag mapping.
This will probably be done here: [`MetricCollectingServerInterceptor`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerInterceptor.java#L124-L129)
