### ISSUE TITLE
把证书打到jar中启动报错,证书文件不存在

### ISSUE THREAD

**Issue by celityowce** [yidongnan/grpc-spring-boot-starter#348]
启动报错，找不到证书文件 AbstractChannelFactory.toCheckedFile 调用File.isFile()方法，发现jar包中的文件为false。请问这个怎么处理。我用的是2.1.0

**Comment by ST-DDT** [comment]
Note to self:
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F348

-----------------------

[`AbstractChannelFactory#toFile`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/v2.1.0.RELEASE/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/springboot/autoconfigure/grpc/client/AbstractChannelFactory.java#L241) only works with files on the file system not inside a jar file.

Thats why we changed that logic to use a spring `Resource` which supports muliple locations and formats.
Please update to the latest version.

The following links should help you with the configuration:
https://yidongnan.github.io/grpc-spring-boot-starter/en/client/security#trusting-a-server
https://yidongnan.github.io/grpc-spring-boot-starter/zh-CN/client/security#%E4%BF%A1%E4%BB%BB%E6%9C%8D%E5%8A%A1%E7%AB%AF

https://docs.spring.io/spring/docs/5.2.x/spring-framework-reference/core.html#resources-implementations

Does this help you?
