### ISSUE TITLE
Please update documentation to match the latest security configuration names

### ISSUE THREAD

**Issue by emacsvsvi** [yidongnan/grpc-spring-boot-starter#349]
**The problem**

The server documentation for security doesn't have the correct names for the configuration of TLS. The values have changed from 

grpc.server.security.certificateChain=file:certificates/server.crt
grpc.server.security.privateKey=file:certificates/server.key

to 

grpc.server.security.certificateChain=certificates/server.crt
grpc.server.security.privateKey=certificates/server.key

**The solution**

Update the doc.

PS It would also be valuable to have working security configuration set up in the local-grpc-server and client example.

**Comment by ST-DDT** [comment]
Are you referring to the `file:` prefix?
I'm pretty sure that it works with that prefix:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/setup/SelfSignedMutualSetupTest.java#L36
Did you add the cert to your jar? Then you need to use the `classpath:` prefix (which is the default if nothing is specified).

**Comment by emacsvsvi** [comment]
Sorry, please disregard. I somehow ended up on an old version of the documentation that still had 
"path" added to the parameter names so I couldn't get it to work. Not sure how I got on that page because everything I look at now has the correct values.
