### ISSUE TITLE
Example for using Microsoft Identity Platform

### ISSUE THREAD

**Issue by ThomasBarnekow** [yidongnan/grpc-spring-boot-starter#352]
**The context**

I am trying to write a microservice in Java that exposes a gRPC API and calls the Microsoft Graph API on behalf of the user. The user authenticated with the client application against the Microsoft Identity Platform, using the v2.0 endpoint. The client could be a .NET Framework-based WPF app or an ASP.NET Core 3.0 web application. The clients use the MSAL library, which also exists in Java. Thus, if possible, I would want to use that API on both platforms (.NET and Java) where it makes sense.

I already have the basic gRPC microservice, using the `grpc-spring-boot-starter` to turn it into a Spring application. The task at hand is to add the security (authentication, authorization) piece to the gRPC microservice.

I also have examples for REST APIs that authenticate against AAD / the Microsoft identity platform:
  
- https://github.com/Azure-Samples/ms-identity-java-webapi
- https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-backend-sample
- https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-v2-spring-boot-backend-sample

And I looked at the `security-grpc-bearerAuth-server` example, which uses Keycloak.

**The question**

Unfortunately, I have limited experience in Spring, Spring Security, and the differences due to servlets vs. netty. Therefore, I'm having a little bit of trouble putting the pieces together. I would very much appreciate an example that shows how I can integrate all of this while getting access to the authentication (e.g., token) required to have my gRPC API call the Microsoft Graph.

The Microsoft examples I found extend either the `ResourceServerConfigurerAdapter` (see https://github.com/Azure-Samples/ms-identity-java-webapi/blob/master/msal-obo-sample/src/main/java/com/microsoft/azure/msalobosample/SecurityResourceServerConfig.java) or `WebSecurityConfigurerAdapter` (see https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot-samples/azure-active-directory-spring-boot-backend-sample/src/main/java/sample/aad/security/AADOAuth2LoginSecurityConfig.java). Could I also extend the `WebSecurityConfigurerAdapter` and add a bean that returns a `GrpcAuthenticationReader` or, more specifically, a `BearerAuthenticationReader`?

**Comment by ST-DDT** [comment]
Sorry, IMO such an example is outside of the scope of this project.

AFAICT you are providing/implementing a grpc-server/service that connects to a HTTP/REST-API.

Then all you have to do is:

1) Make it work as if you are providing a HTTP/REST-API (Setup the AuthenticationManager/Provider).
2) Once that works, add a `GrpcAuthenticationReader` bean to your application that does the same as the web security filter (Maybe the `BearerAuthenticationReader` is all you have to add).
3) Extract the credentials/token from the `Authentication(Context)` in the same way you do it with your HTTP variant and forward it to the Microsoft Graph API.

As for the specifics, you should ask these questions on StackOverflow or similar platforms.
