### ISSUE TITLE
如果在nacos作为注册中心 判定目标服务是否开通了grcp

### ISSUE THREAD

**Issue by dyg4228** [yidongnan/grpc-spring-boot-starter#356]
**The context**

What do you wish to achieve?

**The question**

What's the problem? What's not working? What's missing and why do you need it?

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot):
* grpc-java:
* grpc-spring-boot-starter:
* java: version + architecture (64bit?)
* Other relevant libraries...

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment]
https://translate.googleusercontent.com/translate_c?depth=1&nv=1&pto=aue&rurl=translate.google.com&sl=zh-CN&sp=nmt4&tl=en&u=https://github.com/yidongnan/grpc-spring-boot-starter/issues/356

Sorry, I don't understand the question.
@yidongnan Could you please take a look at this?

**Comment by yidongnan** [comment]
![image](https://user-images.githubusercontent.com/3163314/82184218-d8dfd000-9919-11ea-993e-32fb11e56038.png)
@dyg4228 使用此依赖，目标服务注册在 nacos 上会有 gRPC.port 元数据信息。整合示例可以参考此回复https://github.com/yidongnan/grpc-spring-boot-starter/issues/307#issuecomment-626098032
