### ISSUE TITLE
How to call the remote method by ip and port explicitly?

### ISSUE THREAD

**Issue by freezingWu** [yidongnan/grpc-spring-boot-starter#357]
**The context**
some special situation, I need to call the remote rpc by IP and  Port explicit.
etc.   http://{ip}:{port}/path/method

And go thru the framework, i can't  found the expected schemes(**static cannot meet my need**) to visit the remote, may i have your opinion on calling remote rpc by assigned ip and port ?

What do you wish to achieve?
 is there anyway to meet my need to visit remote rpc by assigned ip and port ?
(port and ip here  will be cnanged during runtime.)

**The question**

What's the problem? What's not working? What's missing and why do you need it?

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot): 2.2.5.RELEASE
* grpc-spring-boot-starter: 2.7.0.RELEASE
* java: JDK8 (64 bit)

**Comment by ST-DDT** [comment]
From where do you get these dynamic IPs and ports?

Are these transported during the original call / attached to the request context?

- If yes, then you have to create the stubs yourself. Because we don't know, when to close them. You might be able to reuse [`AbstractChannelFactory#configure(ManagedChannelBuilder, String) {`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/AbstractChannelFactory.java#L156) though.
- If no, then you also have the option to implement and register your own `NameResolverProvider` which would then provide the current ip and port (similar to the discovery service name resolver)

**Comment by freezingWu** [comment]
hi bro, thanks for your response so rapidly. 
i am creating a IM system, and undertaking the GRPC as my RPC in my spring cloud. due to different client may located in different Comet server(a sever hold the real physical connection), and each comet server would gain ip dynamicly when it's boot up .

that  is why i need to post the request by dynamic assigned ip and port (client may located at different server which hold the physical connection).

i will try to make the way out  with your suggestion, thanks a lot.

**Comment by freezingWu** [comment]
hi bro , need your comment on this.
I do a lot tests without "grpc-client-spring-boot-starter" and works well like this way: 
`xxxxxxxxxxGrpc
        .newBlockingStub(ManagedChannelBuilder.forAddress("192.168.31.174", 19090).usePlaintext().build())` 
the client can connect to the server as expectation.

but after i include the "grpc-client-spring-boot-starter" ,  it failed to connect to the server and console print log like:
`2020-05-20 12:22:25.094 ERROR 14876 --- [ault-executor-0] n.d.b.g.c.n.DiscoveryClientNameResolver  : No servers found for 192.168.31.174:19090
2020-05-20 12:22:25.094  WARN 14876 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<3>: (192.168.31.174:19090)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for 192.168.31.174:19090, cause=null}`
seems my orgion created channel impacted by something , could you tell me how to work a ground this ?

**Comment by ST-DDT** [comment]
Add `static://` to your address config.
Our code uses `ManagedChannelBuilder.forName()` so it defaults to using spring's discovery service.

**Comment by ST-DDT** [comment]
Does this answer your question?

**Comment by freezingWu** [comment]
hi bro , 
i solved my problems under your suggestions as a walk around solution eventually.

since my located severs is liimited and can be iteratorable , the most easy way is to add all the static ip:port to the profile setting , and we just need to arrange the target managed channel in our code .

thanks to your response. really great help .

**Comment by freezingWu** [comment]
hi bro , 
i solved my problems under your suggestions as a walk around solution eventually.

since my located severs is liimited and can be iteratorable , the most easy way is to add all the static ip:port to the profile setting , and we just need to arrange the target managed channel in our code .

thanks to your response. really great help .
