### ISSUE TITLE
Global Exception handler in grpc

### ISSUE THREAD

**Issue by freezingWu** [yidongnan/grpc-spring-boot-starter#358]
**The problem**

Hi , with the progress on grpc-starter learning ，it's really great help for my project . but right now i found a feature seems still not under cover yet .

as per springmvc , there is a @ControllerAdvice to capture all the throwable from controller .  
is it possible to create the similar feature for "grpc-server-spring-boot-starter" ?

looking forward your reply , thanks .

**Comment by ST-DDT** [comment]
What would be your expected result for an GrpcExceptionHandler?
`Status` or `Status.Code`

**Comment by freezingWu** [comment]
sorry for my late  response.  as per my expectation, server side may throw a exception without expected,and the client side may just got a status : unknow. 
so , the server side should make a approach to catch all the exception if happend ,with inputted function param: throwable ，and return something(maybe "Any") to replace the reponse to the client.

**Comment by ST-DDT** [comment]
It might be impossible to return a non error message. At least I'm not sure about the functional implications. How do I ensure that the correct type is sent to the client? Any is probably impossible. How should I treat Streaming vs unary calls? Should I close the call after an exception? Should I mark the call as aborted on the server side even if we sent a valid message as response?

IMO the exception to message mapping is too application dependent and thus should be done in the GrpcService implementations itself.
For now, I will only implement an exception to StatusRuntimeExceptionMapping.

**Comment by pdoro** [comment]
Hi. I've been reviewing this issue lately. In my opinion the best option would be to provide a `ServerInterceptor` very similar to this [one](https://github.com/grpc/grpc-java/issues/6162#issuecomment-533229174). The `ServerInterceptor` would start the call and handle any exception thrown by the GrpcHandler and delegate it to a GlobalGrpcExceptionHandler discovered through a custom `@GrpcAdvice` annotation.

Regarding your concerns about returning the correct type I suggest to only allow returning `io.grpc.Status` as this will be the most common pattern when an exception is raised. I haven't used `com.google.rpc.Status` but I beleive it allows to provide `Any<T>` which could be used as fallback value.

**Comment by ST-DDT** [comment]
> The `ServerInterceptor` would start the call and handle any exception thrown by the GrpcHandler and delegate it to a GlobalGrpcExceptionHandler discovered through a custom `@GrpcAdvice` annotation.

Why the additional `@GrpcAdvice` annotation? Do you wish to allow to filter the `GrpcExceptionHandler` per class/package?

> Regarding your concerns about returning the correct type I suggest to only allow returning `io.grpc.Status` as this will be the most common pattern when an exception is raised.

I agree.

> I haven't used `com.google.rpc.Status` but I believe it allows to provide `Any<T>` which could be used as fallback value.

I probably abstain from using that one, because it would complicate the process a lot more.
Any error that gets caught in the interceptor will end the call with the resolved error status code. No fallback value allowed.

-------------------

Do you think, we should make the `GrpcExceptionHandler` generic? E.g.: `GrpcExceptionHandler<IllegalArgumentException>` and handle only the specific ones? As an alternative we could add a `supports(Class<? extends Throwable>) ` Method. Or should we go for a concept that allows the exception handlers to be skipped by returning `null`?

------------------

Should we aim for a annotation driven handler e.g. `@GrpcExceptionHandler` or solely for a `@Bean` based one?

**Comment by pdoro** [comment]
> Why the additional `@GrpcAdvice` annotation? Do you wish to allow to filter the `GrpcExceptionHandler` per class/package?

An annotation such as `@GrpcAdvice` will be more familiar to people coming from spring-web plus the added benefit of filtering per class/package, yes.

> I probably abstain from using that one, because it would complicate the process a lot more.
Any error that gets caught in the interceptor will end the call with the resolved error status code. No fallback value allowed.

Definitely `io.grpc.Status` is the way to go.

> Do you think, we should make the GrpcExceptionHandler generic? E.g.: GrpcExceptionHandler<IllegalArgumentException> and handle only the specific ones? As an alternative we could add a supports(Class<? extends Throwable>) Method. Or should we go for a concept that allows the exception handlers to be skipped by returning null?

As said before, I believe familiarity with the spring-web way of handling errors is a benefit here. Usually for spring.web you define a GlobalExceptionHandler class annotated with [`@ControllerAdvice`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/ControllerAdvice.html) or `@RestControllerAdvice` and provide several methods annotated with [`@ExceptionHandler`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/ExceptionHandler.html) whose annotation signature allows to define multiple exception types. For grpc the best solution would look like this:

```java
@GrpcAdvice
public class GrpcExceptionHandler {

   @ExceptionHandler(IllegalArgumentException.class)
   public Status handleIllegalArgumentException( IllegalArgumentException ex ) {
      return Status.fromCode(Status.Code.INVALID_ARGUMENT)
         .withDescription("Email or password malformed")
	 .withCause(ex);
   }

   @ExceptionHandler({ MyCustomDomainException.class, AnotherCustomDomainException.class })
   public Status handleDomainException( RuntimeException ex ) {
      return Status.fromCode(Status.Code.INTERNAL)
         .withDescription(ex.getMessage())
	 .withCause(ex);
   }
}
```

I believe this approach is cleaner and will be familiar for every developer. The main concern I have is that `io.grpc.Status` can't carry `io.grpc.Metadata` which is very useful to provide extra information regarding errors. A solution might be to allow adding a Metadata argument on the signature and build a new Metadata instance on the `ServerInterceptor` so it can be forwarded to the introspected method. It's not very javaish but the only alternative would be to build a wrapper around both `io.grpc.Status` and `io.grpc.Metadata` and let it be the response type.

```java
@ExceptionHandler(UserNotFoundException.class)
public Status handleIllegalArgumentException( UserNotFoundException ex, Metadata metadata ) {
 
   Metadata.Key<String> key = Metadata.Key.of("userId", Metadata.ASCII_STRING_MARSHALLER);
   metadata.put(key, ex.getUserId());

   return Status.fromCode(Status.Code.INVALID_ARGUMENT)
      .withDescription("Email or password malformed")
      .withCause(ex);
}
```

> Should we aim for a annotation driven handler e.g. @GrpcExceptionHandler or solely for a @Bean based one?

In my opinion an annotation driven approach is best but would require more code. An iterative solution could be to allow a @Bean definition at first and later enhance the feature by doing a lookup for the desired annotation.

**Comment by ST-DDT** [comment]
This requires a lot of work and I don't wish to delay the next release for that long, so I have to delay this feature till the one after that.
