### ISSUE TITLE
关于Grpc 异常返回码

### ISSUE THREAD

**Issue by hehanpeng** [yidongnan/grpc-spring-boot-starter#360]
在公司使用Grpc 对接pyhon系统的时候，发现下游系统喜欢直接使用grpc的协议返回方式，我们需要捕获grpc的 子异常StatusRuntimeException，自定义一个handler 处理这些错误码，能否提供一种简介的方式，通过配置全局的处理，来统一处理异常，返回一个处理后的对象呢

**Comment by ST-DDT** [comment]
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F360

Possible duplicate of: 
https://github.com/yidongnan/grpc-spring-boot-starter/issues/358
