### ISSUE TITLE
关于泛化调用

### ISSUE THREAD

**Issue by hehanpeng** [yidongnan/grpc-spring-boot-starter#361]
未来能都开发泛化调用的功能，比如直接使用全局的包类名，一个invoke 方法，  方法和入参等，直接调用该rpc服务，而不是通过 grpcclient 注入的方式

**Comment by ST-DDT** [comment]
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F361

Please correct me if I understand you wrong. You wish to call a grpc method (client -> server) without a grpc stub.
(Probably using the grpc-reflection API?)

This should already be possible:
1) Inject a `ManagedChannel`
2) Use it to send requests to the server

For 2) the following links might help you
- https://github.com/grpc/grpc-java/blob/master/stub/src/main/java/io/grpc/stub/ClientCalls.java
- https://github.com/grpc-ecosystem/polyglot/blob/master/src/main/java/me/dinowernli/grpc/polyglot/grpc/DynamicGrpcClient.java

As for adding grpc-reflection-client-call support directly to this library, IMO that is outside of the scope of this library. (I'm not even sure there's anything I could add)
