### ISSUE TITLE
Creating multiple service classes with @GrpcService annotation

### ISSUE THREAD

**Issue by kkochanski** [yidongnan/grpc-spring-boot-starter#365]
**The context**

I would like to set multiple classes with @GrpcService annotation. My Service defined in Protocol Buffer contains multiple RPC procedures, that logically could be split into multiple @GrpcService classes.

**The question**

Currently, when I'm trying to do that, two services are properly loaded by Spring Boot. Once my client app is trying to call procedures from service class that was declared first, all is working properly. Although when I'm calling procedures from second service class, then I'm getting an 'unimplemented' error. 

Also, when I removed the first service class (that properly works), the second one is starting to work well.

I'm wondering if it the proper behavior or bug?

**Stacktraces and logs**

**The application's environment**

Which versions do you use?
* Spring (boot): 2.2.7.RELEASE
* grpc-java: 1.27.2
* grpc-spring-boot-starter: 2.7.0.RELEASE
* java: version + architecture (64bit?): Amazon Corretto-11.0.7.10.1 64 bit
* protoc: 3.11.4

**Additional information**

* Did it ever work before? Not aware
* How can we reproduce it? Set two services with @GrpcService annotation
* Do you have a demo? No

**Comment by ST-DDT** [comment]
This should work as described above.

**Comment by kkochanski** [comment]
Thank you for your answer. I will prepare some demo soon and share it.

**Comment by kkochanski** [comment]
As promised, here's two applications:
- server - https://github.com/kkochanski/grpc-server-test
- client - https://github.com/kkochanski/grpc-client-test

I tested it at 2.7.0 and 2.8.0 version starter.

With the current configuration, methods of one @grpcService won't get loaded. Although while running the application, there's information about that in the console:
`2020-06-07 20:08:08.287  INFO 7919 --- [           main] n.d.b.g.s.s.AbstractGrpcServerFactory    : Registered gRPC service: greet.Greet, bean: firstController, class: test.object.controller.FirstController`
`2020-06-07 20:08:08.289  INFO 7919 --- [           main] n.d.b.g.s.s.AbstractGrpcServerFactory    : Registered gRPC service: greet.Greet, bean: secondController, class: test.object.controller.SecondController`

The service that methods didn't properly work, will start work after commenting/removing another @grpcService class.

**Comment by ST-DDT** [comment]
Your both `@GrpcService` instances implement the same service interface:

- https://github.com/kkochanski/grpc-server-test/blob/master/src/main/java/test/object/controller/FirstController.java#L7
- https://github.com/kkochanski/grpc-server-test/blob/master/src/main/java/test/object/controller/SecondController.java#L7

````java
public class ___Controller extends test.grpc.greet.GreetGrpc.GreetImplBase {
````

Thus you have two implementations of the same service. These two implementations don't complement each other but replace each other. So its an usage issue.

This library/grpc should show a warning or throw an Exception in that case though.

I opened a ticket upstream to fix this error at the root:
https://github.com/grpc/grpc-java/issues/7125
Closing in favor of an upstream fix.

**Comment by kkochanski** [comment]
Ok, thanks a lot. I was not aware that it's possible to set multiple services in Protocol Buffer file. That approach will solve my problem.
