### ISSUE TITLE
Istio + Jaeger tracing with gRPC calls

### ISSUE THREAD

**Issue by kensixx** [yidongnan/grpc-spring-boot-starter#372]
**The context**

I want to know how to properly integrate this with Istio + Jaeger tracing. 
I need to know what are the needed dependencies for this to happen.

**The question**

I have two (2) apps, one serves as the gRPC client and one serves as the gRPC server, 

The expectation is that the trace between the gRPC client and the gRPC server must be reflected in Jaeger. But it's not happening.

I am inside a Kubernetes cluster that has Istio.

What really happens is HTTP request -> Envoy sidecar -> gRPC Client's Spring Boot @RestController -> get the Headers from HTTP request -> copy those to gRPC call before making the call -> gRPC Service.

How can I make the gRPC client <-> gRPC Service trace shown to Jaeger? 

Are there any dependencies that needs to be imported? 

Right now I have:

```xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
<!-- Used together with Sleuth to be able to trace gRPC calls. -->
<dependency>
	<groupId>io.zipkin.brave</groupId>
	<artifactId>brave-instrumentation-grpc</artifactId>
</dependency>
<!-- Add'l dependency for Istio + Jaeger gRPC tracing -->
<dependency>
	<groupId>io.jaegertracing</groupId>
	<artifactId>jaeger-client</artifactId>
</dependency>
```

I also have done something like this to "propagate the headers":
```java
private void propagateHeaders(HttpHeaders headers) {
	// TODO: adding these string values to a final / constant.
	// get these tracing headers from HTTP request, (coming from Envoy)
	String xRequestIdFromHttpHeader = headers.getFirst("x-request-id");
	String xB3TraceIdFromHttpHeader = headers.getFirst("x-b3-traceid");
	String xB3SpanIdFromHttpHeader = headers.getFirst("x-b3-spanid");
	String xB3ParentSpanIdFromHttpHeader = headers.getFirst("x-b3-parentspanid");
	String xB3SampledFromHttpHeader = headers.getFirst("x-b3-sampled");
	String xB3FlagsFromHttpHeader = headers.getFirst("x-b3-flags");
	String xOtSpanContextFromHttpHeader = headers.getFirst("x-ot-span-context");

	// create a custom gRPC header, they call it Metadata
	Metadata xRequestIdMetadata = new Metadata();
	Metadata xB3TraceIdMetadata = new Metadata();
	Metadata xB3SpanIdMetadata = new Metadata();
	Metadata xB3ParentSpanIdMetadata = new Metadata();
	Metadata xB3SampledMetadata = new Metadata();

	// TODO: refactor. putting to List<> and using foreach to attach this one.
	// assign value of the x-request-id Metadata to the value of the HTTP Header
	xRequestIdMetadata.put(Metadata.Key.of("x-request-id", Metadata.ASCII_STRING_MARSHALLER), xRequestIdFromHttpHeader);
	xB3TraceIdMetadata.put(Metadata.Key.of("x-b3-traceid", Metadata.ASCII_STRING_MARSHALLER), xB3TraceIdFromHttpHeader);
	xB3SpanIdMetadata.put(Metadata.Key.of("x-b3-spanid", Metadata.ASCII_STRING_MARSHALLER), xB3SpanIdFromHttpHeader);
	xB3ParentSpanIdMetadata.put(Metadata.Key.of("x-b3-parentspanid", Metadata.ASCII_STRING_MARSHALLER), xB3ParentSpanIdFromHttpHeader);
	xB3SampledMetadata.put(Metadata.Key.of("x-b3-sampled", Metadata.ASCII_STRING_MARSHALLER), xB3SampledFromHttpHeader);

	// TODO: refactor. putting to List<> and using foreach to attach this one.
	// use MetadataUtils to attach that new Metadata to our stub before requesting to our gRPC Server via gRPC
	greetingServiceStub = MetadataUtils.attachHeaders(greetingServiceStub, xRequestIdMetadata);
	greetingServiceStub = MetadataUtils.attachHeaders(greetingServiceStub, xB3TraceIdMetadata);
	greetingServiceStub = MetadataUtils.attachHeaders(greetingServiceStub, xB3SpanIdMetadata);
	greetingServiceStub = MetadataUtils.attachHeaders(greetingServiceStub, xB3ParentSpanIdMetadata);
	greetingServiceStub = MetadataUtils.attachHeaders(greetingServiceStub, xB3SampledMetadata);
}
```

But it doesn't seem to work..

**UPDATE:**

I am now investigating that this is due to Spring Cloud Sleuth + `brave-instrumentation-grpc `dependency, assuming that Istio works as intended.

**Comment by linarkou** [comment]
Hi! I recently had the same problem. And there is no need in setting up tracing in your application implicitly. Istio should do it automatically, so you should check your k8s configs.
First of all check if Pod has 2 containers - your app and proxy. If you don't have proxy - check annotation `sidecar.istio.io/inject: “true”` in Deployment.
Then check your Service - it should have port with name `grpc` (it is important! Istio search port by name and setup HTTP/2 for name with `grpc` prefix).  ex:
```
ports:
  - name: grpc
    port: 50101
    targetPort: 50101
    protocol: TCP
```
But I had problem with port - i used 9090 and it is not worked. 50101 is working, and I don't know why.

**Comment by kensixx** [comment]
Oh! This is really helpful. Thank you so much for this. I've been looking at the wrong angle, which is by the application tracing part.

an HTTP request goes first before entering my gRPC client. 

gRPC Client K8s Service current `.yaml`:
```yaml
ports:
  - name: http-grpc-caller
    protocol: TCP
    port: 8080
    # Refer to deployments/grpc-caller.yaml containers.name
    targetPort: grpc-caller
```

So obviously `http-grpc-caller` should be `grpc` right? 😁 

then my gRPC Service:
 ```yaml
ports:
  - name: grpclb # Put this as name to indicate that you want to reach a gRPC port
    protocol: TCP
    port: 80
    # Refer to deployments/grpc-wc-service.yaml containers[0].ports[0].name
    targetPort: grpc-port
```
So this needs to be `grpc` named only, right? or `grpclb` should work?

**Comment by linarkou** [comment]
> So obviously `http-grpc-caller` should be `grpc` right? 😁
In client you receive requests over HTTP/1 from browser, isn't it? So you shouldn't change name here. You should change name of port in k8s Service for grpc **server**

> So this needs to be `grpc` named only, right? or `grpclb` should work?
`grpclb` should work.

**Comment by kensixx** [comment]
Oh I see. Thanks so much for these explanations. Atleast I narrowed down my scope on the problem. 

My current gRPC Server's K8s service.yaml doesn't work as stated above. Maybe I should try port `50101` as well just like what you did. 😄 

> Then check your Service - it should have port with name grpc (it is important! Istio search port by name and setup HTTP/2 for name with grpc prefix).
Can I have a resource / documentation link regarding this one? I just learned this now and I never would've caught that if it wasn't for you. I don't see it anywhere as well on Istio's docs. Or maybe I just don't know where to look.

**Comment by kensixx** [comment]
Hi! I've just tried this now and confirm it actually works. Thanks so much @linarkou! 🙏

There's seems to be no explanation yet why the port `50101` in particular is working. Is Istio only accepting a range of gRPC ports exposed via Kubernetes Services as of date?

**Comment by linarkou** [comment]
You're welcome! I've read this article (contains info about port naming): https://medium.com/namely-labs/a-crash-course-for-running-istio-1c6125930715

But I don't know about range of gRPC ports 😞
