### ISSUE TITLE
How to configure thread count

### ISSUE THREAD

**Issue by kitkars** [yidongnan/grpc-spring-boot-starter#373]
Hi,
Thanks for this project. It is very easy to use and works just great. 

I have a question regarding setting the thread count as we do for the regular spring boot web applications. Is there any way to do that? What is the default thread count?

Thanks.

**Comment by ST-DDT** [comment]
I don't know the default Thread count, but according to [this issue](https://github.com/grpc/grpc-java/issues/2123) its supposedly `processors * 2`. There is no config option for that (yet), but you can still configure it using a `GrpcServerConfigurer`:

````java
@Bean
GrpcServerConfigurer grpcServerConfigurer(@Value("${grpc.server.workerEventLoopGroup.threads}") int threads) {
    return builder -> ((NettyServerBuilder) builder).workerEventLoopGroup(new NioEventLoopGroup(threads));
}
````

You can change the other related options in a similar fashion.

**Comment by NielsUll** [comment]
This fails with the error message:
All of BossEventLoopGroup, WorkerEventLoopGroup and ChannelType should be provided or neither should be

So a bit more is required

**Comment by ST-DDT** [comment]
This has changed in a recent version of grpc. Thanks for pointing this out.
