### ISSUE TITLE
[GraalVM Support] Disabling CGLIB proxies for autoconfiguration

### ISSUE THREAD

**Issue by nickjn92** [yidongnan/grpc-spring-boot-starter#379]
**The problem**

Currently Spring Boot applications are unable to run with GraalVM and native image due to CGLIB proxies on the autoconfiguration classes. The current error is observed on startup:
```
2020-07-10 13:54:17.715 ERROR 1412912 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: @Configuration classes need to be marked as proxyBeanMethods=false. Found: [net.devh.boot.grpc.common.autoconfigure.GrpcCommonCodecAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientMetricAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientSecurityAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientAutoConfiguration, net.devh.boot.grpc.client.autoconfigure.GrpcClientHealthAutoConfiguration, net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration, net.devh.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration, net.devh.boot.grpc.server.autoconfigure.GrpcServerFactoryAutoConfiguration]
```

**The solution**

Set the proxyBeanMethods=false on the `@Configuration` annotation on the Autoconfiguration classes

**Comment by ST-DDT** [comment]
Thank you for bringing this to our attention.

I'm quite interested in the native image approach.
Could you prepare an example project that I could use to verify that this library is fully native image compatible?

**Comment by lthd92** [comment]
https://github.com/lthd92/graalvm-grpc-starter
here ya go. Let me know if you need anything more from me :)

**Comment by ST-DDT** [comment]
Thanks for your fast response. I'm busy this weekend, but I hope I have time to look into it next week.
