### ISSUE TITLE
服务间调用失败

### ISSUE THREAD

**Issue by laihuibiao** [yidongnan/grpc-spring-boot-starter#390]
**服务间调用失败**
客户服务端Jar版本：2.9.0.RELEASE

开发过程：
按官网例子操作

出错：
客户端：
UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
服务端：

````txt
io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 16030100790100007503036e6df560c9418b859c748674f6
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:306)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
````

谢谢~

**Comment by yidongnan** [comment]
The server runs in PLAINTEXT mode, but the client tries to connect it in TLS (default) mode.
https://yidongnan.github.io/grpc-spring-boot-starter/en/trouble-shooting.html#transport-failed

**Comment by laihuibiao** [comment]
已经添加了，还是不行~





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yidongnan/grpc-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上8:30
收件人:&nbsp;"yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"295830345"<295830345@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yidongnan/grpc-spring-boot-starter] 服务间调用失败 (#390)





 
The server runs in PLAINTEXT mode, but the client tries to connect it in TLS (default) mode.
 https://yidongnan.github.io/grpc-spring-boot-starter/en/trouble-shooting.html#transport-failed

**Comment by laihuibiao** [comment]
使用的注册中心是:Nacos
想问下，是否有nacos的例子












------------------------------------------------------------------------------
已经添加了，还是不行~





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "yidongnan/grpc-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上8:30
收件人:&nbsp;"yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"295830345"<295830345@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yidongnan/grpc-spring-boot-starter] 服务间调用失败 (#390)





 
The server runs in PLAINTEXT mode, but the client tries to connect it in TLS (default) mode.
 https://yidongnan.github.io/grpc-spring-boot-starter/en/trouble-shooting.html#transport-failed

**Comment by ST-DDT** [comment]
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F390

If you still get the same error message, then you probably have a typo in your config.

There are only two reasons why this message appears:
- Connecting with TLS mode to a PLAINTEXT connection (check your config)
- Connecting to a binary-encoded service, that is not a gRPC or HTTP service (wrong port?), (check the [nacos data](https://github.com/yidongnan/grpc-spring-boot-starter/blob/1043e47ca980ac25fe7ce9b01cf3c8aa4932cef2/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java#L216) send by the server and check whether the referenced port (or `gRPC.port`) belongs to the grpc service)

Based on the error message (`SslHandler [...] ClientTlsHandler`), I'm pretty sure its a config issue.
Maybe add a `@Autowired GrpcChannelsProperties` to your class and output/log the respective config option before starting the call.

The nacos example is tracked here:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/307 (not yet implemented)

**Comment by laihuibiao** [comment]
First of all, thank you（首先表示感谢）


1）Client / server code development, in strict accordance with the official website （客户端/服务端代码开发上，都严格按照了官网）
2）In&nbsp;config，Many attempts have been made，such&nbsp;as（在配置上，进行了许多的尝试，例如）
1th：

2nd：

3th：参考了这个链接https://blog.csdn.net/qq_35875671/article/details/106012835，但是不行！
3）but，all&nbsp;fail
4）this&nbsp;is&nbsp;client&nbsp;exception



5）this&nbsp;is&nbsp;server&nbsp;exception






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yidongnan/grpc-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月21日(星期二) 晚上11:06
收件人:&nbsp;"yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"295830345"<295830345@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yidongnan/grpc-spring-boot-starter] 服务间调用失败 (#390)





 
https://translate.google.com/translate?sl=zh-CN&amp;tl=en&amp;u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F390
 
If you still get the same error message, then you probably have a typo in your config.
 
There are only two reasons why this message appears:
  
Connecting with TLS mode to a PLAINTEXT connection (check your config)
 
Connecting to a binary-encoded service, that is not a gRPC or HTTP service (wrong port?), (check the nacos data send by the server and check whether the referenced port (or gRPC.port) belongs to the grpc service)
  
Based on the error message (SslHandler [...] ClientTlsHandler), I'm pretty sure its a config issue.
 Maybe add a @Autowired GrpcChannelsProperties to your class and output/log the respective config option before starting the call.
 
The nacos example is tracked here:
 #307 (not yet implemented)

**Comment by ST-DDT** [comment]
The important parts seem to be missing. Also there seem to be some escaped formatting codes in there.

**Comment by laihuibiao** [comment]
just，need&nbsp;to&nbsp;help~I try more，but fail~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yidongnan/grpc-spring-boot-starter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 凌晨4:40
收件人:&nbsp;"yidongnan/grpc-spring-boot-starter"<grpc-spring-boot-starter@noreply.github.com&gt;;
抄送:&nbsp;"295830345"<295830345@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yidongnan/grpc-spring-boot-starter] 服务间调用失败 (#390)





 
The important parts seem to be missing. Also there seem to be some escaped formatting codes in there.

**Comment by ST-DDT** [comment]
Have you debugged your application and checked the property at runtime?
If it still doesnt work we need an example project to reproduce this.

**Comment by ST-DDT** [comment]
We will reopen this once we get more information.
