### ISSUE TITLE
Inaccurate metrics from MetricCollectingServerInterceptor

### ISSUE THREAD

**Issue by YixingCheng** [yidongnan/grpc-spring-boot-starter#393]
**The context**

Our project is using `MetricCollectingServerInterceptor` to collect metrics. We wish to get the accurate metrics for our gRPC service.

**The bug**

We found the metrics we got is always just 1/10 of the accurate value.
For example, we use `grpc.server.requests.received` to find number of requests received.
We always got 0.1 but which actually there is 1 request.
I am not sure anybody else also had this issue.

**Stacktrace and logs**

Is there a stacktrace or a hint in the logs? (very important)
Screenshots work as well, but don't screenshot your logs.

I am attaching a screenshot from our datadog. Here the metrics is `grpc.server.processing.duration` as count, it is supposed to report integer value like 1, 2, but it is actually report 0.1, 0.2.
![image](https://user-images.githubusercontent.com/4967016/88319306-d0689480-ccd0-11ea-982a-7f4f4127a840.png)

**Steps to Reproduce**

1. Any Spring application using `gprc-spring-boot-starter`
2. Use `MetricsCollectionServerInterceptor`
3. We used datadog to collect metrics, not sure if promethus will still have the same issue.

**The application's environment**

Which versions do you use?
* Spring (boot): 2.2.4
* grpc-java: 1.27.1
* grpc-spring-boot-starter: 2.7.0
* java: version + architecture (64bit?) adoptopenjdk/openjdk11
* Other relevant libraries...

**Additional context**

* Did it ever work before?
* Do you have a demo?

**Comment by ST-DDT** [comment]
From the code I consider it unlikely, that it increments the counter by a fraction each time.

https://github.com/yidongnan/grpc-spring-boot-starter/blob/1043e47ca980ac25fe7ce9b01cf3c8aa4932cef2/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerCall.java#L69
https://github.com/yidongnan/grpc-spring-boot-starter/blob/1043e47ca980ac25fe7ce9b01cf3c8aa4932cef2/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerCall.java#L63

Have you tried accessing the value directly from the actuator/metrics endpoint?

![actuator-metrics](https://user-images.githubusercontent.com/1579362/88373968-19841b80-cd99-11ea-9cee-964be93c6799.png)

I only used it with Prometheus. There I didn't encounter this issue. Please note, that Prometheus provides two separate metrics, for the call count and the call duration sum.

````prometheus
grpc_server_processing_duration_seconds_count{method="...",methodType="UNARY",service="...",statusCode="OK",} 6112.0
grpc_server_processing_duration_seconds_sum{method="...",methodType="UNARY",service="...",statusCode="OK",} 5.598520498
````

Is it possible that you accidentally access the duration metric and your calls happen to take only ~0.1s each?

**Comment by ST-DDT** [comment]
@YixingCheng Have you tried my suggestions?

**Comment by YixingCheng** [comment]
Hi, thanks for looking into this.

I think I figured out why the counter is showing a decimal value for a Counter in datadog. As datadog documentation states here: https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/?tab=python#count
> Stored as a RATE type in Datadog. Each value in the stored timeseries is a time-normalized delta of the metric’s value over the StatsD flush period.

This basically tells that the raw counter value will be normalized to the flush period.

The flush period/polling frequence is default to 10s: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/statsd/StatsdProperties.java#L72,

so that's the reason why I saw all the values in datadog is one tenth of the raw value.

I am thinking is it a good idea for the `MetricCollectingServerInterceptor` to find this `management.metrics.export.statsd.pollingFrequency`, and instead of increment 1, but increment `pollingFrequency` to offset the normalization if we don't want to tweak the raw value in datadog anymore.

**Comment by ST-DDT** [comment]
> I think I figured out why the counter is showing a decimal value for a Counter in datadog. As datadog documentation states here: https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/?tab=python#count
> 
> > Stored as a RATE type in Datadog. Each value in the stored timeseries is a time-normalized delta of the metric’s value over the StatsD flush period.
> 
> This basically tells that the raw counter value will be normalized to the flush period.

That's a very interesting detail, thanks for sharing it.

> I am thinking is it a good idea for the `MetricCollectingServerInterceptor` to find this `management.metrics.export.statsd.pollingFrequency`, and instead of increment 1, but increment `pollingFrequency` to offset the normalization if we don't want to tweak the raw value in datadog anymore.

The metrics are stored as `RATE` with a unit of `1/s`. So the value of `0.1/s` is technically correct, but I agree with you that it doesn't feels right. I still won't increment the count by more than one each due to these two reasons:

* Other metric frameworks might behave differently (prometheus does) and changing the counter might cause issues with them
* It will get really awkward, if the flush period stops being a plain second value and instead becomes something with milliseconds.

I'm not sure which display/graph library you use, but I recommend you configure it to display the result as `1/10s` which fixes the decimal values and still conveys a proper unit. It even conveys the original interval that was used to create the graph.

The raw data are correct, just their presentation feels off.

If you have further questions or suggestions feel free to comment, but for now I consider this as "works as intended".
