### ISSUE TITLE
How to dynamically add/remove grpc servers

### ISSUE THREAD

**Issue by samotoo** [yidongnan/grpc-spring-boot-starter#397]
**The context**

I'm working on a system which consists of one master and multiple agents (running on different machines). The master acts as the grpc client and the agent acts as the server. The master collects status from and send control commands to those agents by making grpc calls.

**The question**

The problem is that agent could be added to/removed from the system at runtime, which means the grpc servers are dynamically added or removed. So I think creating client beans when the master started is not enough, if a new agent is added, a new grpc client has to be created as well.

Could you please advice on how to implement this using grpc-spring-boot-starter? Or should I manage the channels and stubs by myself?

**Stacktraces and logs**

N/A

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.0.RELEASE
* grpc-java: 1.30.0
* grpc-spring-boot-starter: 2.9.0.RELEASE
* java: version + architecture (64bit?) JDK 1.8 on x86_64

**Additional information**

N/A

**Comment by ST-DDT** [comment]
I would reverse the structure. Making the master the server and the agents the clients. The agents the open a streamung call to the server. The server can use it to send commands to the agent and the agent can send their status to the server.

-----------

If you wish to keep your design then you might be better of with just plain grpc as this library does not yet support custom channel lifecycles. How should the library know that you dont need the connection anymore? Future versions might contain features to support this.
If you still wish to use this library, then you have to extend the channel factory to expose the cached managed channels and close them after you don't need them anymore. As an alternative you could create a channel factory per channel and close it in it entirely. However the later variant does not support automatic injection.

**Comment by samotoo** [comment]
Thanks a lot for the quick response. I will try to extend the channel factory.
