### ISSUE TITLE
Loading 1.1.0 via gradle gives error

### ISSUE THREAD

**Issue by backjo** [yidongnan/grpc-spring-boot-starter#40]
When I updated 1.0.2.RELEASE -> 1.1.0.RELEASE in my gradle file and do a clean build, I'm getting the following error: 

Classpath entry points to a file that is not a JAR archive: /Users/jback/.gradle/caches/modules-2/files-2.1/net.devh/grpc-server-spring-boot-starter/1.1.0.RELEASE/597c601f63d24b1b6eeed8cb51710d79c6279d3d/grpc-server-spring-boot-starter-1.1.0.RELEASE.jar.asc

 Unresolved reference: devh

Not sure that this happens for everyone, but likely since 1.0.2.RELEASE loaded fine and nothing else has changed in my gradle file.

**Comment by yidongnan** [comment]
I'm so sorry, there was a trouble when deploy to maven central. I already hotfix it. you can use 1.1.1.RELEASE. I will be more careful later.

**Comment by backjo** [comment]
No worries, just wanted to give you a heads up :)

Thanks for the spring-boot-starter package :)
