### ISSUE TITLE
Allow GrpcService on @Bean methods

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#406]
**The problem**

`GrpcService` is only applicable to types.

**The solution**

Allow `GrpcService` on methods, so that it can be used in `@Configuration` classes. This allows for using non-Spring/third-party `BindableService` in Spring gRPC code.

**Alternatives considered**

A custom `GrpcServiceDiscoverer` can be created, but that requires more code, defeats the purpose of autoconfiguration, and disables `AnnotationGrpcServiceDiscoverer`. I think the last assumption is incorrect; there's no reason we can't have one class annotated with `GrpcService`, and another `@Configuration` method with annotated with `GrpcService`.

**Additional context**

Spring Boot 2.3.1.RELEASE, grpc-spring-boot-starter 2.9.0.RELEASE

**Comment by ST-DDT** [comment]
I will fix it soon.

**Comment by asarkar** [comment]
I’m assuming you’ll create another `GrpcServiceDiscoverer` that can find methods annotated with `GrpcService`?

**Comment by ST-DDT** [comment]
[`@GrpcService](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/service/GrpcService.java)

It might be easier than that. Maybe all I have to do is add `ElementType.METHOD` to the annotation, but I have to test that.

**Comment by ST-DDT** [comment]
If I have enough time I will fix it in 1.10.1
