### ISSUE TITLE
Retry with different call credentials

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#415]
Currently, I configure a `CallCredentials` bean that gets picked up by `GrpcClientSecurityAutoConfiguration`. Creating the call credentials involves acquiring a token by making more than one HTTP calls. For the purposes of this ticket, this token can be thought of as an OAuth token that has a certain expiration. What I'm looking to do is instead of acquiring the token before every call, cache the token once acquired, and if the server returns an authorization error, retry the call with a new token. Obviously, this will require some sort of information being passed from the interceptor that handles the response, and the `CallCredentials` bean. See an example of retrying interceptor [here](https://github.com/grpc/grpc-java/issues/5856#issuecomment-511077021).

Note that gRPC has inbuilt [retry mechanism](https://github.com/grpc/proposal/blob/master/A6-client-retries.md), but it's idempotent, and doesn't allow for side-effects like refreshing a token.

This can all be done in the interceptor without any need for a `CallCredentials` bean, but IMO, it's cleaner (but more complicated) to separate the retry from the generation of `CallCredentials`.

Since Spring has a retry mechanism, I'm hoping this discussion may lead to such a feature in this library. If time permits, I will make a contribution. This ticket is to start the brainstorming process.

**Comment by asarkar** [comment]
See https://github.com/grpc/grpc-java/issues/7345

**Comment by ST-DDT** [comment]
The interceptor in the mentioned issue is a nice example. If I have the time, I will add it to the client security docs for session based authentication.
