### ISSUE TITLE
Allow GrpcGlobal*Interceptor on @Bean methods

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#418]
Allow `GrpcGlobalClientInterceptor` and `GrpcGlobalServerInterceptor` on `@Bean` methods. The motive is similar to https://github.com/yidongnan/grpc-spring-boot-starter/issues/406. The implicit assumption that we have access to the source code isn't always true.

**Comment by ST-DDT** [comment]
Like this one?
#394 https://github.com/yidongnan/grpc-spring-boot-starter/pull/394/commits/2ff58cdc73b63792e885e836ae9c107125ec53bd (v1.10.0+)

[`GrpcGlobalClientInterceptor`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/interceptor/GrpcGlobalClientInterceptor.java#L41)
[`GrpcGlobalServerInterceptor`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/interceptor/GrpcGlobalServerInterceptor.java)

Or is there something I missed/that doesn't work as expected?

**Comment by asarkar** [comment]
I see, this was a change introduced in 2.10.0 (not 1.10.0 as in your comment). I was looking at 2.9.0, that didn't have this change.
