### ISSUE TITLE
In process client can't resolve in process server

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#421]
**src/test/resources/application.yml**
```
grpc:
  server:
    in-process-name: other
    port: -1
  client:
    my-service:
      address: in-process:other
    other:
      address: static://${some-server}:${some-port}
```
**src/test/resources/application-it.yml**
```
grpc.client.other:
  address: in-process:other
```

The idea is to be able to point `other` to `some-server` for functional testing, and `in-process:other` for integration testing.

```
@GrpcClient("my-service")
private lateinit var stub: SomeStub
```

**The bug**

When `grpc-netty` is on the classpath, two `ChannelFactory` are created:

```
2020-08-31 10:26:44.635 [Test worker] [INFO ] MyServiceIntegrationTest - The following profiles are active: it
...
2020-08-31 10:16:56.770 [Test worker] [INFO ] n.d.b.g.c.a.GrpcClientAutoConfiguration - Detected grpc-netty: Creating NettyChannelFactory + InProcessChannelFactory
```

and the test works as expected.

However, when `grpc-netty` is removed from the classpath:
```
val testRuntimeOnly by configurations
testRuntimeOnly.exclude("io.grpc", module = "grpc-netty")
```

```
2020-08-31 10:26:44.635 [Test worker] [INFO ] MyServiceIntegrationTest - The following profiles are active: it
...
2020-08-31 10:26:45.746 [Test worker] [WARN ] n.d.b.g.c.a.GrpcClientAutoConfiguration - Could not find a GrpcChannelFactory on the classpath: Creating InProcessChannelFactory as fallback
```

**Stacktrace and logs**

```
UNAVAILABLE: Could not find server: my-service
io.grpc.StatusException: UNAVAILABLE: Could not find server: my-service
```

This is a bug. It shouldn't be looking for `my-service`, everything is in process and available.

**Comment by ST-DDT** [comment]
Sorry, I don't have time to look into it right now. I'll try to look into it asap.

In the meantime, can you check whether the grpc in-process-server is already up and running when the client tries to connect?
(registered inside [`InProcessServer#registry`](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/inprocess/InProcessServer.java#L40))

**Comment by asarkar** [comment]
It seems you meant [InProcessServer.register()](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/inprocess/InProcessServer.java#L107) method, not the [InProcessServer#registry](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/inprocess/InProcessServer.java#L40) `Map`. I checked, and in the failure case, the `InProcessServer.register()` is **not** invoked when the client tries to connect. In the success case, it is. In both cases, `InProcessServer.start()` method is invoked.

**Comment by ST-DDT** [comment]
Could you please include a little bit more of your `Stacktrace and logs`?
And please also include the code that you use to invoke that stub.
There might be an issue with using the in-process-server connection during `@PostConstruct`

**Comment by ST-DDT** [comment]
I assume the issue here is that you try to use the bean too early.
You may only use the injected stubs that point to the in-process server in/after the `ApplicationStartedEvent`.
For external services, you can start using the stubs as early as `@PostContruct`/ `afterPropertiesSet`.
Without a complete stacktrace/reproducible example, I cannot narrow it down any further.
Connecting to the in-process server prior to the application started event may result in unspecified behavior.

**Comment by asarkar** [comment]
> I assume the issue here is that you try to use the bean too early.

I don't have the complete stacktrace available after 4 months, but there's no change in bean lifecycle or usage as far as the app is concerned. Simply removing `grpc-netty` from classpath exhibits this bug.
