### ISSUE TITLE
Can send message to the special client with the instanceId instead of using application name ?

### ISSUE THREAD

**Issue by yhf597869822** [yidongnan/grpc-spring-boot-starter#422]
i want to send to special client with instane ID
![image](https://user-images.githubusercontent.com/31063160/92085623-ab9d2c00-edfb-11ea-8c9b-2d9af4c8d494.png)

**Comment by ST-DDT** [comment]
Lets check whether I got you right.
You have a group of servers ("agents"), that you wish to connect to using your stub, but you wish to send the message only to a specific one (by id) based on the context?
AFAICT this isn't supported by grpc-java.
The only possibility for that is, if you create the stubs dynamically.

**Comment by yhf597869822** [comment]
thx,I create the native client to connect the server.
