### ISSUE TITLE
集成的starter 能支持seata吗

### ISSUE THREAD

**Issue by hehanpeng** [yidongnan/grpc-spring-boot-starter#425]
我看到seata 的官网说是支持grpc 但是缺乏资料，有没考虑下，集成一个示例，放在官网目录上

**Comment by ST-DDT** [comment]
https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F425

Could you please add a link to their grpc adapter? 
I couldn't find the relatated code only the maven artifact.

Is there anything we have to do to be compatible?
AFAICT the only problem is that their project has no documentation, but they should probably fix that themselves.

**Comment by hehanpeng** [comment]
今天测试了下，目前看不需要你们做兼容，我将seata的拦截器加载进了全局拦截配置，是可以传递事务的xid的
`@Configuration
public class GrpcSeataConfig {

    @GrpcGlobalClientInterceptor
    ClientInterceptor ClientTransactionInterceptor() {
        return new ClientTransactionInterceptor();
    }

    @GrpcGlobalServerInterceptor
    ServerInterceptor ServerTransactionInterceptor() {
        return new ServerTransactionInterceptor();
    }
}`
`@Configuration
@AutoConfigureBefore({GrpcServerAutoConfiguration.class})
@Slf4j
public class GrpcInterceptorConfiguration {

    @Bean
    @ConditionalOnMissingBean(ServerTransactionInterceptor.class)
    public ServerTransactionInterceptor serverTransactionInterceptor() {
        log.info("Pre-Registering service serverTransactionInterceptor");
        return new ServerTransactionInterceptor();
    }

    @Bean
    @ConditionalOnMissingBean(ClientTransactionInterceptor.class)
    public ClientTransactionInterceptor clientTransactionInterceptor() {
        log.info("Pre-Registering service clientTransactionInterceptor");
        return new ClientTransactionInterceptor();
    }

}`

**Comment by ST-DDT** [comment]
IMO these beans can easily be added by everyone themselves, there is no need to add extra documentation in this library.
I added a separate issue for explicit global interceptor code in the docs: #427

As for the missing documentation on their site, have you opened an issue there?
if not please create one and link it here, then maybe we can add the relevant configuration to their page.
As an alternative, we could add a sample to their project.

grpc-code: https://github.com/seata/seata/tree/develop/integration/grpc

**Comment by ST-DDT** [comment]
Closed in favor of #427

**Comment by qianxunclub** [comment]
> 今天测试了下，目前看不需要你们做兼容，我将seata的拦截器加载进了全局拦截配置，是可以传递事务的xid的
> 
> ```java
> @Configuration
> public class GrpcSeataConfig {
> 
>     @GrpcGlobalClientInterceptor
>     ClientInterceptor ClientTransactionInterceptor() {
>         return new ClientTransactionInterceptor();
>     }
> 
>     @GrpcGlobalServerInterceptor
>     ServerInterceptor ServerTransactionInterceptor() {
>         return new ServerTransactionInterceptor();
>     }
> }
> ```
> 
> ```java
> @Configuration
> @AutoConfigureBefore({GrpcServerAutoConfiguration.class})
> @Slf4j
> public class GrpcInterceptorConfiguration {
> 
>     @Bean
>     @ConditionalOnMissingBean(ServerTransactionInterceptor.class)
>     public ServerTransactionInterceptor serverTransactionInterceptor() {
>         log.info("Pre-Registering service serverTransactionInterceptor");
>         return new ServerTransactionInterceptor();
>     }
> 
>     @Bean
>     @ConditionalOnMissingBean(ClientTransactionInterceptor.class)
>     public ClientTransactionInterceptor clientTransactionInterceptor() {
>         log.info("Pre-Registering service clientTransactionInterceptor");
>         return new ClientTransactionInterceptor();
>     }
> 
> }
> ```
> 
> maven坐标
> 
> ```
> 
> <dependency>
>   <groupId>io.seata</groupId>
>   <artifactId>seata-spring-boot-starter</artifactId>
>   <version>1.3.0</version>
> </dependency>
> ```

哈喽，我也是这样配置的，但是 ClientTransactionInterceptor 断点进不去，GRPC 发送前没有走这个方法，又遇到吗？
