### ISSUE TITLE
GrpcClientHealthAutoConfiguration reports incorrect Health status

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#432]
**The context**

Monitor the health of gRPC client apps.

**The bug**

`GrpcClientHealthAutoConfiguration` reports the client application down if the channel has transient failures. However, the [Javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ConnectivityState.html#TRANSIENT_FAILURE) clearly states:
> Channels in this state will eventually switch to the CONNECTING state and try to establish a connection again.

Thus, the correct health status to report is [OUT_OF_SERVICE](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/health/Status.html#OUT_OF_SERVICE), not `DOWN`. In other words, the application is alive but not accepting requests, not down.

Also note that starting with version 2.3.0.RELEASE, Spring Boot provides liveness and readiness information under Actuator health endpoint. See [Kubernetes Probes](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-kubernetes-probes) for details.

Also opened https://github.com/grpc/grpc-java/issues/7465.

**Comment by ST-DDT** [comment]
> `GrpcClientHealthAutoConfiguration` reports the client application down if the channel has transient failures. However, the [Javadoc](https://grpc.github.io/grpc-java/javadoc/io/grpc/ConnectivityState.html#TRANSIENT_FAILURE) clearly states:
> 
> > Channels in this state will eventually switch to the CONNECTING state and try to establish a connection again.
> 
> Thus, the correct health status to report is [OUT_OF_SERVICE](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/health/Status.html#OUT_OF_SERVICE), not `DOWN`. In other words, the application is alive but not accepting requests, not down.

I will change it in the next version.

> Also note that starting with version 2.3.0.RELEASE, Spring Boot provides liveness and readiness information under Actuator health endpoint. See Kubernetes Probes for details.

I am aware of these. However, they are either configured via config or custom health providing code, so there is nothing for me to do here. They have originally been introduced in 2.2 as health groups, because the `/health` call provided too many health indicators that were irrelevant for the actual health status. 2.3 extended them to be explicitly setable, but that's probably all they do. Or did I miss something.

**Comment by asarkar** [comment]
> However, they are either configured via config or custom health providing code

That's not correct. In addition to to reporting `Health` status, a `HealthIndicator` can publish `ReadinessState` and `LivenessState` events that contribute to the overall application status. At least that's my experience so far, the Spring Boot team has no clear guidance on this matter.
However, it's a little tricky since the client may be running an older version of Spring Boot that doesn't support these events; so, to support them, we can use reflection to publish the events. It's not type safe, but it's backward compatible.

**Comment by ST-DDT** [comment]
> > However, they are either configured via config or custom health providing code
> 
> That's not correct. In addition to to reporting `Health` status, a `HealthIndicator` (like the one in `GrpcClientHealthAutoConfiguration`) can publish `ReadinessState` and `LivenessState` events that contribute to the overall application status. At least that's my experience so far, the Spring Boot team has no clear guidance on this matter.

This is what I meant with "making them setable".

> However, it's a little tricky since the client may be running an older version of Spring Boot that doesn't support these events; so, to accommodate them, we can use reflection to publish the events. It's not type safe, but it's backward compatible.

AFAICT there is no spring-library code that actually uses them (except for the health groups). Setting these values/using the events is entirely up to the user's code.

> The “liveness” Probe should not depend on health checks for external systems.
> [...]
> As for the “readiness” Probe, the choice of checking external systems must be made carefully by the application developers, i.e. Spring Boot does not include any additional health checks in the readiness probe.
>
> [Source](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-kubernetes-probes-external-state)

**Comment by asarkar** [comment]
> no spring-library code that actually uses them

True, but these aren't meant to be consumed by Spring. Their usefulness is when deploying in a Kubernetes environment.

**Comment by ST-DDT** [comment]
> True, but these aren't meant to be consumed by Spring.

They aren't meant to be produced by a spring/this library either.

**Comment by asarkar** [comment]
> They aren't meant to be produced by a spring/this library either.

I'm not sure I understand your reluctance in publishing these events from the library. You already implemented a `HealthEndpoint` that is not useful to Spring either, but somehow you decide supporting a Kubernetes probes is not useful? The `HealthEndpoint` is the only place where these events can be reliably published; if you don't want to support them, you should also remove the `HealthEndpoint` and the user can create their own.

**Comment by ST-DDT** [comment]
The `grpcChannel` health status is purely informational. Just like the `mongo` one pretty much every other `HealthIndicator` (except ready and liveness). It offers you the ability to check which component inside your application is down. It is and was never intended to be used as indicator whether the entire application is up or down.

**Comment by asarkar** [comment]
> one indicator for all channels

As I’m sure you know, Actuator accumulates the status from individual `HealthIndicator`s, so this comes for free already.

**Comment by asarkar** [comment]
After speaking with the Spring Boot team on Twitter, it appears that the intended design is not to update application availability from inside an HealthIndicator, but instead add the health indicator to the liveness and/or readiness groups.

So, just changing the health status from down to out of service is what's left to do in this ticket.

**Comment by asarkar** [comment]
@ST-DDT I found a bigger issue. `GrpcClientHealthAutoConfiguration` sets up `grpcChannelHealthIndicator` bean regardless of the channel name, which under Actuator healthpoint, would become  `grpcChannel`. If there are multiple channels, this doesn't distinguish between them. The `HealthIndicator` should be named according to the channel name.

**Comment by ST-DDT** [comment]
> @ST-DDT I found a bigger issue. `GrpcClientHealthAutoConfiguration` sets up `grpcChannelHealthIndicator` bean regardless of the channel name, which under Actuator healthpoint, would become `grpcChannel`. If there are multiple channels, this doesn't distinguish between them. The `HealthIndicator` should be named according to the channel name.

Yeah, I'm aware of that:

> Whether the structure of "one indicator for all channels" is optimal, is something else entirely.

**Comment by asarkar** [comment]
@ST-DDT Perhaps this ticket could be broken up into two parts. One to change the status from `DOWN` to `OUT_OF_SERVICE`, that is a PR that can be easily merged. Another to track channel status for each client, which is more work.
