### ISSUE TITLE
how to set custom executor to the gRPC Service

### ISSUE THREAD

**Issue by banandh** [yidongnan/grpc-spring-boot-starter#434]
when i register a gRPC service using gRPC libraries , i can customize the executor behavior to get maximum performance out of the serice. 

Similarly using this artifact how i can customize executor for any gRPC service

**Comment by ST-DDT** [comment]
Are you referring to the grpc server setup?
[`GrpcServerConfigurer`](https://yidongnan.github.io/grpc-spring-boot-starter/en/server/configuration.html#grpcserverconfigurer) are the way for any additional customization. If you can tell me which kind of customization you wish to achieve, then maybe we could integrate it into this library.

**Comment by tahuy** [comment]
Hi @ST-DDT, I want to custom executor like this
`@Component
public class BootGrpcConfiguration extends GRpcServerBuilderConfigurer{

    @Override
    public void configure(ServerBuilder<?> serverBuilder) {
        ExecutorService threadPoolExecutor = Executors.newFixedThreadPool(1);
        serverBuilder.executor(threadPoolExecutor);

    }

}`

**Comment by ST-DDT** [comment]
This has already been answered in the answer above yours.
Please use the **[`GrpcServerConfigurer`](https://yidongnan.github.io/grpc-spring-boot-starter/en/server/configuration.html#grpcserverconfigurer)** to do that.
You can then use an implementation that is pretty close to your example.

Please tell me if my answer or the linked documentation is hard to understand and if you have any suggestions on how to improve them.

**Comment by tahuy** [comment]
Thank @ST-DDT 
I implement executor and it working.
Here is my code
````java
@Configuration
public class GrpcClientExecutorConfiguration {
    private static final Logger log = LoggerFactory.getLogger(LogGrpcInterceptor.class);
    @Bean
    public GrpcChannelConfigurer keepAliveClientConfigurer() {
        return (channelBuilder, name) -> {
            if (channelBuilder instanceof NettyChannelBuilder) {
                log.info("Configured client executor!!!");
                ((NettyChannelBuilder) channelBuilder)
                        .executor(Executors.newFixedThreadPool(16))
                        .keepAliveTime(30, TimeUnit.SECONDS)
                        .keepAliveTimeout(5, TimeUnit.SECONDS);
            }
        };
    }
}
````
I still have one concern that does my custom thread pool shutdown when I shutdown spring?

**Comment by ST-DDT** [comment]
No it wont be closed like that.
You have to implement `Closeable` for that too.

**Comment by tahuy** [comment]
> No it wont be closed like that (unless you shutdown the entire JVM).
> You have to implement a `Closeable` bean for that too.

Hi @ST-DDT , for the first one, it means that when I restart spring it not shutdown the executors?
Second one, can you detail me where to implement Closeable. I am newbie with Spring and GRPC, I am sorry for any stupid questions.

**Comment by ST-DDT** [comment]
> Hi @ST-DDT , for the first one, it means that when I restart spring it not shutdown the executors?

Yes, because spring does not know about the executors (as they are not beans themselves).
You might be able to circumvent that by decaring it as a bean (factory/provider) too.

````java
@Bean(destroy="shutdown")
Executor grpcExecutor() {
    return Executors.newFixedThreadPool(16);
}

    @Bean
    public GrpcServerConfigurer keepAliveServerConfigurer(Executor grpcExecutor) {
        return serverBuilder -> {
            if (serverBuilder instanceof NettyServerBuilder) {
                log.info("Configured server executor!!!");
                ((NettyServerBuilder) serverBuilder)
                        .executor(grpcExecutor)
                        .keepAliveTime(30, TimeUnit.SECONDS)
                        .keepAliveTimeout(5, TimeUnit.SECONDS)
                        .permitKeepAliveWithoutCalls(true);
            }
        };
    }
````

> Second one, can you detail me where to implement Closeable. I am newbie with Java, Spring and GRPC, I am sorry for any stupid questions.

````java
class CloseableGrpcServerConfigurer implements GrpcServerConfigurer, Closeable {
    [...]
}
````

**Comment by tahuy** [comment]
Hi @ST-DDT 
Thank for your answer, for first one I implement like this
````java
@Configuration
public class GrpcServerExecutorConfiguration {
    private static final Logger log = LoggerFactory.getLogger(GrpcServerExecutorConfiguration.class);

    @Bean(destroyMethod = "shutdown")
    ExecutorService grpcExecutor() {
        return Executors.newFixedThreadPool(16);
    }

    @Bean
    public GrpcServerConfigurer keepAliveServerConfigurer() {
        return serverBuilder -> {
            if (serverBuilder instanceof NettyServerBuilder) {
                log.info("Configured server executor!!!");
                ((NettyServerBuilder) serverBuilder)
                        .executor(grpcExecutor())
                        .keepAliveTime(30, TimeUnit.SECONDS)
                        .keepAliveTimeout(5, TimeUnit.SECONDS)
                        .permitKeepAliveWithoutCalls(true);
            }
        };
    }
}
````

For second, what I think here is right or wrong
````java
@Component
class CloseableGrpcServerConfigurer implements GrpcServerConfigurer, Closeable {

    private ExecutorService threadPoolExecutor = Executors.newFixedThreadPool(16);

    @Override
    public void configure(ServerBuilder<?> serverBuilder) {
        serverBuilder.executor(threadPoolExecutor);

    }

    @PreDestroy
    public void close() {
        threadPoolExecutor.shutdown();
    }

}
````

**Comment by ST-DDT** [comment]
Both variant look good to me. Now, its just a matter of preference.

**Comment by tahuy** [comment]
@ST-DDT thank you so much for recommendation.
For GRPC with spring, if you have anything for newbie like me, please tell me

**Comment by thousmile** [comment]
Hi @ST-DDT,  @tahuy ，How to customize the client thread pool!

The default client thread pool uses InheritableThreadLocal to transfer data, which will reuse the data of the previous request. If the grpc request ends, clear the data in InheritableThreadLocal. Then the latest InheritableThreadLocal data cannot be obtained next time

````
    @Slf4j
    @GrpcGlobalClientInterceptor
    public static class TokenClientInterceptor implements ClientInterceptor {

        @Override
        public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> methodDescriptor,
                                                                   CallOptions callOptions,
                                                                   Channel channel) {
            var delegate = channel.newCall(methodDescriptor, callOptions);
            return new ForwardingClientCall.SimpleForwardingClientCall<>(delegate) {

                @Override
                public void start(Listener<RespT> responseListener, Metadata headers) {
                    var tenantId = GrpcContext.getTenantId();
                    log.info("2.Client TenantId: String \n{}", tenantId);
                    if (StringUtils.hasText(tenantId)) {
                        headers.put(TENANT_ID, tenantId);
                    }
                    super.start(new ForwardingClientCallListener.SimpleForwardingClientCallListener<RespT>(responseListener) {

                        @Override
                        public void onClose(Status status, Metadata trailers) {
                            log.info("4.onClose: \n{}", GrpcContext.getTenantId());
                            GrpcContext.reset();
                            super.onClose(status, trailers);
                        }

                    }, headers);
                }

            };
        }
    }
````

````
public class GrpcContext {

    private static final InheritableThreadLocal<String> TENANT_ID = new InheritableThreadLocal<>();

    public static void setTenantId(String tenantId) {
        if (StringUtils.hasText(tenantId)) {
            TENANT_ID.set(tenantId);
        } else {
            TENANT_ID.remove();
        }
    }

    public static String getTenantId() {
        return TENANT_ID.get();
    }

    public static void reset() {
        TENANT_ID.remove();
    }

}

````

[source code](https://github.com/thousmile/spring-cloud-grpc-demo)

**Comment by ST-DDT** [comment]
@thousmile Is this a question or an answer?

**Comment by thousmile** [comment]
@ST-DDT Of course, it's a problem. How to customize the client thread pool ，
My problem is that when the client thread pool reuses threads, the data passed by InheritableThreadLocal is chaotic

**Comment by ST-DDT** [comment]
In the future please create a new issue for new questions.
However, this is a general grpc-java question, that should either be asked directly at grpc-java's github repo or on stackoverflow.

-----------

I'm not sure why the data are chaotic like this, but I had a similar problem on the server side, where the threads can change between each invocation of the Interceptor and the Client/ServerCall. So especially for the `ClientCall` in your case I assume that is whats happening. 

I think `CallCredentials` are intended for you usecase.
`stub.withCallCredentials(...)`

You might want to have a look at these helper method / class:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java#L287

````java
String tenantId = ...;
Metadata map = new Metadata();
map.put(...)
CallCredentials credentials = CallCredentialsHelper.authorizationHeaders(map); // reuseable
Stub tenantStub = stub.withCallCredentials(credentials); // reuseable
tenantStub.someCall(...);
````
