### ISSUE TITLE
Having a dependency issue with the server portion of this project

### ISSUE THREAD

**Issue by andrewlandfried** [yidongnan/grpc-spring-boot-starter#436]
**The context**

I am looking to use import the dependencies for this project, using Spring Boot 2.3.4 and gRPC-java version 1.32.1. 

**The question**

I have successfully imported the client portion of this project and made calls to localhost server that is not running with your grpc library. Now i want to test with a grpc server that was created using your library, but there is a problem with the server dependency. 

**Stacktraces and logs**

When I `mvn clean install` i get ...
`Could not resolve version conflict among [io.grpc:grpc-testing:jar:1.32.1 -> io.grpc:grpc-core:jar:[1.32.1,1.32.1], net.devh:grpc-spring-boot-starter:jar:2.10.1.RELEASE -> net.devh:grpc-server-spring-boot-starter:jar:2.10.1.RELEASE -> net.devh:grpc-server-spring-boot-autoconfigure:jar:2.10.1.RELEASE -> net.devh:grpc-common-spring-boot:jar:2.10.1.RELEASE -> io.grpc:grpc-core:jar:1.31.1, net.devh:grpc-spring-boot-starter:jar:2.10.1.RELEASE -> net.devh:grpc-server-spring-boot-starter:jar:2.10.1.RELEASE -> net.devh:grpc-server-spring-boot-autoconfigure:jar:2.10.1.RELEASE -> io.grpc:grpc-netty-shaded:jar:1.31.1 -> io.grpc:grpc-core:jar:[1.31.1,1.31.1], net.devh:grpc-spring-boot-starter:jar:2.10.1.RELEASE -> net.devh:grpc-server-spring-boot-starter:jar:2.10.1.RELEASE -> net.devh:grpc-server-spring-boot-autoconfigure:jar:2.10.1.RELEASE -> io.grpc:grpc-services:jar:1.31.1 -> io.grpc:grpc-core:jar:[1.31.1,1.31.1]]`

POM looks like this: 

`<dependency>`
`<groupId>io.grpc</groupId>`
`<artifactId>grpc-netty-shaded</artifactId>`
`<scope>runtime</scope>`
`<version>${grpc.version}</version>`
`</dependency>`

`<dependency>`
           `<groupId>net.devh</groupId>`
            `<artifactId>grpc-spring-boot-starter</artifactId>`
            `<version>2.10.1.RELEASE</version>`
`<!--            <exclusions>-->`
`<!--                <exclusion>-->`
`<!--                    <groupId>io.grpc</groupId>-->`
`<!--                    <artifactId>grpc-netty-shaded</artifactId>-->`
`<!--                </exclusion>-->`
`<!--            </exclusions>-->`
`        </dependency>`

I have tried with/without `grpc-netty-shaded` exclusion. I have also tried including the `grpc-netty` (not shaded) dependency instead. 

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.4
* grpc-java: 1.32.1
* grpc-spring-boot-starter: 2.10.1.RELEASE
* java: version + architecture (64bit?): java 11, 64 bit mac
* Other relevant libraries...

**Additional information**

* Did it ever work before? - It works with just the client. When i add the combined dependency, the server dependency breaks my build.
* How can we reproduce it? `mvn clean install` with this setup/versions.
* Do you have a demo?

I am mostly confused because your documentation says you are compatible with `grpc-netty-shaded` but there seems to be some sort of disconnect I'm not seeing. Any help would be great. Thanks.

**Comment by ST-DDT** [comment]
Have you tried adding the grpc-bom for 1.32.1 to your project? This might solve the dependency conflicts due to dismatching versions of grpc.
grpc-spring-boot-starter works with multiple versions of grpc, as long as all grpc-libraries use the same version.

**Comment by andrewlandfried** [comment]
Sorry, took me a while to look at this again. It looks like this library works when I use grpc.version **1.31.1**. 

I added this grpc-bom dependency like you mentioned, 
`<dependency>`
            `<groupId>io.grpc</groupId>`
            `<artifactId>grpc-bom</artifactId>`
            `<version>${grpc.version}</version>`
            `<type>pom</type>`
        `</dependency>`
but it didn't seem to help. 
When i used version 1.31.1 as the grpc-version, it builds with and without the bom. Not sure if it's just an incompatibility or what.

**Comment by ST-DDT** [comment]
Without the bom it uses whatever version is used transitively. If you use 1.32.1 yourself, then the dependencies used by this library cause a conflict (unless you overwrite them all).
If you use the bom you can use whatever grpc-java version you wish to use.

**Comment by ST-DDT** [comment]
You have to add the bom to your `<dependencyManagement>` section + scope import.

**Comment by andrewlandfried** [comment]
Yes .. this worked. I've never used a BOM so i added to the `dependencies` without adding to the `dependencyManagement` section. Thanks for the help. Confirmed it's now building correctly with java-grpc version 1.33.1.
