### ISSUE TITLE
Meltdown & fallback

### ISSUE THREAD

**Issue by ukid** [yidongnan/grpc-spring-boot-starter#439]
**The question**
Does this lib support meltdown and fallback?If not,any ideas on how to implement the future?

**Comment by ST-DDT** [comment]
Can you please provide a little bit more context or a link to the library you are referring to?

**Comment by ukid** [comment]
So appreciate your reply.

I was looking for some kind of feature like [Hystrix CircuitBreaker and Feign](https://www.appsdeveloperblog.com/hystrix-circuitbreaker-and-feign/). With this feature,we can handle rpc calls gracefully,when the microservice is unavailable for some reason.

**Comment by uweschaefer** [comment]
why not just wrap grpc calls into hystrix (or resilience4j or...) commands?

**Comment by ukid** [comment]
@uweschaefer So this lib doesn't have the feature.And i have to find out where the grpc call is,then override the function.Is that correct?

**Comment by ST-DDT** [comment]
Yes, this library and grpc-java itself don't support that feature yet. However, there might be libraries for grpc(-java) out there that support that feature.

If you use a service mesh such as istio, then you could simulate the circuit breakers using the network layer itself without modifying your code.

If you wish to implement it in Java then your point of entry are grpc's Client or ServerInterceptors.
Circuitbreakers should be rather easy to implement there.
As for the fallback responses, you can either use a lookup map in the interceptors or fork the call and delegate it to an in-process server.
Note: Both variants require some in-depth considerations to work without issues (memory leaks, streaming calls etc)

**Comment by ukid** [comment]
@ST-DDT Many thanks!

**Comment by ukid** [comment]
@uweschaefer  Thanks again!
