### ISSUE TITLE
Upgrade to Spring boot 2.3.4

### ISSUE THREAD

**Issue by iperminov** [yidongnan/grpc-spring-boot-starter#440]
**The problem**

gRPC Spring boot starter currently depends on Spring boot 2.3.3. Unfortunately, Spring boot 2.3.3 contains a memory problem on Java 11+: https://github.com/spring-projects/spring-boot/issues/22998 (full description in https://github.com/spring-projects/spring-boot/issues/22991). This problem has been fixed in Spring boot 2.3.4.

**The solution**

Please, upgrade gRPC Spring boot starter to Spring boot 2.3.4.

**Comment by ST-DDT** [comment]
Thank you for reporting this issue to us, we will be fixing this issue with our next release.
In the meantime you can overwrite the used spring-boot version by including the latest spring-boot bom.
