### ISSUE TITLE
Disabling the server for actual application

### ISSUE THREAD

**Issue by andrewlandfried** [yidongnan/grpc-spring-boot-starter#445]
**The context**

I have the server dependencies included in my project because I want to make some mock servers for some integration tests. However, in my actual application, I only need the client.

**The question**

When I start my application, I notice this log line: 
`method=createAndStartGrpcServer line=91 - gRPC Server started, listening on address: *, port: 9090` 

Is there a way to disable the server? I didn't see too much about the actual configuration properties in the documentation other than being able to change the port. 

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.4
* grpc-java: 1.31.1
* grpc-spring-boot-starter: 2.10.1.LATEST
* java: version + architecture (64bit?)   64 bit java 11
* Other relevant libraries...

**Comment by ST-DDT** [comment]
How about using the server part as a `test` dependency? (alternatively as `provided`/`compileOnly`/`optional` dependency)

> Is there a way to disable the server? I didn't see too much about the actual configuration properties in the documentation other than being able to change the port.

Use `-1` to disable it.

https://github.com/yidongnan/grpc-spring-boot-starter/blob/aa286ab3e4c78899f77a9872b1a275a51ca4733f/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java#L78-L86

**Comment by asarkar** [comment]
I believe https://github.com/yidongnan/grpc-spring-boot-starter/issues/419 talks about the same problem, and a solution was discussed. This ticket can be closed a dup in favor in 419.
