### ISSUE TITLE
有没有使用consul作为服务注册中心的demo

### ISSUE THREAD

**Issue by 470139387** [yidongnan/grpc-spring-boot-starter#446]

**Comment by ST-DDT** [comment]
[English translation](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F446)

------------------------

There isn't an example for that yet. But the grpc part works exactly the same as in the discovery example (eureka):
- [cloud-grpc-client](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples/cloud-grpc-client)
   Configure your client the same as for any other consul powered client and make sure you use `discovery:<name>` as the client address
- [cloud-grpc-server](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples/cloud-grpc-server)
  Just configure your server the same as for any other consul powered server

Does this answer your question.

**Comment by ZMRWEGO** [comment]
@470139387   兄弟现在有了 可以看一下
- [consul服务端](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples/cloud-grpc-server-consul)
- [consul消费端](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples/cloud-grpc-client-consul)
引入对应的依赖就可以了

**Comment by ST-DDT** [comment]
@ZMRWEGO Thanks for linking to the demos. I guess this is now solved.
