### ISSUE TITLE
memory leaking because sleuth span is not close 

### ISSUE THREAD

**Issue by jixianzhao** [yidongnan/grpc-spring-boot-starter#45]
`Tried to close span but it is not the current span: .  You may have forgotten to close or detach.`

I got many warn like above. And finally result in endless full GC. 

![image](https://cloud.githubusercontent.com/assets/5001927/26783389/7840fc74-4a2a-11e7-8d12-c0cb21c37a10.png)

![image](https://cloud.githubusercontent.com/assets/5001927/26778149/aac63d70-4a12-11e7-8c01-6e6ff00723dc.png)

![image](https://cloud.githubusercontent.com/assets/5001927/26778155/b3abcb08-4a12-11e7-9e60-1c55813d79e0.png)

![image](https://cloud.githubusercontent.com/assets/5001927/26778164/beca6210-4a12-11e7-9a14-eb5788dd5054.png)

seems tracer.close(span); did not close every spans correctly, inside  TraceClientInterceptor.interceptCall().checkedStart().

After comment out all code which depends on sleuth, problem is fixed.

Looking forward to your reply.
Thanks

**Comment by yidongnan** [comment]
@iamtiancaif What version are you using?
