### ISSUE TITLE
一个GRPC服务分多个实现类去实现的问题

### ISSUE THREAD

**Issue by zhouze-java** [yidongnan/grpc-spring-boot-starter#450]
在我的 proto 文件中,所有的方法都是写到一个 service 中,之后编译生成一个 ServiceGrpc 类, 然后我需要继承他的 ServiceGrpc.ServiceImplBase 类实现我自己的业务逻辑,  然后我分了多个实现类分别实现 ServiceGrpc.ServiceImplBase 中的部分方法,然后所有实现类都加上了 @GrpcService 注解,但是启动项目后,只有最后一个被加载的实现类里面的方法是可以使用的, 其他都找不到具体的实现方法     
  
比如我有个 base 类 , 然后 A B C 三个类都继承 base类,都加上 @GrpcService 注解, 启动的时候 A B C 按顺序加载, 然后只有C类里面的方法是可以正常使用的其他都找不到   
  
想问一下这种情况有什么处理办法吗

**Comment by ST-DDT** [comment]
[English translation](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F450)

------------------------------

Possibly a duplicate of https://github.com/yidongnan/grpc-spring-boot-starter/issues/401

I expect the server to throw an exception:

https://github.com/yidongnan/grpc-spring-boot-starter/blob/aa286ab3e4c78899f77a9872b1a275a51ca4733f/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java#L126-L128

Could you do me a favor and debug, why the server factory didn't throw an exception in that line?
