### ISSUE TITLE
Is it possible to use with Wire

### ISSUE THREAD

**Issue by iTanChi** [yidongnan/grpc-spring-boot-starter#458]
Currently I'm using [Wire](https://github.com/square/wire) to generate Kotlin classes from protos for my project (contains Spring Boot and Kotlin multiplatform modules)

Wire supports gRPC but I cannot use it with spring boot and your lib because your lib requires `BindableService`

So how can I use Wire with your lib. I can not change to grpc-kotlin because of `multiplatform` targets

This is an example of grpc service from Wire:
```
import com.squareup.wire.Service
import com.squareup.wire.WireRpc

interface OrderServiceServer : Service {
  @WireRpc(
    path = "/OrderService/GetOrder",
    requestAdapter = "GetOrderRequest#ADAPTER",
    responseAdapter = "GetOrderResponse#ADAPTER"
  )
  suspend fun GetOrder(request: GetOrderRequest): GetOrderResponse
}
```

**Comment by ST-DDT** [comment]
You have to implement the [`GrpcServiceDiscoverer`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/service/GrpcServiceDiscoverer.java#L32) interface and add it to you application context ( `@Bean` ).

See also [`AnnotationGrpcServiceDiscoverer`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/service/AnnotationGrpcServiceDiscoverer.java) as an example.

Does that answer your question?

**Comment by iTanChi** [comment]
@ST-DDT `GrpcServiceDiscoverer` is still using `ServerServiceDefinition` -> need io.grpc.*

**Comment by ST-DDT** [comment]
So Wire isn't based on grpc-java at all?
Then its outside of the scope of this library.

**Comment by iTanChi** [comment]
Thanks, I will find another way
