### ISSUE TITLE
Grpc actuator health check

### ISSUE THREAD

**Issue by LeoBarykin** [yidongnan/grpc-spring-boot-starter#461]
**The context**

I want to customize grpc health checks/

**The question**

We are using starter in apps, which are deployed to Openshift platform. We use spring boot and actuator for health checking.
Firstly, I have not found here [https://yidongnan.github.io/grpc-spring-boot-starter/en/actuator.html] info about default health check, could you show me, where this feature is documented (or add it)?
Now, if an app faces grpc error, state is changed to DOWN and container restarts. How can I customize or exclude it?  

Thank you!

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.0
* grpc-java: 1.30
* grpc-spring-boot-starter: 2.9.0
* java: version + architecture (64bit?) Java 11 64

**Comment by ST-DDT** [comment]
I assume you are using `/actuator/health` as endpoint. But for kubernetes there is especially `/actuator/health/readiness` and `/actuator/health/liveness`:
See also:
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-kubernetes-probes
Does that help you?

**Comment by LeoBarykin** [comment]
Thank you! We really use /actuator/health as probes now. I will look into article you suggest, since our probes need being improved.
But I still think that few lines about GrpcClientHealthAutoConfiguration class in documentation will be really helpful. Btw we excluded this configuration as a temporary fix.

**Comment by ST-DDT** [comment]
I'll add it to our ToDo list.

**Comment by ST-DDT** [comment]
I use this issue as the reminder.

**Comment by ST-DDT** [comment]
FYI: Moved issue to the next milestone

**Comment by asarkar** [comment]
I've a blog post on this exact topic: https://blogs.asarkar.com/technical/grpc-kubernetes-spring/
