### ISSUE TITLE
Allow @GrpcClient on parameters of @Bean methods

### ISSUE THREAD

**Issue by justinrlle** [yidongnan/grpc-spring-boot-starter#463]
**The problem**

We have a lib which is not tied to spring, exposing a class which needs a stub to be passed as a parameter. What I'd like is to use all the goodness from this lib when using the both of them. Right now this is more or less how I do it:
```java
@Bean
public NonSpringClient configNonSpringClient(@Value("${custom.path.to.grpc.address}") String address, @Value("${custom.path.to.grpc.port}") int port) {
    ManagedChannel channel = ManagedChannelBuilder.forAddress(address, port)
        .usePlaintext()
        .intercept(/* list of interceptors repeated from StubTransformer */)
        .build();
    MyGrpcServiceBlockingStub stub = MyGrpcService.newBlockingStub(channel);
    return new NonSpringClient(stub);
}
```
But I loose all the benefits from using `@GrpcClient`.

All in all, this is not blocking, but it would be really cool and more flexible if we could use `@GrpcClient` at the same places you can put a `@Value`, for example.

**The solution**

I want to be able to write the following:
```java
@Bean
public NonSpringClient configNonSpringClient(@GrpcClient("MY_STUB") MyGrpcServiceBlockingStub stub) {
    return new NonSpringClient(stub);
}
```
**Alternatives considered**

I'm not sure if what I'm asking is even possible, one alternative would be to give programmatic access to the stubs through an injectable class, something like:
```java
@Bean
public NonSpringClient configNonSpringClient(GrpcStubInjector injector) {
    return new NonSpringClient(injector.getStub("MY_STUB"));
}
```

**Comment by ST-DDT** [comment]
> **The solution**
> 
> I want to be able to write the following:
> 
> ```java
> @Bean
> public NonSpringClient configNonSpringClient(@GrpcClient("MY_STUB") MyGrpcServiceBlockingStub stub) {
>     return new NonSpringClient(stub);
> }
> ```

I would like to support it, unfortunately I'm not sure how. Do you know any spring-library/annotation that supports something like this?
Excluding:
- `@Value`, `@Qualifier` (spring native ones)
- `@RequestParam`, ... (spring controller ones)

> **Alternatives considered**
> 
> I'm not sure if what I'm asking is even possible, one alternative would be to give programmatic access to the stubs through an injectable class, something like:
> 
> ```java
> @Bean
> public NonSpringClient configNonSpringClient(GrpcStubInjector injector) {
>     return new NonSpringClient(injector.getStub("MY_STUB"));
> }
> ```

Sounds like a good alternative. Although I'm not sure whether I should add these methods to the `GrpcClientBeanPostProcessor` or a different class/interface.

The method definitions would probably look similar to the following:

- `<T extends AbstractStub<T>> createStub(String clientName, Class<T> stubType)`
- `<T extends AbstractStub<T>> createStub(GrpcClient clientAnnotation, Class<T> stubType)`

Another easy alternative is the following setup:

````java
@Configuration
public class MyCustomGrpcBean {

    @GrpcClient("client")
    private MyStub myStub;

    @Bean
    MyExternalBean myExternalBean() {
        return new MyExternalBean(myStub);
    }

}
````

**Comment by justinrlle** [comment]
> Another easy alternative is the following setup:
> 
> ```java
> @Configuration
> public class MyCustomGrpcBean {
> 
>     @GrpcClient("client")
>     private MyStub myStub;
> 
>     @Bean
>     MyExternalBean myExternalBean() {
>         return new MyExternalBean(myStub);
>     }
> 
> }
> ```

That's a really nice idea, it does everything I want, I hadn't thought about it! Thank you a lot!
Do you mind if I add this as an example to the docs?

> Do you know any spring-library/annotation that supports something like this?

Unfortunately, I can't think of any right now... On the other side, the other two solutions (using `GrpClient` inside a `@Configuration` class and having some sort of `GrpcClientInjector`) would totally be enough for our needs.

> Although I'm not sure whether I should add these methods to the `GrpcClientBeanPostProcessor` or a different class/interface.
> 
> The method definitions would probably look similar to the following:
> 
> * `<T extends AbstractStub<T>> createStub(String clientName, Class<T> stubType)`
> * `<T extends AbstractStub<T>> createStub(GrpcClient clientAnnotation, Class<T> stubType)`

My take would be to have a `GrpcClientInjector`/`Creator` which would have all the code of `GrpcClientBeanPostProcessor#processInjectionPoint` without the reflection part, and `GrpcClientBeanPostProcessor` would simply call it.
I would totally be fine with the method definitions.

**Comment by ST-DDT** [comment]
> Do you mind if I add this as an example to the docs?

Contributions are always welcome. 👍 

> On the other side, the other two solutions (using `GrpClient` inside a `@Configuration` class and having some sort of `GrpcClientInjector`) would totally be enough for our needs.
> 
> My take would be to have a `GrpcClientInjector`/`Creator` which would have all the code of `GrpcClientBeanPostProcessor#processInjectionPoint` without the reflection part, and `GrpcClientBeanPostProcessor` would simply call it.

Sounds good to me. Do you wish to PR this as well?

**Comment by ST-DDT** [comment]
Any news on this one?

**Comment by justinrlle** [comment]
Sorry for not following up, I've started a branch back in december, but never got to finish it because your advice of using `@GrpcClient` in a `@Configuration` class worked really well for us. I'll still try to add that pattern to the doc, given how useful it was for us, but I don't think I'll find the time to do the other things we discussed here.
