### ISSUE TITLE
Update to spring-boot 2.4.x

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#469]
We should update to spring-boot `v2.4.x`.

There are no know incompatibilities between this library and spring-boot `v2.4.x` yet.

**Comment by bartq17** [comment]
Actually `net.devh.boot.grpc.common.autoconfigure.GrpcCommonTraceAutoConfiguration` relies on `TraceAutoConfiguration` that was renamed in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1784 and no longer exist. It raises `java.lang.ClassNotFoundException: org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration` when trying to run Spring App. 

We tried to upgrade spring boot `2.3.6.RELEASE` -> `2.4.x` and spring-cloud `Hoxton.SR9` -> `2020.0.x` but it's incompatible with `2.10.1-RELEASE` that still has dependency to `2.3.3.RELEASE`.

Are there any plans for an update to 2.4.x?

**Comment by ST-DDT** [comment]
Yes, shortly after the release of 2.11.0 (soon). I will release 2.12.0 which will be mostly a spring update.

**Comment by genuss** [comment]
@ST-DDT Are you interested in contribution of this update? I myself am interested in updating to newer spring boot and only this starter left incompatible, so I could do that.

**Comment by ST-DDT** [comment]
PRs are always welcome.

**Comment by genuss** [comment]
Just created one #508
