### ISSUE TITLE
What is the difference to LogNet's grpc-spring-boot-starter ?

### ISSUE THREAD

**Issue by MartinX3** [yidongnan/grpc-spring-boot-starter#48]
What is the difference to https://github.com/LogNet/grpc-spring-boot-starter ?

**Comment by yidongnan** [comment]
@MartinX3 You can see [features](https://github.com/yidongnan/grpc-spring-boot-starter#features ) and [examples](https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples)

**Comment by MartinX3** [comment]
Ah, you only support gRPC 1.3.0, while the other project supports 1.5.0

**Comment by yidongnan** [comment]
@MartinX3  The dependent version will be upgraded recently

**Comment by MartinX3** [comment]
@yidongnan So when will you upgrade from 1.3.0 to 1.5.0 or better 1.6.0? :)
