### ISSUE TITLE
publishPercentiles for grpc_server_processing_duration metric

### ISSUE THREAD

**Issue by voksiv** [yidongnan/grpc-spring-boot-starter#480]
**The problem**

When I start to configure project monitoring, I found that you already implement it with spring actuator, and metrics collected and send with [micrometer](https://micrometer.io/). But when I try to find opportunity to enable [histograms and percentiles](https://micrometer.io/docs/concepts#_histograms_and_percentiles) for grpc_server_processing_duration metric, I found that there is no opportunity to make something like this:

Timer.builder("my.timer")
   .publishPercentiles(0.5, 0.95) // median and 95th percentile
   .publishPercentileHistogram()
   .sla(Duration.ofMillis(100))
   .minimumExpectedValue(Duration.ofMillis(1))
   .maximumExpectedValue(Duration.ofSeconds(10))

Because you prepare timer [here](https://github.com/yidongnan/grpc-spring-boot-starter/blob/f6f3b053f825d79f0406e61f3dcade24d037833b/grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/MetricUtils.java#L64) and as I didn't find opportunity to configure it.  

**The solution**

I want opportunity to get full control of Timer initialization for  grpc_server_processing_duration metric via bean configuration.

**Alternatives considered**

Now my alternative to disable all your grpc metrics and implement custom micrometer Timer Meter in my app.

**Comment by ST-DDT** [comment]
You can modify them via constructor

https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerInterceptor.java#L77

````java
@Bean
MetricCollectingServerInterceptor metricCollectingServerInterceptor(MeterRegistry registry) {
    return new MetricCollectingServerInterceptor(registry, 
        counter -> counter, 
        timer -> timer.publishPercentiles(0.5, 0.95) // median and 95th percentile
                .publishPercentileHistogram()
                .sla(Duration.ofMillis(100))
                .minimumExpectedValue(Duration.ofMillis(1))
                .maximumExpectedValue(Duration.ofSeconds(10)));
````

**Comment by ST-DDT** [comment]
I assume this answers your question. If not, feel free to ask again.
