### ISSUE TITLE
Spring Data JPA support

### ISSUE THREAD

**Issue by WeiTangLau** [yidongnan/grpc-spring-boot-starter#482]
Does the library support Spring Data JPA? 

For example, annotating the generated java files with @Entity annotations.

If Spring Data JPA is not supported, what is the recommended work around for this?

Thanks in advance!

**Comment by ST-DDT** [comment]
This library is totally unrelated to Spring Data JPA.

If your question is related to the generated protobuf classes, then you should ask that question in the protobuf repository.
https://github.com/protocolbuffers/protobuf/issues/4635

So as a workaround, you could create your custom protoc plugin that creates companion classes that are designed and annotated for the use of jpa.

````java
@Entity("FooBar")
public class FooBarEntity {

    @Id
    private long id;

    public static FooBarEntity fromProto(FooBar proto) { [...] }

    public FooBar toProto() { [...] }

    public static FooBar toProto(FooBar proto) { [...] }

}
````

Another alternative is to not rely on the protoc generated code at all.

Does this help with your question?

**Comment by WeiTangLau** [comment]
@ST-DDT thanks for the feedback! It was very informative! 
If I do not rely on protoc generated code, how do I send request / response over to the other side of the communication?

**Comment by ST-DDT** [comment]
I don't know much about that, all I can tell is that the relevant implementation is "hidden" in the generated `___Grpc.___ImpleBase` class or more specifically in the [`#bindService`](https://grpc.github.io/grpc-java/javadoc/io/grpc/BindableService.html#bindService--) method. AFAICT all you have to do, is (re-)implement that method yourself. If you need more information about that you should ask this question over at grpc-java or SO.
