### ISSUE TITLE
Release v2.11.0

### ISSUE THREAD

**Issue by anjeyy** [yidongnan/grpc-spring-boot-starter#483]
Hi,

i was wondering when a new release is coming, since i could not find any hints to when releases are happening.
Is it actually when all linked issues are done for the 2.11 Milestone?

Kind regards

**Comment by ST-DDT** [comment]
> Is it actually when all linked issues are done for the 2.11 Milestone?

Yes. Currently I'm quite busy with work, so I have to reduce the time I spend on this project.
If you need a release urgently, then we could potentially speed things a bit up/drop some features.

**Comment by anjeyy** [comment]
I'll talk to my team and see how urgent it is. 

In what time framework does it mean speeding things up?

**Comment by ST-DDT** [comment]
I need at least till the end of January to finish some more tasks. So we might be able to release in early February.

**Comment by fee1good** [comment]
@ST-DDT really waiting for Exception Handling feature :)

**Comment by anjeyy** [comment]
@ST-DDT Would be really nice for an early februar release, since we decided to wait for the release so we can switch the starter.

**Comment by ST-DDT** [comment]
I'll try to finish everything up this weekend (proposing the last PRs), so I hope we have a release a few days after.

**Comment by ST-DDT** [comment]
@yidongnan Could you please review and merge #497 and then release `v2.11.0`?

**Comment by yidongnan** [comment]
`v2.11.0` has just been released. I am very sorry that the release was delayed due to the Chinese New Year holiday.
