### ISSUE TITLE
Whether to support ZK

### ISSUE THREAD

**Issue by jiajinhui** [yidongnan/grpc-spring-boot-starter#498]
May I ask, does service discovery now support ZK

**Comment by ST-DDT** [comment]
Should be supported. But I haven't tested it myself.
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataZookeeperConfiguration.java

**Comment by jiajinhui** [comment]
你可以试下吗，我试了下，就是实现了helloword ,server注册不到zk上 ，现在在做技术选型，决定要不要用这个,看到留言，麻烦处理下，谢谢
application.xml配置如下：
![image](https://user-images.githubusercontent.com/33280933/109265167-15454280-7841-11eb-878e-3787cb5d2360.png)
启动类如下：
![image](https://user-images.githubusercontent.com/33280933/109265325-576e8400-7841-11eb-88ea-f8a8801a4d70.png)
service类代码如下：
![image](https://user-images.githubusercontent.com/33280933/109265506-9f8da680-7841-11eb-85e9-ed0cb5bc61c0.png)
pom.xml依赖如下：
![image](https://user-images.githubusercontent.com/33280933/109265649-d82d8000-7841-11eb-8d20-e35d1d85893c.png)
