### ISSUE TITLE
How to use grpc-spring-boot-starter for non-SpringBoot projects

### ISSUE THREAD

**Issue by HSZHJHTP** [yidongnan/grpc-spring-boot-starter#499]
Hello, how do general Spring projects (non-SpringBoot projects) use grpc-spring-boot-starter, which beans need to be manually configured, and are there any examples?

**Comment by ST-DDT** [comment]
For a non spring-boot based setup refer to the beans listed in the `autoconfigure` packages:

https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure
https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure

There are no examples for that (AFAIK).
