### ISSUE TITLE
Doesn't allow to implement Grpc Core framework health.proto for health check

### ISSUE THREAD

**Issue by nehalshah50** [yidongnan/grpc-spring-boot-starter#501]
Following code errors with 
`
Caused by: java.lang.IllegalStateException: Found duplicate service implementation: grpc.health.v1.Health
	at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.configureServices(AbstractGrpcServerFactory.java:127)
`

`
@GrpcService
class HealthCheck : HealthGrpc.HealthImplBase(){

    override fun check(request: HealthCheckRequest, responseObserver: StreamObserver<HealthCheckResponse>) {
        coreLoggingService.Debug("Health Check ...")
        responseObserver.onNext(HealthCheckResponse.newBuilder().setStatus(HealthCheckResponse.ServingStatus.SERVING).build())
        responseObserver.onCompleted()
    }

    override fun watch(request: HealthCheckRequest, responseObserver: StreamObserver<HealthCheckResponse>) {
        coreLoggingService.Debug("Health Check - watch ...")
        responseObserver.onNext(HealthCheckResponse.newBuilder().setStatus(HealthCheckResponse.ServingStatus.SERVING).build())
        responseObserver.onCompleted()
    }
}

`

**Comment by ST-DDT** [comment]
This library currently assumes, that you reuse the existing health service implementation (HealthServiceManager).
It's removal is planned for the next release. See also #411
