### ISSUE TITLE
The identification of the value of the GrpcClient annotation is ambiguous

### ISSUE THREAD

**Issue by s5364733** [yidongnan/grpc-spring-boot-starter#506]
#### Let's take a look at the usage of GrpcClient annotation:<br/>

```java

  /**
     * The name of the grpc client. This name will be used to get the {@link GrpcChannelProperties config options} for
     * this client.
     *
     * <p>
     * <b>Example:</b> <code>@GrpcClient("myClient")</code> &lt;-&gt;
     * {@code grpc.client.myClient.address=static://localhost:9090}
     * </p>
     *
     * <p>
     * <b>Note:</b> This value might also be used to check the common / alternative names in server certificate, you can
     * overwrite this value with the {@link Security security.authorityOverride} property.
     * </p>
     *
     * @return The name of the grpc client.
     */
    String value();


```

>The above shows that the value value is the name of the grpc client, which can be customized

#### But when I was debugging the source code, I found the following code:<br/>

```java
  @Override
    public Channel createChannel(final String name, final List<ClientInterceptor> interceptors,
            boolean sortInterceptors) {
        final URI address = this.properties.getChannel(name).getAddress();
        //todo It is recommended to prompt the PRC address configuration error here
        if (address != null && IN_PROCESS_SCHEME.equals(address.getScheme())) {
            return this.inProcessChannelFactory.createChannel(address.getSchemeSpecificPart(), interceptors,
                    sortInterceptors);
        }
        return this.alternativeChannelFactory.createChannel(name, interceptors, sortInterceptors);
    }

```
>When creating the Channel, it is initialized according to the value of **GrpcChannelsProperties**, but the name field in the first line is defined by the value attribute annotated by GrpcClient, so there will be ambiguity here. For the value attribute annotated by @GrpcClient, it is actually It can only match the grpc.client.local-grpc-server in the **application.yml** file, other values cannot get the address

#### Suggest:<br/>

- The address configured by the user should not be strongly coupled with a certain attribute field

![image](https://user-images.githubusercontent.com/24503935/110301929-a4b5d700-8033-11eb-9b96-f6b51637c467.png)

![image](https://user-images.githubusercontent.com/24503935/110301963-b0a19900-8033-11eb-9227-7cc72a660198.png)

>So the part of the picture above must be **local-grpc-server**

#### There is another problem

-  See the code above todo 

> When the address is null, the compile time can pass, in fact this is a hidden runtime error

![image](https://user-images.githubusercontent.com/24503935/110305236-7e923600-8037-11eb-8245-cee86842572c.png)

![image](https://user-images.githubusercontent.com/24503935/110305201-72a67400-8037-11eb-9e7a-4724818c45bc.png)

```java
at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: 不知道这样的主机。 (myClient)
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 5 more
}
2021-03-08 17:57:23.338  WARN 19436 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<1>: (myClient)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host myClient, cause=java.lang.RuntimeException: java.net.UnknownHostException: myClient
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: myClient
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 5 more
}
2021-03-08 17:57:24.656  WARN 19436 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<1>: (myClient)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host myClient, cause=java.lang.RuntimeException: java.net.UnknownHostException: myClient
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: myClient
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 5 more
}

```

#### My codes : <br/>
```java
    @GrpcClient(value = "myClient", interceptors = LogGrpcInterceptor.class )
    private SimpleBlockingStub simpleStub;
```

**Comment by xieyucan** [comment]
what is your grpc server name ?

**Comment by xieyucan** [comment]
> ### Branch: master
> ### Source: cloud-grpc-client/cloud-grpc-server
> #### Let's take a look at the usage of GrpcClient annotation:
> ```java
>   /**
>      * The name of the grpc client. This name will be used to get the {@link GrpcChannelProperties config options} for
>      * this client.
>      *
>      * <p>
>      * <b>Example:</b> <code>@GrpcClient("myClient")</code> &lt;-&gt;
>      * {@code grpc.client.myClient.address=static://localhost:9090}
>      * </p>
>      *
>      * <p>
>      * <b>Note:</b> This value might also be used to check the common / alternative names in server certificate, you can
>      * overwrite this value with the {@link Security security.authorityOverride} property.
>      * </p>
>      *
>      * @return The name of the grpc client.
>      */
>     String value();
> ```
> 
> > The above shows that the value value is the name of the grpc client, which can be customized
> 
> #### But when I was debugging the source code, I found the following code:
> ```java
>   @Override
>     public Channel createChannel(final String name, final List<ClientInterceptor> interceptors,
>             boolean sortInterceptors) {
>         final URI address = this.properties.getChannel(name).getAddress();
>         //todo It is recommended to prompt the PRC address configuration error here
>         if (address != null && IN_PROCESS_SCHEME.equals(address.getScheme())) {
>             return this.inProcessChannelFactory.createChannel(address.getSchemeSpecificPart(), interceptors,
>                     sortInterceptors);
>         }
>         return this.alternativeChannelFactory.createChannel(name, interceptors, sortInterceptors);
>     }
> ```
> 
> > When creating the Channel, it is initialized according to the value of **GrpcChannelsProperties**, but the name field in the first line is defined by the value attribute annotated by GrpcClient, so there will be ambiguity here. For the value attribute annotated by @GrpcClient, it is actually It can only match the grpc.client.local-grpc-server in the **application.yml** file, other values cannot get the address
> 
> #### Suggest:
> * The address configured by the user should not be strongly coupled with a certain attribute field
> 
> ![image](https://user-images.githubusercontent.com/24503935/110301929-a4b5d700-8033-11eb-9b96-f6b51637c467.png)
> 
> ![image](https://user-images.githubusercontent.com/24503935/110301963-b0a19900-8033-11eb-9227-7cc72a660198.png)
> 
> > So the part of the picture above must be **local-grpc-server**
> 
> #### There is another problem
> * See the code above todo
> 
> > When the address is null, the compile time can pass, in fact this is a hidden runtime error
> 
> ![image](https://user-images.githubusercontent.com/24503935/110305236-7e923600-8037-11eb-8245-cee86842572c.png)
> 
> ![image](https://user-images.githubusercontent.com/24503935/110305201-72a67400-8037-11eb-9e7a-4724818c45bc.png)
> 
> ```java
> at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
> 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
> 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.net.UnknownHostException: 不知道这样的主机。 (myClient)
> 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
> 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
> 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
> 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
> 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
> 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
> 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
> 	... 5 more
> }
> 2021-03-08 17:57:23.338  WARN 19436 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<1>: (myClient)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host myClient, cause=java.lang.RuntimeException: java.net.UnknownHostException: myClient
> 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
> 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
> 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.net.UnknownHostException: myClient
> 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
> 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
> 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
> 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
> 	... 5 more
> }
> 2021-03-08 17:57:24.656  WARN 19436 --- [ault-executor-0] io.grpc.internal.ManagedChannelImpl      : [Channel<1>: (myClient)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host myClient, cause=java.lang.RuntimeException: java.net.UnknownHostException: myClient
> 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
> 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
> 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.net.UnknownHostException: myClient
> 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
> 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
> 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
> 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
> 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
> 	... 5 more
> }
> ```
> 
> #### My codes :
> ```java
>     @GrpcClient(value = "myClient", interceptors = LogGrpcInterceptor.class )
>     private SimpleBlockingStub simpleStub;
> ```

what is your grpc server name ?

**Comment by ST-DDT** [comment]
> When creating the Channel, it is initialized according to the value of GrpcChannelsProperties, but the name field in the first line is defined by the value attribute annotated by GrpcClient, so there will be ambiguity here. For the value attribute annotated by @GrpcClient, it is actually It can only match the grpc.client.local-grpc-server in the application.yml file, other values cannot get the address

`@GrpcClient(value = "myClient")`

=> `myClient` is the name of the client or more specifically the name of the config section that is used to populate that field.

=> `grpc.client.myClient` is the name of the actual config section.

a) `grpc.client.myClient.address=static://mytest:8080`
=> The address to resolve is `static://mytest:8080`

b) `grpc.client.myClient.address=` (not-set)
=> The address to resolve is `myClient` which will be resolved by grpc-java using the default mechanism.
This is behavior is intended to simplify the setup code for services that follow the same naming specification (aka. client-name = service-name).

Is b what you disagree with?

> When the address is null, the compile time can pass, in fact this is a hidden runtime error

The address will default to the name, so this might be unexpected (for you) but not a runtime error.

> My codes :
> 
> ````java
>     @GrpcClient(value = "myClient", interceptors = LogGrpcInterceptor.class )
>     private SimpleBlockingStub simpleStub;
> ````

I assume that you just forgot to alter `myClient` in the code snippet to your actual value `local-grpc-server` and that this mismatch is not the source of your error.

Have you checked, whether the `GrpcChannelsProperties` is actually populated/read?

**Comment by ST-DDT** [comment]
I consider this question answered. If not please feel to leave a comment.
