### ISSUE TITLE
Grpc 1.37?

### ISSUE THREAD

**Issue by SledgeHammer01** [yidongnan/grpc-spring-boot-starter#522]
Hi,

Do you plan to release an update that uses Grpc 1.37?

Thanks!

**Comment by ST-DDT** [comment]
I assume that your are referring https://github.com/grpc/grpc-java/releases/tag/v1.37.0

Yes, I will probably try to include it in the next release.

**Comment by SledgeHammer01** [comment]
> I assume that your are referring https://github.com/grpc/grpc-java/releases/tag/v1.37.0
> 
> Yes, I will probably try to include it in the next release.

Oops. Typo. Fixed :). Yeah, 1.37.
