### ISSUE TITLE
How does grpc work in a multi-k8s cluster

### ISSUE THREAD

**Issue by ZMRWEGO** [yidongnan/grpc-spring-boot-starter#527]
1. The ip and port of grpc registered to the registry are the intranet ip in the cluster and cannot be interacted in multiple k8 clusters
2. Our service belongs to the configuration of three centers in two places, which can be understood as three k8 clusters. Currently, rpc calls are made using http-based apis. Because it is on the 7th layer network, it can be forwarded to the corresponding pod network using routing. grpc works on a 4-layer network. And interact directly through ip+port, how to solve this problem

**Comment by ST-DDT** [comment]
Grpc is Http/2 so it should work similar to a simple http call.
I have used grpc from inside and outside of kubernetes (both with and without routers/ingress) without any issues.
So you can simply configure your cluster/grpc-connection as you would do for http.

The sole difference would be the url-scheme:

`https://service.apps.d.example.com` -> `dns:///service.apps.d.example.com`

**Comment by ZMRWEGO** [comment]
yean  i'll try
