### ISSUE TITLE
Release v2.12.0

### ISSUE THREAD

**Issue by ST-DDT** [yidongnan/grpc-spring-boot-starter#533]
The following issues needs to be reviewed and merged before we can release `v2.12.0`:

* Change metadata from gRPC.port to gRPC_port #496
* Make grpc-services.jar optional + remove grpc health service setup #528

I hope to release the version this month/week. Probably on Apr, 29/30th.

@yidongnan Sorry, to trouble you. I know it's quite sudden, but do you have time for that this week?
If you don't have time, then it doesn't matter much.
We shouldn't lower our standards and omit the reviews for a release.

**Comment by asarkar** [comment]
@ST-DDT thanks for these changes. As the author of https://github.com/yidongnan/grpc-spring-boot-starter/issues/411, I am interested in these changes, and made couple of comments on https://github.com/yidongnan/grpc-spring-boot-starter/pull/528.

**Comment by rafaelargenta-quanto** [comment]
These release will support spring-boot 2.4.x ?

**Comment by ST-DDT** [comment]
Yes, 2.12.0 is primarily intended for use with 2.4.x.
AFAICT it will also work with spring-boot 2.3.x except for some combinations with some cloud/tracing libraries.
Note: 2.11.0 also works with 2.4.x with the same exceptions as above.
(Spring changed a few class names, breaking the compatibility)

**Comment by rafaelargenta-quanto** [comment]
I am very much looking forward to RELEASE-2.12.
Thanks.

**Comment by yidongnan** [comment]
v2.12.0 has just been released.

**Comment by ST-DDT** [comment]
Awesome. Thanks for your time.
