### ISSUE TITLE
Grpcglobalclientinterceptor is invalid. Grpcglobalserverinterceptor is valid 

### ISSUE THREAD

**Issue by qianxunclub** [yidongnan/grpc-spring-boot-starter#541]
**The context**

ClientTransactionInterceptor invalid

```
    @GrpcGlobalClientInterceptor
    public ClientInterceptor clientTransactionInterceptor() {
        return new ClientTransactionInterceptor();
    }

    @GrpcGlobalServerInterceptor
    public ServerInterceptor serverTransactionInterceptor() {
        return new ServerTransactionInterceptor();
    }
```

**The question**

同样的配置，ServerTransactionInterceptor 断点可以进去，ClientTransactionInterceptor 的断点不能进去。

In the same configuration, server transaction interceptor breakpoints can be entered, but client transaction interceptor breakpoints cannot be entered

 Custom Interceptor  is valid 

**Stacktraces and logs**
无

**The application's environment**

Which versions do you use?
* Spring (boot):2.4.1
* grpc-java:1.36.0
* grpc-spring-boot-starter:2.12.0.RELEASE
* seata-spring-boot-starter:1.4.2

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by qianxunclub** [comment]
已经解决了，原因是因为我使用一下方式创建的 channel

```
public Channel channel() {
        return NettyChannelBuilder.forAddress(channelHost, channelPort)
                .disableRetry()
                .usePlaintext()
                .build();
}
```

修改为：

```
public Channel channel() {
        ManagedChannel managedChannel = NettyChannelBuilder.forAddress(channelHost, channelPort)
                .disableRetry()
                .usePlaintext()
                .build();
        final GlobalClientInterceptorRegistry globalClientInterceptorRegistry = ApplicationHelper.get(GlobalClientInterceptorRegistry.class);
        final List<ClientInterceptor> interceptors = Lists.newArrayList(globalClientInterceptorRegistry.getClientInterceptors());
        return ClientInterceptors.interceptForward(managedChannel, interceptors);
}
```

**Comment by ST-DDT** [comment]
[English translation](https://translate.google.com/translate?hl=&sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fissues%2F541)

**Comment by ST-DDT** [comment]
Glad to hear, that the problem was resolved.

Note: You can use `GrpcClient("channelName") Channel channel;` to inject the channel into your beans.
