### ISSUE TITLE
GRPC health check failing in 2.12.0

### ISSUE THREAD

**Issue by steven-sheehy** [yidongnan/grpc-spring-boot-starter#542]
**The context**

Working health checks

**The bug**

Health checks have stopped working in 2.12.0. I assume it is related to PR https://github.com/yidongnan/grpc-spring-boot-starter/pull/528. I figured it was because it was missing the now optional `grpc-services` dependency so I added that. There were no docs or notes in the release notes about that breaking change. After adding that dependency it still does not work.

**Stacktrace and logs**

In 2.11.0:

`curl -s "http://localhost:8081/actuator/health/readiness" | jq`
```json
{
  "status": "UP",
  "components": {
    "db": {
      "status": "UP",
      "details": {
        "database": "PostgreSQL",
        "validationQuery": "isValid()"
      }
    },
    "grpcChannel": {
      "status": "UP"
    },
    "grpcServices": {
      "status": "UP",
      "components": {
        "com.hedera.mirror.api.proto.ConsensusService": {
          "status": "UP"
        }
      }
    },
    "ping": {
      "status": "UP"
    }
  }
}
```
`curl -s "http://localhost:8081/actuator/health/readiness" | jq`
```json
{
  "status": "DOWN",
  "components": {
    "db": {
      "status": "UP",
      "details": {
        "database": "PostgreSQL",
        "validationQuery": "isValid()"
      }
    },
    "grpcChannel": {
      "status": "UP"
    },
    "grpcServices": {
      "status": "DOWN",
      "components": {
        "com.hedera.mirror.api.proto.ConsensusService": {
          "status": "DOWN",
          "details": {
            "error": "io.grpc.StatusException: NOT_FOUND: unknown service com.hedera.mirror.api.proto.ConsensusService"
          }
        },
        "grpc.health.v1.Health": {
          "status": "DOWN",
          "details": {
            "error": "io.grpc.StatusException: NOT_FOUND: unknown service grpc.health.v1.Health"
          }
        },
        "grpc.reflection.v1alpha.ServerReflection": {
          "status": "DOWN",
          "details": {
            "error": "io.grpc.StatusException: NOT_FOUND: unknown service grpc.reflection.v1alpha.ServerReflection"
          }
        }
      }
    }
  }
}
```

**Steps to Reproduce**

curl health checks before and after bumping to 2.12

**The application's environment**

Which versions do you use?
* Spring (boot): 2.4
* grpc-java: 1.37.0
* grpc-spring-boot-starter: 2.12.0
* java: AdoptOpenJDK 11.0.10

**Additional context**

* Did it ever work before? Yes, in 2.11.0
* Do you have a demo? https://github.com/hashgraph/hedera-mirror-node/pull/1912

**Comment by steven-sheehy** [comment]
Thanks for your response. Yes, `GrpcHealthIndicator` was written by us. Its intent is provide a central health status of the grpc services for both the gRPC API and the REST API which provides the readiness/liveness probes to Kubernetes. So if gRPC went to not serving both APIs would show the problem and we didn't have to repeat ourselves. The hope was that this library would maintain that ServingStatus for non-application issues related to gRPC or Netty like shutdown or thread pool exhaustion, etc. Is that even possible? If an application issue occurs then applications would of course be responsible for setting it to something else.

I think the removal of the default status of serving is what caused our problems. I think that this library setting the default value to SERVING made sense since this library is responsible for the opinionated registration of the health service and the application services. It makes sense that on startup services are by default marked as SERVING. It also makes sense that on shutdown it be set to `NOT_SERVING`. It seems right now on shutdown it's calling `HealthStatusManager.clearState()` instead of `HealthStatusManager.enterTerminalState()`. We can workaround this by setting it ourselves, but I did think it made sense for the library to maintain it as it did before.

> Is there a way to change the release notes to make it easier to notice/understand?

Normally when a library removes functionality it denotes it in a separate section and provides possible steps to restore the previous functionality. So perhaps add a `Breaking Changes` section that calls out that the health check service is no longer registered by default and to restore the previous behavior add `io.grpc:grpc-services` to the classpath. Also that all services no longer set their health status to serving by default and to restore previous behavior by manually setting it to SERVING via `HealthStatusManager.setStatus()`

**Comment by ST-DDT** [comment]
What about the application ReadinessState and LivenessState (and their respective events)?
- Should the grpc health service wait for the application to be "ready"?
- Should it consider the liveness somehow as well?
- Should it mark the individual services or the "all" service (empty service name)?
  - If it marks the services each individually, what about the "all" service and vice versa?
  - Whats the benefit of marking individual services as SERVING vs the "all" service, especially if all are set at once to the same value?

**Comment by thomas-cools** [comment]
Wanted to note that I'm having a similar issue - when calling the gRPC health service directly I get this response for 2.12.0
 ```
{
  "error": "5 NOT_FOUND: unknown service proto.RcAmadeusGdsDao"
}
```

2.11.0 and below return `SERVING`

**Comment by ST-DDT** [comment]
Yes, the service is no longer initialized blindly. You may use the empty service name or populate the health checks with useful values.
