### ISSUE TITLE
gRPC statusCode tag should be integer

### ISSUE THREAD

**Issue by asarkar** [yidongnan/grpc-spring-boot-starter#543]
**The problem**

`grpc.*.processing.duration` timers have a tag, `statusCode`, which is the name of enum [Status](https://grpc.github.io/grpc-java/javadoc/io/grpc/Status.html). The name is misleading because the tag value is a string, not an integer code. It is also difficult to use the string value for automated alerts (_raise hell if 75% of calls failed in the last 30 minutes_). There's no easy way to differentiate failed status codes from good ones without complicated regex that many alerting systems don't support.

**The solution**

`statusCode` should be the integer value of the status. Only `0` (`OK`) and `1` (`CANCELLED`) are good statuses, which makes it very easy to find all failed calls (> 1).

Please add a tag `status`, the value of which will be the enum name; change `statusCode` to be the integer value of the enum.

**Alternatives considered**

None exists.

**Comment by ST-DDT** [comment]
[`Status.Code`s](https://grpc.github.io/grpc-java/javadoc/io/grpc/Status.Code.html)

While the naming of the tag might be non optimal, i wont introduce an integer status code.
There are two reasons for that:
- modern monitoring systems are either capable of remapping or checking for multiple values
- string values are easier to understand than magic values and thus easier to maintain (and IMO your definition of hell to let loose seems special to your usecase, I assume that public APIs might choose different status codes and limits for that)
- and most importantly the implementation that is contained in this library will be replaced by the one in micrometer soonish, so the right place to propose this would be over there. Please ping me if you do so.

**Comment by asarkar** [comment]
> and most importantly the implementation that is contained in this library will be replaced by the one in micrometer soonish

Not sure why you expect me to let you know of something that you claim to know already. Is there a Micrometer ticket you’re referring to?

**Comment by ST-DDT** [comment]
> > and most importantly the implementation that is contained in this library will be replaced by the one in micrometer soonish
> 
> Not sure why you expect me to let you know of something that you claim to know already. Is there a Micrometer ticket you’re referring to?

https://github.com/micrometer-metrics/micrometer/pull/2323
I almost forgot about it. Thanks for reminding me.
The migration will be tracked here:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/544

> > modern monitoring systems are either capable of remapping or checking for multiple values
> 
> Pretty sure I covered this already in the problem description. Do you’ve a concrete example of a query from any modern monitoring system that could show just failed calls?

`rate(grpc_server_processing_duration_count{statusCode=~"OK|CANCELLED"}[30m] / rate(grpc_server_processing_duration_count[30m]) < 0.25`

This syntax is used by prometheus/grafana. But I usually wouldn't monitor it like that.
I assume other monitoring systems such as Zabbix... have similiar features.

**Comment by asarkar** [comment]
> rate(grpc_server_processing_duration_count{statusCode=~"OK|CANCELLED"}[30m] / rate(grpc_server_processing_duration_count[30m]) < 0.25
>
> This syntax is used by prometheus/grafana. 

This syntax is invalid for Grafana when using graphite database, which is a modern system and no less popular than Prometheus. See https://stackoverflow.com/a/19506794/839733 for details of what's supported by Graphite, which isn't much.

**Comment by ST-DDT** [comment]
Sorry, but I cannot help you with that.
Please search for the proper syntax for your chosen system yourself.
The online documentation or SO can probably help you way better with that setup than I currently can.
If such a feature is not supported by that system, you should consider using one, that offers what you need.

**Comment by asarkar** [comment]
> Please search for the proper syntax for your chosen system yourself.

I've already done the research, and posted the link above, and not asking for help on that. It goes to show that your earlier comment "_modern monitoring systems are either capable of remapping or checking for multiple values_" isn't true, so this ticket was closed prematurely on invalid grounds.

That said, I understand OSS doesn't come with any guarantees, so I'm going to find a way around without support from the library. Thanks.
