### ISSUE TITLE
How to serve static content?

### ISSUE THREAD

**Issue by thomas174** [yidongnan/grpc-spring-boot-starter#546]
**The context**

I want to serve static content like a HTML documentation of the gRPC API.

**The question**

How does it work? What is the best way to implement this?

**Stacktraces and logs**

Putting the HTML file into the `/resources/static` folder didn´t work.

```batch
curl --http2 http://localhost:9090/index.html  
curl: (1) Unsupported protocol
```

**The application's environment**

Which versions do you use?
* Spring (boot): 2.4.5
* grpc-spring-boot-starter: 2.11.0.RELEASE

**Comment by ST-DDT** [comment]
Currently grpc-netty does not provide access to netty (AFAICT) and thus it is not possible to serve static content via "plain HTTP".
If you are still interested in this, feel free to open a new issue over at grpc-java and ask for a how to.
If you post a link here/or already know how to do it maybe we can integrate it here somehow if there is common interest in that feature.
