### ISSUE TITLE
making the client stub *final*  does not work?

### ISSUE THREAD

**Issue by sherlock-ma** [yidongnan/grpc-spring-boot-starter#547]
**The context**

Sample code is shown here.
```java
@Service
@RequiredArgsConstructor
public class GrpcClientService {
    @GrpcClient("client-test")
    private ServiceGrpc.ServiceBlockingStub stub;

    // methods using the stub to fulfill its service.
}
```

**The question**

I find that if I make the `stub` final, then on application startup, Springboot will complain that it didn't find the bean type "ServiceGrpc.ServiceBlockingStub". The error message is something similar as follows.

Parameter 0 of constructor in GrpcClientService required a bean of type 'ServiceGrpc$ServiceBlockingStub' that could not be found.

But if I remove the "final" qualifier, everything goes back to normal and the service works. Why is this? I guess making every possible field, variables final is good java practice. 

**The cause I guess**
The cause of it I guess is that the stub is not injected via constructors so it cannot be made "final", because if I remove the "final" qualifier and replace `@RequiredArgsConstructor` with `@AllArgsConstructor` , the startup fails as well with the same error message.

FYI, [`@RequiredArgsConstructor` creates a constructor for all non-initialized final fields whereas `@AllArgsConstructor` creates a constructor for all fields.](https://projectlombok.org/features/constructor)

**Comment by ST-DDT** [comment]
The issue here is that spring does not support annotation controlled injection.
Thus, the `@GrpcClient` fields cannot be set via constructor directly.
You can however expose them as a bean. That circumvents the issue.

````java
@Configuration
public class StubConfig {

    @GrpcClient("foobar")
    FoobarStub foobarStub;

    @Bean
    FoobarStub foobarStub() {
        return foobarStub;
    }

}
````

````java
@Component
public class MyService {

    private final FoobarStub foobarStub;

    public MyService(FoobarStub foobarStub) {
        this.foobarStub = foobarStub;
    }

[...]

}
````

I'll add this example to the docs, when I have some free time.

**Comment by sherlock-ma** [comment]
Oh that makes sense! Also this is a great example. Thanks

From: ST-DDT ***@***.***>
Date: 2021-05-25 21:33:17
To: yidongnan/grpc-spring-boot-starter ***@***.***>
Cc: Sherlock Ma ***@***.***>,Author ***@***.***>
Subject: Re: [yidongnan/grpc-spring-boot-starter] making the client stub *final* does not work? (#547)

The issue here is that spring does not support annotation controlled injection.
 Thus, the @GrpcClient fields cannot be set via constructor directly.
 You can however expose them as a bean. That circumvents the issue.
@Configuration
public class StubConfig {

    @GrpcClient("foobar")
    FoobarStub foobarStub;

    @Bean
    FoobarStub foobarStub() {
        return foobarStub;
    }

}
@Component
public class MyService {

    private final FoobarStub foobarStub;

    public MyService(FoobarStub foobarStub) {
        this.foobarStub = foobarStub;
    }

[...]

}
I'll add this example to the docs, when I have some free time.

**Comment by ST-DDT** [comment]
This now possible using [`@GrpClientBean`s](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#grpcclientbean)
