### ISSUE TITLE
 how to get tracing span in istio / kubernetes?

### ISSUE THREAD

**Issue by nikitaChernyshev** [yidongnan/grpc-spring-boot-starter#553]
**The context**

I want to receive tracing span between my microservices, how can I send tracing spans to istio?
Is there an example showing how this is done?

**The question**

I know grpc-spring-boot-starter supports micrometer / actuator.
Now i am getting separate metrics of each request without parent id incoming request.
my question in StackOverFlow: https://stackoverflow.com/questions/67739222/i-am-trying-to-pass-the-metric-of-a-grpc-protocol-to-kubernetes-istio-i-am-usin

**Stacktraces and logs**

I tried to set up brave, but every time I pull up the dependency, my application crashes
`Could not find class [org.springframework.cloud.sleuth.autoconfig.brave.BraveAutoConfiguration]`

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.1
* grpc-spring-boot-starter: 2.12.0.RELEASE
* java: 11

**Additional information**

my code in github:
https://github.com/nikita111100/gRPC-vs-REST

**Comment by VladislavShamshurin** [comment]
You a russian bitches! Fuck OFF IDIOT!!!!

**Comment by ST-DDT** [comment]
> I want to receive tracing span between my microservices, how can I send tracing spans to istio?

I'm not familiar with istio's supposted workflow for that, but I assume, that you have to explicitly add the tracing/spawn id to the requests you are creating (using an interceptor).

Maybe you need set up to this dependency: https://github.com/opentracing-contrib/java-grpc

````java
@Configuration
public class TracingConfig {

    @GrpcGlobalClientInterceptor
    TracingClientInterceptor tracingInterceptor(Tracer tracer) {
        return TracingClientInterceptor
                .newBuilder()
                .withTracer(tracer)
                .build();
    }

}
````

Maybe I can automatically setup the required beans for that in a future release.

> I tried to set up brave, but every time I pull up the dependency, my application crashes
> `Could not find class [org.springframework.cloud.sleuth.autoconfig.brave.BraveAutoConfiguration]`

Which version of spring-cloud are you using? (Are you using Hoxton or the 2020+ release train?)
https://github.com/spring-cloud/spring-cloud-release/releases
grpc-spring-boot-starter <= 2.11 is compatible with <= Hoxton
grpc-spring-boot-starter >= 2.12 is compatible with >= 2020

( I definitely need to update the README 😳 )

**Comment by nikita111100** [comment]
thank you, it works for me
