### ISSUE TITLE
How to propagate headers with Spring Cloud Sleuth?

### ISSUE THREAD

**Issue by nikita111100** [yidongnan/grpc-spring-boot-starter#554]
**The context**
I want to propagate headers use gRPC and spring cloud sleuth.

**In Spring cloud sleuth documentation said**
Spring Cloud Sleuth provides instrumentation for gRPC via the Brave tracer. You can disable it entirely by setting spring.sleuth.grpc.enabled to false.

**The bug**

Now tracing doesn't work for me 
Maybe I need to configure a bin?
Do you have instructions for starting tracing with spring cloud sleuth? :)

**Stacktrace and logs**

2021-06-09 11:08:03.814  INFO [grpc-service,,] 8 --- [ool-1-thread-19] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary
2021-06-09 11:08:03.824  INFO [grpc-service,,] 8 --- [pool-1-thread-3] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary
2021-06-09 11:08:03.832  INFO [grpc-service,,] 8 --- [pool-1-thread-6] c.vinsguru.square.service.MyGrpcService  : call findSquareUnary

**The application's environment**

* Spring (boot): 2.5.0
* grpc-spring-boot-starter: 2.12.0 REAEASE 
* java: 11
* Spring-cloud-starter-sleuth: 3.0.3

**My example code**
[https://github.com/nikita111100/gRPC-vs-REST/tree/main/aggregator-service](url)

**Comment by ST-DDT** [comment]
Please check whether these beans are created/used:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientTraceAutoConfiguration.java#L51
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerTraceAutoConfiguration.java#L51
