### ISSUE TITLE
Not able to find how to create access logs

### ISSUE THREAD

**Issue by vikrantch-hk** [yidongnan/grpc-spring-boot-starter#556]
**The context**

how to create access logs?

**The question**

There is no documentation around it also I did not find any straight forward answer on SO so opening a bug.

**The application's environment**

Which versions do you use?
* Spring (boot): 2.1.5.RELEASE
* grpc-spring-boot-starter: 2.12.0.RELEASE

**Comment by ST-DDT** [comment]
There are three potential ways to do this.

- Log it in each request (not recommended)
- Log it using a `ServerInterceptor` (similar to a ServletFilter)
- Log it using the `AuthenticationManager`

-------------------

ServerInterceptor:

The authenticaiton is set in [DefaultAuthenticatingServerInterceptor](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/DefaultAuthenticatingServerInterceptor.java), so you can add your interceptor after it.

````java
public class PostAuthenticationContextSniffer implements ServerInterceptor {

    interceptCall(ServerCall call, X x) {
		SecurityContext context = SecurityContextHolder.getContext();
		sysout(context.getAuthentication());
		try {
        	return x.startCall();
		}
    }

}
````

-------------------

AuthenticationManager:

````java
Authentication authenticate(Authentication request) {
    Authentication auth = delegate.authenticate(request);
    sysout(auth);
    return auth;
}
````

**Comment by ST-DDT** [comment]
Might be related to: https://github.com/yidongnan/grpc-spring-boot-starter/issues/462

**Comment by vikrantch-hk** [comment]
@ST-DDT thanks for quick revert, I want to do it more in spring way using somewhat similar configuration. In below commit they are doing similar thing for reactive netty. Do you think it's better to extend `ServerInterceptor` or in spring way `ChannelDuplexHandler` 

https://github.com/reactor/reactor-netty/commit/e26831e0ee567f39313fb9741bb761e145cb298e

**Comment by ST-DDT** [comment]
I have never heart of `ChannelDuplexHandler` yet, and it doesn't seem to be a spring class either.
I'm not sure how we can customize netty as used by grpc to use that handler, so IMO it is easier to use the ServerInterceptor.

**Comment by vikrantch-hk** [comment]
@ST-DDT `ChannelDuplexHandler` belongs to `netty.shaded` in given commit Spring has added `AccessLogHandler extends ChannelDuplexHandler` please have a look at this commit https://github.com/reactor/reactor-netty/commit/e26831e0ee567f39313fb9741bb761e145cb298e

**Comment by ST-DDT** [comment]
I haven't found a way to add any of these to the netty server so you might have to ask the question how to integrate that directly add grpc-java.

There might be no way to do that in grpc java so your only options might be those listed here:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/556#issuecomment-860547899

If there is a way, please tell us/drop a link here for future reference.
