### ISSUE TITLE
Anyway to use etcd as service discovery with grpc-spring-boot-starter?

### ISSUE THREAD

**Issue by NeonCowboy** [yidongnan/grpc-spring-boot-starter#557]
**The context**

We are using etcd as the service discovery, so we can grpc request to exsiting Go applications.

**The question**

Is there any way to use etcd as service discovery? Because spring-cloud-etcd is out of maintenance, so is there any other way round?

**Comment by ST-DDT** [comment]
Apart from implementing the required discovery client yourself? Unfortunately none that I am aware of.

Is there a pure java etcd client lib, maybe all you have to do is wrap it with the DiscoveryClient interface..

**Comment by NeonCowboy** [comment]
Thanks for your reply! 
I am just a newbee to grpc and etcd. So is there a way that I can use [jetcd](https://github.com/etcd-io/jetcd) to get client ips and ports, then I can choose one to create channel to make grpc request with grpc-spring-boot-starter lib?

**Comment by ST-DDT** [comment]
I searched for a bit and found this impl:

https://github.com/schmohlio/grpc-etcd-java/tree/master/grpc-etcd-java/src/main/java/io/schmohl/grpc/resolvers/etcd

It doesnt use that library, but might work out of the box. I'm not familiar with that library and havent tested it. After a short look, there seems to be some issues regarding how to synchronize the listener. So you might have to edit it a bit.

If you wish to implement it yourself, then I suggest to base your implementation on our existing ones:

https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver

**Comment by NeonCowboy** [comment]
Sorry for late reply.
So if I want to integrate etcd discovery with grpc-spring-boot-starter, I need to implement a discovery client like Nacos or Eureka, right? So is there anyway to do that? Maybe give me some example, so I can try to implement it. After that maybe this project can natively support etcd?

**Comment by ST-DDT** [comment]
> So is there anyway to do that? Maybe give me some example, so I can try to implement it.

See my links above for implementing only the name resolvers. If you wish to implement the entire discovery client, then the out of maintainance spring etcd lib should contain all you need.
