### ISSUE TITLE
How to setup deadline with spring boot properties

### ISSUE THREAD

**Issue by Owenxh** [yidongnan/grpc-spring-boot-starter#559]
How to setup deadline with spring boot properties?

**Comment by ST-DDT** [comment]
Just like with plain grpc-java: https://github.com/grpc/grpc-java/issues/1495

````java
@GrpcClient("foobar")
MyBlockingStub blockingStub;

blockingStub.withDeadlineAfter(3, TimeUnit.SECONDS).doSomething();
````

I haven't found a way to apply a default deadline to all new calls/stubs.
