### ISSUE TITLE
How to recreate channel ? 

### ISSUE THREAD

**Issue by tangjizhou** [yidongnan/grpc-spring-boot-starter#560]
hi , My service cannot be restarted or restart frequently while running ,  what can i do to recreate a channel dynamically ? i updated the channel properties  , but not working , then i check the code , and found no access to this field .    PS:   Forgive my poor english  - - ||

`channel = this.channels.computeIfAbsent(name, this::newManagedChannel);`  

https://github.com/yidongnan/grpc-spring-boot-starter/blob/3e4deca041bb6a8e54e014db0c66b96e0cb4d38f/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/AbstractChannelFactory.java#L108

**Comment by ST-DDT** [comment]
Currently the channels are cached after being created once. So they wont be updated with later config changes.

Which properties do you wish to change and why?

**Comment by tangjizhou** [comment]
`this.channels` in `AbstractChannelFactory.java ` ,  for purpose of updating the channel properties , such as the URI.

 Our service belongs to the field "CIM" , so it can't be restart while running ,  which could cause other requests failed and materials scrapped . but we can shutdown one equipment for maintenance, such as changing the  address of gRPC server or replacing some components.

**Comment by ST-DDT** [comment]
This sounds like you need a discovery service such as eureka, nacos, consul etc.
If you dont wish to use such tools then you can still implement the name resolution yourself.
https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver
Just implement a nameresolver + factory yourself and you dont even have to recreate the channels/stubs. They will automatically be updated to use the latest address.

**Comment by tangjizhou** [comment]
worked , thanks .  0.0
