### ISSUE TITLE
merge registered GrpcMetadataXXXConfiguration

### ISSUE THREAD

**Issue by Cczzzz** [yidongnan/grpc-spring-boot-starter#564]
I see has a lot of GrpcMetadataXXXConfiguration for different Registry.
But they are all to one xxxRegistration add the metadata.
These  inherit org.springframework.cloud.client.ServiceInstance.
We can treat them all as org.springframework.cloud.client.ServiceInstance ，and call ServiceInstance#getMetadata().
And org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration auto register at startup will send InstancePreRegisteredEvent befor register.
InstancePreRegisteredEvent will contain  R extends Registration  .we can use this add metadata to Registration.
Please forgive my bad english.

**Comment by Cczzzz** [comment]
`
@Configuration(proxyBeanMethods = false)
@EnableConfigurationProperties
@ConditionalOnClass({Registration.class})
public class GrpcMetadataConfiguration {

    @Autowired
    private GrpcServerProperties grpcProperties;

    @EventListener(InstancePreRegisteredEvent.class)
    public void beforeRegistered(InstancePreRegisteredEvent event){
        Registration registration = event.getRegistration();
        if (registration != null) {
            final int port = grpcProperties.getPort();
            if (GrpcUtils.INTER_PROCESS_DISABLE != port) {
                registration.getMetadata()
                        .put(GrpcUtils.CLOUD_DISCOVERY_METADATA_PORT, Integer.toString(port));
            }
        }

    }

}
`

**Comment by ST-DDT** [comment]
Seems useful to me. Would you like to create a PR for it?

**Comment by Cczzzz** [comment]
> Seems useful to me. Would you like to create a PR for it?

i will  create a PR for it

**Comment by ST-DDT** [comment]
There is already a PR so I will close this issue
