### ISSUE TITLE
How to run junit test concurrently using spring boot application with grpc spring boot starter

### ISSUE THREAD

**Issue by begemot63** [yidongnan/grpc-spring-boot-starter#565]
**The context**

What do you wish to achieve? 
 concurrently running junit testing without message port is already used

**The question**

 
1. I have these annotations for spring  boot application :

````java
    @DirtiesContext
    @ExtendWith(SpringExtension.class)
    @SpringBootTest(
            classes = {MyApplication.class},
            webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
            properties = {
                    "grpc.server.inProcessName=test",// Enable inProcess server
                    "grpc.server.port=-1", // Disable external server
                    "grpc.client.inProcess.address=in-process:test" // Configure the client to connect to the inProcess server
            })
````

my application.yaml has these settings :

````yaml
    grpc:
      server:
        port:  6565
````

Sometimes my junitest (which run concurrently) failed because 6565 port is already used.
What do I need to do to avoid it?

2. Can you clarify when I need to use the option shown below and when I should not.
`grpc.server.port=-1`
 
 

**Stacktraces and logs**

 Getting 6565 port is already used 

**The application's environment**

Which versions do you use?
* Spring (boot):            '2.3.4.RELEASE'
* grpc  protocVersion    : '3.12.3'
* grpc-spring-boot-starter: 2 .10.1.RELEASE
* java: version + architecture (64bit?) Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
* Other relevant libraries...

**Additional information**

**Comment by ST-DDT** [comment]
Sorry for the late response. I have been on vacation.

Please check why the grpc server is created.
You can do this by checking any of these beans:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java#L66

The `shadedNettyGrpcServerFactory` and `nettyGrpcServerFactory` beans should not be created.

**Comment by begemot63** [comment]
Hi
Thanks for your response.
I think the is related to the port which needs to be set to 0

**Comment by ST-DDT** [comment]
`grpc.server.port=-1` should turn the port based server off, so its better to use `-1` than `0` if you don't need to access the port. So the main question should be, why it isn't turned off. Hence the debugging into the bean creation.

**Comment by begemot63** [comment]
If I need to use grpc I need to access the server and so the grcp port
should be always available.
The value grpc.server.port=0 is much more clear if it means to set a random
port for testing purposes.
Thus option grpc.server.port=-1  looks very strange. Please elaborate when
it is used with grpc called. Please give running example when -1 value is
not ignored but used

**Comment by ST-DDT** [comment]
`0`  =>  random
`-1` => disabled

JUnit-Test: [`OnlyInProcessServerTest`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/setup/OnlyInProcessServerTest.java#L59)
