### ISSUE TITLE
exclude grpc server on unit-test

### ISSUE THREAD

**Issue by c2hy** [yidongnan/grpc-spring-boot-starter#572]
**The problem**

**The solution**

**Alternatives considered**

**Additional context**

**Comment by ST-DDT** [comment]
Please provide the requested information, as I am unable to understand your intentions.

**Comment by c2hy** [comment]
When I test, I don't want server to enable. Can I have a parameter that controls enable ?

发送自 Windows 10 版邮件应用

发件人: ST-DDT
发送时间: 2021年8月5日 21:22
收件人: yidongnan/grpc-spring-boot-starter
抄送: Lano; Author
主题: Re: [yidongnan/grpc-spring-boot-starter] exclude grpc server onunit-test (#572)

Please provide the requested information, as I am unable to understand your intentions.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ST-DDT** [comment]
`grpc.server.port=-1`

https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java#L66

**Comment by c2hy** [comment]
Thks

发送自 Windows 10 版邮件应用

发件人: ST-DDT
发送时间: 2021年8月6日 23:45
主题: Re: [yidongnan/grpc-spring-boot-starter] exclude grpc server onunit-test (#572)

grpc.server.port=-1
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java#L66
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
