### ISSUE TITLE
 如何通过grpc-spring-boot-starter设置重试相关的配置，目前不提供这样的功能吗？

### ISSUE THREAD

**Issue by wushengju** [yidongnan/grpc-spring-boot-starter#573]
**The context**

What do you wish to achieve?

**The question**

What's the problem? What's not working? What's missing and why do you need it?

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot):
* grpc-java:
* grpc-spring-boot-starter:
* java: version + architecture (64bit?)
* Other relevant libraries...

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment]
[English](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://github.com/yidongnan/grpc-spring-boot-starter/issues/573)

This library does not provide any additional logic related to retry.
Please use either grpc's or third-party's retry library code.

Currently there are no plans to add additional retry code to this library.
If you would like to have some specific properties to setup the grpc retry, then please request them more specificly. PRs are always welcome.
