### ISSUE TITLE
服务端感知客户端断开连接

### ISSUE THREAD

**Issue by celityowce** [yidongnan/grpc-spring-boot-starter#576]
客户端发起流连接，服务端保持连接对象，如果客户端应用停用或者网络中断，服务端如何才能主动感知到

**Comment by ST-DDT** [comment]
[English translation](https://translate.google.com/translate?sl=zh-CN&tl=en&u=https://github.com/yidongnan/grpc-spring-boot-starter/issues/576)

----------------------

The call will get cancelled eventually, so you have to set a cancellation listener:
[ServerCallStreamObserver#setOnCancelHandler(...)](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html#setOnCancelHandler-java.lang.Runnable-) (IIRC this requires a cast for the given `StreamObserver<X> responseObserver`)

As an alternative you could use [Context#addListener(...)](https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.html#addListener-io.grpc.Context.CancellationListener-java.util.concurrent.Executor-) to achieve the same.

````java
    @Override
    public void watch(Empty request, StreamObserver<Message> responseObserver) {
        synchronized (this.watchers) { // Prevent sending stale states
            responseObserver.onNext(this.lastMessage);
            this.watchers.add(responseObserver);
        }
        Context.current().addListener(context -> {
            this.watchers.remove(responseObserver);
            responseObserver.onCompleted();
        }, directExecutor());
    }
````

Does this answer your question?
