### ISSUE TITLE
Why the grpc-client need to configure grpc client ports to start in k8s？

### ISSUE THREAD

**Issue by wilson11314** [yidongnan/grpc-spring-boot-starter#584]
There is no port configuration in this GrpcChannelsProperties class，However, the startup service reports the following exceptions

2021-09-16 17:33:15.456 DEBUG 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : Application failed to start due to an exception
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'grpc.client.port' to net.devh.boot.grpc.client.config.GrpcChannelProperties
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:363) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:323) ~[spring-boot-2.3.7.RELEASE.jar!/:2.3.7.RELEASE]

**Comment by ST-DDT** [comment]
The property is called `grpc.client.<clientname>.address`.

For example you would configure the address for `@GrpcClient("myService")` via:

````properties
grpc.client.myService.address=dns:///my-service.some.domain:8443
````

- [GrpcChannelsProperties#client](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelsProperties.java#L48)
- [GrpcChannelProperties#address](https://github.com/yidongnan/grpc-spring-boot-starter/blob/3236156600e95595e5f2deaa4ed7bc0873d80a20/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java#L59)

Does that answer your question?

**Comment by ST-DDT** [comment]
`grpc-spring-boot-starter` uses the port 9090 for grpc by default.
So you might have to create a `my-service-grpc` service that maps the container port to 80, if you don't want to configure the port.

**Comment by wilson11314** [comment]
this is grpc client configration
`#grpc配置
grpc:
  client:
    grpc-client:
      negotiationType: TLS #证书验证的两种模式PLAINTEXT、TLS
      address: static://localhost:9091
      #address: static://172.16.14.155:30080
      security:
        trust-cert-collection: classpath:keys/trusted-servers-collection
        private-key: classpath:keys/client2.key
        certificate-chain: classpath:keys/client.pem
        authority-override: SERVER
        client-auth-enabled: true
`
start client-service reports the following exceptions
![image](https://user-images.githubusercontent.com/30697826/133707565-29bfb926-63f5-4aa3-a7a1-cbdc94424af6.png)

**Comment by ST-DDT** [comment]
Please check your configuration again.
The exception literally shows another property that is not present in your screenshot and that is causing issues.
Remove the `grpc.client.port` property from all your configurations.

**Comment by ST-DDT** [comment]
I assume this to be fixed. Feel free to reopen, if you have another question.
