### ISSUE TITLE
Grpc server started but cannot connect

### ISSUE THREAD

**Issue by jeffreychuuu** [yidongnan/grpc-spring-boot-starter#588]
I'm using kotlin with spring boot building by gradle. The log shows that grpc server was listening on port 9090, while when I use BloobRpc to test if the server works, it reflects "error": "12 UNIMPLEMENTED: Method not found: demo.Greeter/SayHello". 

My GrpcServerService basically is written by Java as below

```java
@GrpcService
public class GrpcServerService extends GreeterGrpc.GreeterImplBase {
    @Override
    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
        HelloReply reply = HelloReply.newBuilder().setMessage("Hello ==> " + req.getName()).build();
        responseObserver.onNext(reply);
        responseObserver.onCompleted();
    }
}
```

Does anyone knows how to resolve this issue?

![image](https://user-images.githubusercontent.com/20805843/135115876-be576d2a-2776-4798-acd7-2a7d91ae5d97.png)

![image](https://user-images.githubusercontent.com/20805843/135115998-8da80cd7-7550-479c-909b-c8c851a6e17a.png)

**Comment by ST-DDT** [comment]
As you can see in the logs, the server did not find/register the grpc service.
Can you please check that the bean is actually created.

**Comment by jeffreychuuu** [comment]
The grpc server should have started correctly since once I changed the port to others in BloomRpc the error code is not "error": "12 UNIMPLEMENTED: Method not found: demo.Greeter/SayHello". It was "error": "14 UNAVAILABLE: failed to connect to all addresses" instead.

![image](https://user-images.githubusercontent.com/20805843/135182669-85cece53-19d0-422e-a9c6-a7463ec0aadf.png)

**Comment by jeffreychuuu** [comment]
Would be appreciated that if you don't mind help me to check through my app. It locates at https://github.com/jeffreychu-org/kotlin_example_app. 

It may tested simply be 
1. cd /rdbms_service
2. docker-compose up -d to start the PostgreSQL and redis
3. simple start the spring boot app and it will trigger the other project grpc_lib to generate the grpc stub for use

**Comment by ST-DDT** [comment]
> $ docker compose up
> (root) Additional property postgres is not allowed

I have trouble starting the docker compose on my computer (I haven't used it here before).
Maybe Windows doesn't like docker compose?

I still managed to start the application by stripping it of the other components.
FFR: Please reference only minimal workign examples not a project that showcases all.

````txt
2021-09-29 21:38:40.805  INFO 2888 --- [           main] n.d.b.g.s.s.AbstractGrpcServerFactory    : Registered gRPC service: grpc.health.v1.Health, bean: grpcHealthService, class: io.grpc.services.HealthServiceImpl
2021-09-29 21:38:40.805  INFO 2888 --- [           main] n.d.b.g.s.s.AbstractGrpcServerFactory    : Registered gRPC service: grpc.reflection.v1alpha.ServerReflection, bean: protoReflectionService, class: io.grpc.protobuf.services.ProtoReflectionService
2021-09-29 21:38:41.220  INFO 2888 --- [           main] n.d.b.g.s.s.GrpcServerLifecycle          : gRPC Server started, listening on address: *, port: 9090
2021-09-29 21:38:41.230  INFO 2888 --- [           main] c.e.k.KotlinExampleAppApplicationKt      : Started KotlinExampleAppApplicationKt in 3.566 seconds (JVM running for 4.106)
````

As you can see the server detected the two default grpc services ( ServerReflection, Health ).
But it didn't detect your `GrpcServerService`, nor did it execute its `afterPropertiesSet` method.
So the issue here is that the service doesn't get recognized as bean.
I tried to annotate it with `@Component` but doesn't seem to do the trick either.

I checked the jar and the class wasn't present there, so I suspect there is an issue with your build gradle that ignores plain java files.

**Comment by jeffreychuuu** [comment]
Yes. That's what I'm also suspecting that if we can have hybird spring boot application with boot kotlin and java since I found that the bean is not created. Anyway, does this starter package support kotlin version? Since I know the message files generated by protoc are still java. Or is there any example of integrating with kotlin about this starter so I can get a try.

**Comment by ST-DDT** [comment]
See also https://github.com/yidongnan/grpc-spring-boot-starter/pull/412
