### ISSUE TITLE
how to custom grpc client route rule

### ISSUE THREAD

**Issue by winnerku** [yidongnan/grpc-spring-boot-starter#599]
i just want custom my client route rule ,because i want use user_id to route which server i want. example:
user_id:1  --> server 1
user_id:2 --> server2

how can i do with grpc spring boot starter client

**Comment by ST-DDT** [comment]
There is nothing build into grpc or this library to achieve this. The requirements are very vage, so it's hard to tell what you exactly want to achieve.

How many "user_id -> server" mappings are there? 1:1 (different server per client) or x:1 (multiple clients share the same server)?

**Comment by winnerku** [comment]
The function I want is intelligent route, similar to certain conditions to the specified node
For example, I have 100 users, 3 nodes, determined where the route is based on the user ID.
for example:
UserId = 1, hash (userid)% 3 (number of machines) = 1 -> Node 1
UserId = 2, hash (userid)% 3 (number of machines) = 2 -> Node 2
I hope that some strategies for open routing will be used to use our customization.

**Comment by ST-DDT** [comment]
There are two ways to do this:

Create an wrapper around your channel/stub that toggles between the servers.

````java
@GrpcClient("stub0")
MyStub stub0;
@GrpcClient("stub1")
MyStub stub1;
@GrpcClient("stub2")
MyStub stub2;

MyStub getStub(long userId) {
    switch (userId % 3) {
        default:
        case 0:
            return stub0;
        case 1:
            return stub1;
        case 2:
            return stub2;
    }
}
````

As an alternative you can use a `ClientInterceptor` to do the same (but behind the scenes).
Does this answer your question?

**Comment by winnerku** [comment]
Sorry, I may not express it clearly, what you said does not solve my problem
For example: I have a `@Grpcclient ("A")` service
There are 4 machines under A services: **10.10.1.21-10.10.1.24**
now
```
  Userid: 1 user routes 10.10.1.21
  Userid: 2 user routes 10.10.1.22
  Userid: 3 user routes 10.10.1.23
  UserID: 4 user routes 10.10.1.24
```

I don't know if I have a clear problem now.
My needs is how the machine is the process of how to route the machine?

**Comment by ST-DDT** [comment]
I understand you better now.
There is a grpc client side LoadBalancer that might be able to do what you want.
https://grpc.github.io/grpc-java/javadoc/io/grpc/LoadBalancer.html
I haven't created one myself yet, but AFAICT you have to create a factory and register it in the registry, then you can use the config to set the name to configure it.
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java#L149
Please note that I dont know whether the LB has access to the authentication or how to forward related information to it.

If you find an answer please let me know.

**Comment by winnerku** [comment]
I know what you mean, I will try to solve this problem, if there is any way to solve, I will tell you the first time.

**Comment by ST-DDT** [comment]
I will close the issue for now. If you/someone have found a solution we can reopen this issue to expand the documentation with it.
