### ISSUE TITLE
bearerAuth in net.devh.boot.grpc.client.security.CallCredentialsHelper doesn't work properly

### ISSUE THREAD

**Issue by victorhua** [yidongnan/grpc-spring-boot-starter#617]
**The context**

The following method doesn't seem to work for me.
public static CallCredentials bearerAuth(final Supplier<String> tokenSource)

**The bug**

When passing the supplier, it seems putting tokenSource.toString() as token. It looks like a typo there.
I think it should be:

````java
    public static CallCredentials bearerAuth(final Supplier<String> tokenSource) {
        return authorizationHeader(() -> BEARER_AUTH_PREFIX + tokenSource.get());
    }
````

**Comment by ST-DDT** [comment]
Sorry for the trouble and nicely spotted.
We will fix it in the next release.
