### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by 94010846** [yidongnan/grpc-spring-boot-starter#62]
![image](https://user-images.githubusercontent.com/23432338/34512340-cf1115e8-f09c-11e7-91c0-e09d6338c9db.png)
不知道什么原因，client调用server调不通。
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.sleuth.Span.baggageItems()Ljava/lang/Iterable;

**Comment by yidongnan** [comment]
可能是依赖版本有冲突，可以检查一下。或者参考示例
https://github.com/yidongnan/spring-boot-grpc-example
