### ISSUE TITLE
"Network closed for unknown reason" after "not an SSL/TLS record".

### ISSUE THREAD

**Issue by Fr3027** [yidongnan/grpc-spring-boot-starter#623]
**The context**

What do you wish to achieve?
Remotely call the grpc code of the user microservice from the consumer microservice.

**The question**

Got "Network closed for unknown reason".
What's the problem? What's not working? What's missing and why do you need it?
I have 2 service registered by consul, one called user-service , and the other called consumer-service. I set up grpc server in user microservice successfully, and I can use native grpc-java code call my function remotely. 
The problem is , I can't use UserServiceBlockingStub annotated by @GrpcClient successfully, it throws "not an SSL/TLS record" error. I resolved this by settings negotiationType to plaintext in application.yml, then it throws "Network closed for unknown reason". The trouble Shooting page suggests that it can be either  (1) trying to connect to an grpc-server in TLS mode using a PLAINTEXT client or (2) the target is not a grpc-server (e.g. a web-server). I think I can rule out the second error cause the "not an SSL/TLS record" I encountered before. and what confused me is that I leave grpc server configuration default so it should not in TLS mode.

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.0.RELEASE
* grpc-java: 1.42.2
* grpc-spring-boot-starter: 2.13.1.RELEASE
* java: version + architecture (64bit?) JDK1.8 64bit
* Other relevant libraries...

**Additional information**

Using native grpc-java code call my function remotely is working fine:

```java
ManagedChannel channel = ManagedChannelBuilder
        .forAddress("192.168.0.207", 9090)
        .usePlaintext()
        .build();
UserServiceGrpc.UserServiceBlockingStub userServiceStub = UserServiceGrpc.newBlockingStub(channel);
UserResponse abc = userServiceStub.query(UserRequest.newBuilder().setName("abc").build());
System.out.println(abc);
```

consumer microservice application.yml related to grpc:

```yaml
grpc:
  client:
    user-service:
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
```

**Comment by Fr3027** [comment]
Thank you for your reply, it works now after changed to static address, can you tell me how to set the net.devh.boot.grpc.client.nameresolver.DiscoveryClientNameResolver logger to DEBUG?

**Comment by Fr3027** [comment]
```
2022-01-12 00:10:02.365 DEBUG 23908 --- [ault-executor-0] n.d.b.g.c.n.DiscoveryClientNameResolver  : Got 1 candidate servers for mall-admin
2022-01-12 00:10:02.365 DEBUG 23908 --- [ault-executor-0] n.d.b.g.c.n.DiscoveryClientNameResolver  : Ready to update server list for mall-admin
2022-01-12 00:10:02.368 DEBUG 23908 --- [ault-executor-0] n.d.b.g.c.n.DiscoveryClientNameResolver  : Found gRPC server host.docker.internal:8080 for mall-admin
```
It seems that grpc client find my tomcat port instead of grpc server port. But why, in consul service metadata, I can verify that metadata is set correctly.
![image](https://user-images.githubusercontent.com/38545119/148979775-d0a633de-61f1-4ef7-8ef9-12e546922601.png)

**Comment by ST-DDT** [comment]
Because spring-boot doesn't yet offer a way to generically register a service.
The standalone support is planned, but not yet added.
You can manually register your service in consul, that might be the easiest fix.

See also: https://github.com/spring-cloud/spring-cloud-commons/issues/1058

**Comment by Fr3027** [comment]
Since your project already supports registering consul service with metadata, is it necessary to register a service manually? 
I mean , can we do client-side grpc server port discovery using metadata information?

**Comment by ST-DDT** [comment]
The metadata are already used for it.

https://github.com/yidongnan/grpc-spring-boot-starter/blob/aee1d1486973f06d1b7be3a030b3a2c309b671a4/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java#L161-L189

If you encounter issues with that, please use the debugger to check whether your client receives that data and why it isn't detected in that method.

**Comment by Fr3027** [comment]
I found that spring cloud consul's DiscoverClient implementation treats consul tag as metadata by default. It works fine after setting `spring.cloud.consul.discovery.tagsAsMetadata=false`. But I don't find this properties setting anywhere in [cloud-grpc-client example](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/examples/cloud-grpc-client/src/main/resources/application-consul.yml), did I miss something important?

**Comment by ST-DDT** [comment]
Which version of spring-cloud are you using?
To me, it looks like the property has been removed at some point so that it works out of the box now.
https://github.com/spring-cloud/spring-cloud-consul/issues/698

**Comment by Fr3027** [comment]
spring-cloud :　Hoxton.SR5
spring-cloud-consul-discovery: 2.2.3-RELEASE

**Comment by ST-DDT** [comment]
If I remember correctly we had to change the metadata name at some point.
See this posts for details:
https://github.com/yidongnan/grpc-spring-boot-starter/issues/495

**Comment by ST-DDT** [comment]
I would like to improve the troubleshooting section a bit, since you found and read the actual cause, but were unable to link it to your problem.

Do you have a suggestion on how to improve this?

The current version for easier reference:

> ## Network closed for unknown reason
> 
> ### Client-side
> 
> ````txt
> io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
> ````
> 
> ### The Problem
> 
> You are either (1) trying to connect to an grpc-server in `TLS` mode using a `PLAINTEXT` client
> or (2) the target is not a grpc-server (e.g. a web-server).
> 
> ### The Solution
> 
> 1. Configure your client to use `TLS` mode.
> 
>    ````properties
>    grpc.client.__name__.negotiationType=TLS
>    ````
> 
>    or remove the `negotiationType` config completely as `TLS` is the default.
> 2. Validate that the configured server is running and is a grpc-server using
>    [`grpcurl`](https://github.com/fullstorydev/grpcurl) or a similar tool.

I consider adding a third section:

````md
3. Validate that the name resolver (dns/service discovery) you are using returns the correct ip and port.
   (e.g. by temporarily using the hardcoded ip and port as address: `static://<ip>:<port>`)
````

However, I am not sure if this is helpful to users and would like to hear your opinion on this issue.

**Comment by Fr3027** [comment]
4. Validate grpc server port founded is correct by viewing `net.devh.boot.grpc.client.nameresolver.DiscoveryClientNameResolver logger` DEBUG information. If grpc server port founded is not as excepted, it indicated that grpc server port information is not found in metadata. Double check your `grpc-spring-boot-starter` version and `spring-cloud-consul` version if you sure that port information exists. Notice that older `spring cloud consul` DiscoverClient implementation treat consul `tags` as `metadata`, you can resolve this by either upgrading `spring cloud consul` version or setting `spring.cloud.consul.discovery.tagsAsMetadata=false`
I think information above is useful.
