### ISSUE TITLE
Own variant bean GrpcServerLifecycle

### ISSUE THREAD

**Issue by mrfandorin** [yidongnan/grpc-spring-boot-starter#629]
Hi,
I trying to create my variant GrpcServerLifecycle, but I don't understand how to change bean net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle to my bean.

**The application's environment**
* Spring (boot): 5.3.13/2.4.13
* grpc-spring-boot-starter: 2.12.0

**Comment by ST-DDT** [comment]
If you create your own server, then you also have to create your own lifecycle bean.
See also: https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java#L52

Does this answer your question?

**Comment by mrfandorin** [comment]
> If you create your own server, then you also have to create your own lifecycle bean. See also: https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java#L52
> 
> Does this answer your question?

Thanks for your answer. 
Can I override only method stop()?

**Comment by ST-DDT** [comment]
> Can I override only method stop()?

Sure you can, but what do you wish to achieve by that?
Spring calls that, if the application shuts down, but you can do so as well.
Do you wish to control the server shutdown?

**Comment by mrfandorin** [comment]
> Sure you can, but what do you wish to achieve by that? Spring calls that, if the application shuts down, but you can do so as well. Do you wish to control the server shutdown?

Yes, I want to add logic with timeout

`  @Override
    public void stop() {
        myTimeoutMethod();
        stopAndReleaseGrpcServer();
    }
`

**Comment by ST-DDT** [comment]
Currently the server only overs a grace period, so if you need anything custom you can overwrite it.
Do you have any other questions related to this?

**Comment by mrfandorin** [comment]
Can I do this steps?
1. Spring calls stop()
2. New connections is processing during a timeout period (while traffic is going from balancer)
3. Next steps from stopAndReleaseGrpcServer()

**Comment by ST-DDT** [comment]
Yes, but I recommend not shutting the application down while the balancer still has open connections. As soon as you shutdown the application some beans might become unavailable.
Maybe you can intercept the spring shutdown hooks:
- Unregister the application from the lb. 
- Wait x time. 
- Then shutdown the app.

**Comment by mrfandorin** [comment]
Thanks for yor answers!
