### ISSUE TITLE
In the service method, how do I get the currently authorized user

### ISSUE THREAD

**Issue by melin** [yidongnan/grpc-spring-boot-starter#634]
In the service method, how do I get the currently authorized user。

**Comment by ST-DDT** [comment]
Like you do in SpringSecurity: [`SecurityContextHolder.getContext().getAuthentication()`](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/context/SecurityContextHolder.html#getContext()).

As an alternative you can use the grpc way: [`SECURITY_CONTEXT_KEY.get()`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthenticatingServerInterceptor.java#L50)
