### ISSUE TITLE
Is the GrpcAuthenticationReader equivalent to the Spring AuthenticationFilter?

### ISSUE THREAD

**Issue by zenon-was-here** [yidongnan/grpc-spring-boot-starter#636]
Hi, I am enjoying using this framework. 

I have a question: Is the `GrpcAuthenticationReader` equivalent to the Spring `AuthenticationFilter`? It seems to fit the same role, interacting with the AuthenticationManager.

If that is the case, another question is: Why? Is the need for it due to some fundamental difference in how the io.grpc.ServerCall happens compared to the HttpServletRequest that the AuthenticationFilter processes?

Thank you.

**Comment by ST-DDT** [comment]
Yes, it is impossible to access the underlying http request from grpc, rendering this method inaccessible/unusable.
https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/authentication/AuthenticationFilter.html#doFilterInternal(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,javax.servlet.FilterChain)
( grpc isnt servlet based )

The AuthenticationReader is only one part of the authentication workflow. Its only job is it to read the authentication details from the request.
It does not validate these using the authentication manager. (I would love to reuse more of the spring security components, but unfortunately they are strongly coupled to spring web/servlets.)

The second and more important part is the https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/DefaultAuthenticatingServerInterceptor.java
which does the actual auth steps.

After that there will either be
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthorizationCheckingServerInterceptor.java#L58 or the normal spring security annotation chain.

See also https://yidongnan.github.io/grpc-spring-boot-starter/en/server/security.html#authentication-and-authorization

Does this answer your question?

**Comment by zenon-was-here** [comment]
Thank you for these insights!
