### ISSUE TITLE
EnableGlobalMethodSecurity stops ability to use GrpcClient

### ISSUE THREAD

**Issue by fgarsombke** [yidongnan/grpc-spring-boot-starter#637]
This works just fine...

```
@Configuration
public class AppConfig extends GlobalMethodSecurityConfiguration {

  @GrpcClient("userService")
  private UserServiceGrpc.UserServiceBlockingStub userService;

  @Bean
  public UserClient userClient() {
    return new UserClientWrapper(userService);
  }
```

But when security is added...

```
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class AppConfig extends GlobalMethodSecurityConfiguration {

  @GrpcClient("userService")
  private UserServiceGrpc.UserServiceBlockingStub userService;

  @Bean
  public UserClient userClient() {
    return new UserClientWrapper(userService);
  }
```

the `userService` is always null. 

This also works without global security...

```
@Configuration
@GrpcClientBean(
    clazz = UserServiceGrpc.UserServiceBlockingStub.class,
    beanName = "userService",
    client = @GrpcClient("userService"))
public class AppConfig extends GlobalMethodSecurityConfiguration {

  @Bean
  public UserClient userClient(@Qualifier("userService") final UserServiceGrpc.UserServiceBlockingStub userService) {
    return new UserClientWrapper(userService);
  }
```

But does not work with...

```
@Configuration
@GrpcClientBean(
    clazz = UserServiceGrpc.UserServiceBlockingStub.class,
    beanName = "userService",
    client = @GrpcClient("userService"))
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class AppConfig extends GlobalMethodSecurityConfiguration {

  @Bean
  public UserClient userClient(@Qualifier("userService") final UserServiceGrpc.UserServiceBlockingStub userService) {
    return new UserClientWrapper(userService);
  }
```

Thoughts?

Thank you in advance!

**Comment by ST-DDT** [comment]
Is it possible that you run into this issue?

https://yidongnan.github.io/grpc-spring-boot-starter/en/server/security.html#spring-annotation-security-checks

**Comment by fgarsombke** [comment]
Thank you for the quick response.

I did try the proxy target class true flag and the GrpcClient is still null
when it is passed to the UserClient bean. :(

Without the EnableGlobalMethodSecurity everything works fine.

**Comment by ST-DDT** [comment]
Please check, whether the stub is null in the bean method itself and when the constructor is invoced.

````java
@Bean
public UserClient userClient(@Qualifier("userService") final UserServiceGrpc.UserServiceBlockingStub userService) {
    return new UserClientWrapper(Objects.requireNonNull(userService, "userService"));
}
````

The same inside the constructor.

If that does pass, then the proxying will probably attempt to call a method that points to the proxy instead of the actual instance.
This is usually the case, if you have any `final` methods inside your class.

You can also configure security for grpc without annotations too, by using the 

https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerSecurityAutoConfiguration.java#L103-L104

**Comment by fgarsombke** [comment]
OK awesome, thank you for the advice. I will try this out tonight and
follow up with which of these approaches worked. Have a great weekend!

**Comment by fgarsombke** [comment]
Strange, that still doesn't work.

This works.

```
@Configuration
@GrpcClientBean(
    clazz = UserServiceGrpc.UserServiceBlockingStub.class,
    beanName = "userService",
    client = @GrpcClient("userService"))
public class AppConfig extends GlobalMethodSecurityConfiguration {

  @Bean
  public UserClient userClient(@Qualifier("userService") final UserServiceGrpc.UserServiceBlockingStub userService) {
    return new UserClientWrapper(userService);
  }

```

But this throws an error:

```
@Configuration
@GrpcClientBean(
    clazz = UserServiceGrpc.UserServiceBlockingStub.class,
    beanName = "userService",
    client = @GrpcClient("userService"))
@EnableGlobalMethodSecurity(prePostEnabled = true, proxyTargetClass = true)
public class AppConfig extends GlobalMethodSecurityConfiguration {

  @Bean
  public UserClient userClient(@Qualifier("userService") final UserServiceGrpc.UserServiceBlockingStub userService) {
    return new UserClientWrapper(userService);
  }
```

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method userClient in com.xxxxx.apiv4.config.AppConfig required a bean of type 'com.xxxxx.user.api.user.UserServiceGrpc$UserServiceBlockingStub' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Qualifier(value="userService")


Action:

Consider defining a bean of type 'com.xxxxx.user.api.user.UserServiceGrpc$UserServiceBlockingStub' in your configuration.
-----------------------------------------

We would like to use the @PreAuthorize annotation because we have built quite a bit of functionality with our own permission eavaluators.

**Comment by fgarsombke** [comment]
I've determined its the combination of `extends GlobalMethodSecurityConfiguration` and `@EnableGlobalMethodSecurity(prePostEnabled = true, proxyTargetClass = true)` that causes this issue.

Without `extends GlobalMethodSecurityConfiguration` it works correctly.

I will continue to investigate why the extends causes the null issue.

**Comment by ST-DDT** [comment]
Strange. I haven't had any issues with it messing up the configuration beans yet. (Well, I avoid defining beans in extended configs anyway).
You could try `@Configuration(proxybeanmethods=false)` that way there should be at least less magic happening in that config class.

**Comment by e7868a** [comment]
**GlobalMethodSecurityConfiguration** implements **SmartInitializingSingleton**, it is created early than **GrpcClientBeanPostProcessor**。**GrpcClientBeanPostProcessor** can't process **AppConfig** and it's dependency beans。

create stub bean with **GrpcClientBean**,  use **@Lazy** to delay field inject。

Maybe **GrpcClientBeanPostProcessor** should implments  **PriorityOrdered** to get higher priority。
