### ISSUE TITLE
Can we get HttpRequest, HttpServletRequest or request metadata header on GrpcService

### ISSUE THREAD

**Issue by burak0206** [yidongnan/grpc-spring-boot-starter#639]
I am developing a grpc api with Spring boot and the grpc-spring boot lib. 
 
 I need to be able to access the user id and other information in the bearer token in @GrpcService. How can I access the request header in @GrpcService ?

Which versions do you use?
* Spring boot: 2.6.3
* io.grpc: 1.42.1
* grpc-spring-boot-starter: 2.13.0.RELEASE
* kotlin: 1.6.10 + M1 Chipset

**Comment by ST-DDT** [comment]
If you are referring to just the headers, then this might help:
https://github.com/grpc/grpc-java/tree/v1.33.1/examples/src/main/java/io/grpc/examples/header

If you want to get access to the authentication instance, then you can use
`SecurityContextHolder.getSecurityContext().getAuthentication()` dependending on your AuthenticationProvider it might contain all you need.

Does that help you?

**Comment by burak0206** [comment]
Hi,

I have tried to use `SecurityContextHolder.getSecurityContext().getAuthentication()`.  I added a class, GrpcAuthorizationInterceptor that extented ServerInterceptor.  My goal is not just security. At the same time, I need to access the userID of token from within grpc services. I have one more service that verifies jwt, parses and generates tokens. Other than that, I didn't add any other  spring security configuration code. but I have serious concerns about whether this is thread safe or not. I understand that the GrpcAuthorizationInterceptor is refreshed for each request. Is SecurityContextHolder.getContext().authentication thread safe ? Is it created differently for each request? I tried to use spring security at first, but I couldn't. As I said, I need to use userID in grpc services as well. How should I proceed?

`

               @GrpcGlobalServerInterceptor
                class GrpcAuthorizationInterceptor(private val jwtUtil: JwtUtil) : ServerInterceptor {
                
                    companion object {
                        private const val AUTHORIZATION_TAG = "Authorization"
                        private const val BEARER_TAG = "Bearer "
                        private val FORBIDDEN_RESPONSE = Status.UNKNOWN
                
                        private fun isValid(authHeader: String?): Boolean {
                            return authHeader != null && authHeader.trim().isNotBlank() && authHeader.startsWith("Bearer ")
                        }
                    }
                
                    private val logger = KotlinLogging.logger {}
                
                    override fun <ReqT : Any?, RespT : Any?> interceptCall(
                        serverCall: ServerCall<ReqT, RespT>?,
                        metadata: Metadata?,
                        serverCallHandler: ServerCallHandler<ReqT, RespT>?
                    ): ServerCall.Listener<ReqT> {
                        logger.info("GrpcAuthorizationInterceptor::interceptCall")
                        logger.info(serverCall?.methodDescriptor?.fullMethodName)
                        val authHeader = metadata?.get(Metadata.Key.of(AUTHORIZATION_TAG, Metadata.ASCII_STRING_MARSHALLER))
                        if (isValid(authHeader)) {
                            logger.info(authHeader)
                            val jwt = authHeader!!.replace(BEARER_TAG, "")
                            logger.info(jwt)
                            if ( jwtUtil.tokenValidate(jwt)){
                                val claims = jwtUtil.getClaimsFromToken(jwt)
                                claims?.apply {
                                    logger.info(claims.toString())
                                    val userId = claims["userId"].toString().toLong()
                                    val authToken = UsernamePasswordAuthenticationToken(userId, null, emptyList())
                                    logger.info { authToken }
                                    SecurityContextHolder.getContext().authentication = authToken
                                    return serverCallHandler!!.startCall(serverCall!!, metadata!!)
                                }
                            }
                        }
                        logger.info( serverCall?.authority)
                        SecurityContextHolder.getContext().authentication = null
                        return serverCallHandler!!.startCall(serverCall!!, metadata!!)
                    }
                }
                
                @GrpcService
                class UserManagementController(
                    private val addCustomerRolePermissionUseCase: AddCustomerRolePermissionUseCase,
                    private val addCustomerRolePermissionPresenter: AddCustomerRolePermissionPresenter,
                    private val getCustomerRolePermissionUseCase: GetCustomerRolePermissionUseCase,
                    private val getCustomerRolePermissionPresenter: GetCustomerRolePermissionPresenter,
                    private val getUserUseCase: GetUserUseCase,
                    private val getUserUsePresenter: GetUserUsePresenter
                ) : UserManagementApiGrpc.UserManagementApiImplBase() {
                
                    private val logger = KotlinLogging.logger {}
                
                    override fun getUser(request: GetUserRequest?, responseObserver: StreamObserver<GetUserResponse>?) {
                        logger.info { "user.management.api.getuser" }
                        logger.info { request.toString() }
                
                        if(SecurityContextHolder.getContext().authentication != null ) {
                            logger.info { SecurityContextHolder.getContext().authentication }
                            logger.info { SecurityContextHolder.getContext().authentication.principal }
                        }
                
                        if(SecurityContextHolder.getContext().authentication != null ) {
                            responseObserver?.onError(
                                     StatusException(
                                         Status.UNAUTHENTICATED.withDescription("there is no token")
                                     )
                            )
                        }
                        
                        request?.selector?.apply {
                            val filter = request.selector?.searchByFilterCase?.name
                
                            when (filter)  {
                                "ID" ->  responseObserver?.onError(
                                    StatusException(Status.UNKNOWN.withDescription("id ile gelinmez"))
                                )
                                "EMAIL" -> {
                                    val email = Email(request.selector.email.email)
                                    val command = GetUserUseCase.GetUser(
                                        email
                                    )
                                    val getUserResponse = getUserUseCase.getUser(command)
                                    getUserUsePresenter.respond(command, getUserResponse, responseObserver)
                                }
                                "SEARCHBYFILTER_NOT_SET" -> responseObserver?.onError(
                                    StatusException(Status.UNKNOWN.withDescription("SEARCHBYFILTER_NOT_SET ile gelinmez"))
                                )
                            }
                        }
                    }
                
                
                @GrpcService
                class AccountController(
                    private val userLoginUseCase: UserLoginUseCase,
                    private val userLoginPresenter: UserLoginPresenter
                ) : AccountApiGrpc.AccountApiImplBase() {
                
                    private val logger = KotlinLogging.logger {}
                    override fun login(request: LoginRequest?, responseObserver: StreamObserver<LoginResponse>?) {
                        logger.info { "account.api.login" }
                
                
                        if(SecurityContextHolder.getContext().authentication != null ) {
                            logger.info { SecurityContextHolder.getContext().authentication }
                            logger.info { SecurityContextHolder.getContext().authentication.principal }
                        }
                        val email = Email(request?.email?.email)
                        val unencodedPassword = Password(request?.password?.password)
                        unencodedPassword.checkPasswordMeetConditions()
                        val command = UserLoginUseCase.UserLogin(
                            email,
                            unencodedPassword,
                        )
                        val loginResponse = userLoginUseCase.login(command)
                        userLoginPresenter.respond(command, loginResponse, responseObserver)
                    }
                }
                
                
                

`

**Comment by ST-DDT** [comment]
AFAICT You are leaking the security context. This will cause security issues in high concurrency cases. (Thread switches may occur after connect/before/after each message.)

Note: This library has spring security support.
You can use the authentication's user details to transport the user id. Just configure an AuthenticationReader and AuthenticationManager.
See also https://yidongnan.github.io/grpc-spring-boot-starter/en/server/security.html#authentication-and-authorization

If you wish to use your own interceptor, then please use the existing one as a reference.
Please use a test similar to this one to test your interceptor.
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/java/net/devh/boot/grpc/test/security/ConcurrentSecurityTest.java

**Comment by burak0206** [comment]
Actually my purpose are not authorization and authentication on spring security module. I know very little about spring security. I do not want to make a mistake. Also I can produce and parse token in business logic. Moreover I need token in @GrpcServices. Frankly, I want to pass the header to the services (GrpcService) in a thread-safe way without authentication or authorization. if i can't do that , I can use SecurityContextHolder.getContext().authentication.  I can generate a simple class that carries the token in any field derived from Authentication class. Or I parse first and pass userID. I fetch necessary things from DB.

I tried something like below (grpcAuthenticationReader), but I think this is very wrong because the purpose here is already authentication, I added a header to the login method for testing.  

What is the easiest way to send the header to services thread safe without check authentication or authorization If I have to use SecurityContextHolder W?

`    
      
              @Bean
              @Primary
              fun grpcAuthenticationReader(): GrpcAuthenticationReader {
                  return GrpcAuthenticationReader { call, headers ->
                      println("GrpcAuthenticationReader::readAuthentication")
                      val token = headers?.get(Metadata.Key.of("Authorization", Metadata.ASCII_STRING_MARSHALLER))
                      val jwt = token!!.replace("Bearer", "")
                      val claims = jwtUtil.getClaimsFromToken(jwt)
                      val userId = claims["userId"]
                      UsernamePasswordAuthenticationToken(userId, "qwerty123", emptyList())
                  }
              }
    
    
   `

**Comment by ST-DDT** [comment]
If you want to go for at least pseudo auth, then you can do it like this:

````java
@Bean
GrpcAuthenticationReader grpcAuthenticationReader() {
     return new BearerAuthenticationReader(token -> new PreAuthenticatedAuthenticationToken(token, null)); // just wrap it in something that can hold the token
}

@Bean
AuthenticationManager dummyAuthenticationManager () {
    return new ProviderManager(new AuthenticationProvider() {

		Authentication authenticate(Authentication auth) {
			try {
				// return a dummy authentication with all the information you want
				// or create a custom authentication subclass that contains all the methods you need
				// or use a user details service to lookup the user from the database...
				return new PreAuthenticatedAuthenticationToken(jwtUtil.getClaimsFromToken(auth.getPrincipal()), null, Collections.emptyList());
			} catch (JwtParseException e) {
				throw new BadCredentialsException("Invalid jwt token", e);
			}
        }

        boolean supports(Class<? extends Authentication> clazz) {
			return PreAuthenticatedAuthenticationToken.class.equals(clazz);
        }
    });
}
````

This does not verify the token other than `jwtUtil.getClaimsFromToken`.

-----------------------

If you are just after the header follow this example:

https://stackoverflow.com/questions/40112374/how-do-i-access-request-metadata-for-a-java-grpc-service-i-am-defining

--------------------

Does this answer all your questions?

**Comment by burak0206** [comment]
yes, 

thank you very much, 

these answers work for me.

I will try these. and I will test it. I will also share the code snippet here.
