### ISSUE TITLE
How to change negotiation type dynamicly via eureka meta data.

### ISSUE THREAD

**Issue by EdAndrew** [yidongnan/grpc-spring-boot-starter#651]
**The context**

I want to make new feature about grpc channel, and it is :

Grpc server can write meta data in eureka about whether negotiation type client should use to communicate with server. And before requests grpc server, grpc client should read this meta data from eureka and change own negotiotion type in channel.

**The question**

I know grpc client can use `DiscoveryClientNameResolver` to change ips of grpc server dynamicly, and want to know how to rewrite code to impletaion dynamic negotation type. Negotiation type is configured in Spring Boot init stage, how to change it in communication state?

Thanks for you answer!

**Comment by ST-DDT** [comment]
I don't know whether this is possible (it might not be for security reasons).
Could you open an issue on grpc-java directly or on StackOverflow and post a link to it here?

**Comment by EdAndrew** [comment]
Thanks a lot for answer. And link is https://github.com/grpc/grpc-java/issues/9064

**Comment by ST-DDT** [comment]
Seems it isn't possible as mentioned upstream. Closing for now.
