### ISSUE TITLE
istio address unknown

### ISSUE THREAD

**Issue by Chenbin1996** [yidongnan/grpc-spring-boot-starter#652]
grpc.client.item.address=static://activate.navicat.com:9091
grpc.client.item.negotiationType=PLAINTEXT

An error prompt：io.grpc.StatusRuntimeException: UNKNOWN

This is my code：
@GrpcClient("item")
    private ItemServiceGrpc.ItemServiceBlockingStub stub;

stub.addItem(operateItemRes)

**Comment by ST-DDT** [comment]
Please post the entire stacktrace.
I cannot help you at all like this.
