### ISSUE TITLE
build grpc service with bazel & grpc-java

### ISSUE THREAD

**Issue by xushaoxiao** [yidongnan/grpc-spring-boot-starter#665]
Recently building grpc service with bazel and grpc-java. grpc-java version is 1.46.0, but devh latest version only support 1.42.2.
so will release a version to support grpc-java:1.46.0

**Comment by ST-DDT** [comment]
AFAICT grpc-spring-boot-starter supports most grpc-java versions (at least those that are newer than the specified ones).
You can simply upgrade by using a newer grpc-java bom.
We will release a new version when we have time. Currently I'm very busy and I don't have time for some fixes, that I would like to include.

If you have a particular issue with this library/a grpc version please post a stacktrace.

**Comment by xushaoxiao** [comment]
I known, but i got a trace message about "net.devh.boot.grpc.server.condition.ConditionalOnInterprocessServer.logOutcome - Condition ConditionalOnInterprocessServer on net.devh.boot.grpc.server.autoconfigure.GrpcServerFactoryAutoConfiguration#nettyGrpcServerFactory matched due to NoneNestedConditions 0 matched 1 did not; NestedCondition on ConditionalOnInterprocessServer.NoServerPortCondition @ConditionalOnProperty (grpc.server.port=-1) found different value in property 'grpc.server.port'
"

**Comment by ST-DDT** [comment]
This message has nothing to do with the grpc version. It just tells you that you have not disabled port based access to your application in the config. Almost all (prod) deployments of this library have that trace message in their logs.
It's a trace log for a reason.

**Comment by xushaoxiao** [comment]
> This message has nothing to do with the grpc version. It just tells you that you have not disabled port based access to your application in the config. Almost all (prod) deployments of this library have that trace message in their logs. It's a trace log for a reason (from spring-boot).

Okay, thanks for support work.
