### ISSUE TITLE
How to add a custom header in grpc client for some requests?

### ISSUE THREAD

**Issue by pjslina** [yidongnan/grpc-spring-boot-starter#681]
How do I set custom headers for some requests

**Comment by ST-DDT** [comment]
Please search for a solution first before opening an issue.
I literally copied your question + ``java`` to google and this example was in the top 3.

https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java

TLDR:
- Add an [interceptor](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#clientinterceptor) ([global](https://www.javadoc.io/doc/net.devh/grpc-client-spring-boot-autoconfigure/latest/net/devh/boot/grpc/client/interceptor/GrpcGlobalClientInterceptor.html) or [dynamically](https://github.com/grpc/grpc-java/blob/f68be9f87ccf276069c3c6bd1f3be395a3090cd9/examples/src/main/java/io/grpc/examples/header/CustomHeaderClient.java#L50)) and [add a header](https://github.com/grpc/grpc-java/blob/f68be9f87ccf276069c3c6bd1f3be395a3090cd9/examples/src/main/java/io/grpc/examples/header/HeaderClientInterceptor.java#L49) there

**Comment by pjslina** [comment]
Thinks，I use GrpcClient annotation, this "stub" can not set header

@GrpcClient("common-service")
    private ICommonServiceGrpc.ICommonServiceBlockingStub stub;

**Comment by ST-DDT** [comment]
If you register the interceptor globally, then this library will apply it before injecting the stub.

You can also apply it yourself by only injecting the channel and creating the stub yourself.
