### ISSUE TITLE
GrpcExceptionHandler doesn't catch an exception in SpringBootTest

### ISSUE THREAD

**Issue by pc-avasilev** [yidongnan/grpc-spring-boot-starter#685]
I'm trying to test the **GrpcAdvice** and **GrpcExceptionHandler** with the SpringBootTest.
I have created the **GrpcCoreExceptionHandler**
```
@GrpcAdvice
public class GrpcCoreExceptionHandler
{

	@GrpcExceptionHandler(IllegalArgumentException.class)
	public StatusException handleResourceNotFoundException(IllegalArgumentException e) {
		Status status = Status.INVALID_ARGUMENT.withDescription(e.getMessage()).withCause(e);
		Metadata metadata = new Metadata();
		return status.asException(metadata);
	}
}
```
and have an integration test which invokes one of the methods in our gRPC `PersonService`
Here is the SpringBootTest setup:
```
@SpringBootTest(properties =
{
		"grpc.server.inProcessName=PersonServiceIntegrationTest", "grpc.server.port=-1"
})
@RunWith(SpringRunner.class)
@Transactional("spTransactionManager")
public class PersonServiceIntegrationTest
{
	@Autowired
	private PersonService subject;

	@SpyBean
	private PersonDao personDao;

	@Test
	public void getPerson_whenExceptionBeenThrown_returnsErrorResponse()
	{
		doThrow(IllegalArgumentException.class).when(personDao).getPerson(any(), any());
		StreamRecorder<PersonProto> responseObserver = StreamRecorder.create();
		UserPersonIdProto userPersonId = UserPersonIdProto.newBuilder().build();

		subject.getPerson(userPersonId, responseObserver);

		Throwable error = responseObserver.getError();
		assertNotNull(error);
	}

}
```
In current setup the ExceptionHandler is not invoking and Exception is propagating farther to a spring RunAfterTestExecutionCallbacks layer. 

But if i start the application locally and make a call with the Postman or any other gRPC client i can see that exception will be handled with the GrpcExceptionHandler.
So, it looks like there is some conflict with between the SpringBootTest configuration and GrpcAdvice initilization.

**Comment by ST-DDT** [comment]
Can you please check whether the related beans are created and called?

https://github.com/yidongnan/grpc-spring-boot-starter/blob/a8d26df77dc44ae0100031c496fc3494b3cb1192/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcAdviceAutoConfiguration.java#L52

**Comment by pc-avasilev** [comment]
Hi, thank you for response.
Yes, the GrpcAdviceAutoConfiguration.java class was initialized successfully.

**Comment by ST-DDT** [comment]
And are the related beans ever called?
Especially the GrpcExceptionInterceptor?

**Comment by pc-avasilev** [comment]
Nope, the GrpcExceptionInterceptor was not invoked during the debug session.

**Comment by ST-DDT** [comment]
I haven't found a test with `@SpringBootTest` for that.
I will have a look at it, when I have time.
In the meantime you could check why the interceptor is never invoked.
This is probably related to the initialization order:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/0194be1c68faaeea251ff2edb063b37121988554/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/interceptor/AnnotationGlobalServerInterceptorConfigurer.java#L64

**Comment by pc-avasilev** [comment]
When I'm running the app and making the gRPC call directly to this specific endpoint the exception is been intercepted by the `GrpcExceptionListener` and then handled by provided `ExceptionHandlerConfig`.

When I'm trying to run the PersonServiceIntegrationTest the initialization process goes through the `AnnotationGlobalServerInterceptorConfigurer.java` and two interceptors were added in a chain (GrpcRequestScope, GrpcExceptionInterceptor).
But neither of them were triggered after Exception throw. The next execution trace step goes to `RunAfterTestExecutionCallbacks`. So, i don't think this is an ordering issue.

**Comment by pc-avasilev** [comment]
I think i know why we have this behavior. The problem is that in my SpringBootTest I'm interacting with the `PersonSerivce` directly like with the regular Spring bean not like in standard `MockMvc` Controller tests where you are actually making the interactions with the DispatcherServlet. Do you have any ideas what can be used to substitute the `MockMvc` for gRPC?

**Comment by ST-DDT** [comment]
Yes: use @GrpcClient on a stub and then call your method there.

https://github.com/yidongnan/grpc-spring-boot-starter/blob/0194be1c68faaeea251ff2edb063b37121988554/tests/src/test/java/net/devh/boot/grpc/test/setup/AbstractSimpleServerClientTest.java#L88

**Comment by pc-avasilev** [comment]
Thank you for your help. The real client injection works fine.
