### ISSUE TITLE
Client Side certificate authentication

### ISSUE THREAD

**Issue by ncoif-tw** [yidongnan/grpc-spring-boot-starter#69]
Thanks for this Spring Boot integration!!

I've successfully configured it to use TLS tranport, but how would I use it for Client Side authentication in addition?

More specifically, something similar to the following:

```
Server server = NettyServerBuilder.forPort(8443)
    .sslContext(GrpcSslContexts.forServer(certChainFile, privateKeyFile)
        .trustManager(clientCertChainFile)
        .clientAuth(ClientAuth.REQUIRE) //this part
        .build());
```

https://github.com/grpc/grpc-java/blob/master/SECURITY.md#mutual-tls

**Comment by ST-DDT** [comment]
Currently this is only possible, if you implement and create your own `GrpcServerFactory` bean.

I will probably try to add direct support for that and also add support for easier configuration of unsupported features using a hook or something similar. (If I have some spare time).

**NettyGrpcServerFactory**

````java
public Server createServer() {
    [...]
    customize(builder, properties);
    return builder.build();
}

/**
 * Hook that can be used to customize the builder with features that are not 
 * yet supported by this library. The default implementation does nothing.
 */
protected void customize(NettyServerBuilder builder, GrpcServerProperties properties) {
}
````

**Comment by ST-DDT** [comment]
This is now already possible with the [clientAuth](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/springboot/autoconfigure/grpc/server/GrpcServerProperties.java#L95) property.

````properties
grpc.server.security.clientAuth=REQUIRE
grpc.server.security.trustCertCollectionPath=certificates/trusted-clients-collection
````

**Comment by ST-DDT** [comment]
I guess this issues can be closed now.
