### ISSUE TITLE
Customizable Tags Provider

### ISSUE THREAD

**Issue by pluttrell** [yidongnan/grpc-spring-boot-starter#703]
The current implementation provides a way to add new tags or to replace the entire interceptor bean to customize metrics. The former is a great way to add new static tags and the later is a bit of a full scale replacement. 

Please consider adding a middle option that would enable a way to more easily provide _all_ of the tags. 

WebFlux provides this with a `WebFluxTagsProvider`, which allows for full customization, including adding, renaming and omitting. 

Also, it would be great if this provider passes the `MethodDescriptor`.

**Comment by ST-DDT** [comment]
Please also report/request that feature there as we will eventually switch to that one.
This sound like a useful extension to me, so please ping me from the new issue and I might be able to add/implement it (when I have time).
https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc

**Comment by ST-DDT** [comment]
As for the original request in this issue (customizable tags):
this could also achieved using the following code:

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.customizing

```java
@Bean
public MeterFilter renameRegionTagMeterFilter() {
        return MeterFilter.renameTag("com.example", "mytag.region", "mytag.area");
}
```

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.customizing

In combination with the switch to the micrometer implementation I consider this as won't implement.
