### ISSUE TITLE
Add properties to enable/disable each metric

### ISSUE THREAD

**Issue by pluttrell** [yidongnan/grpc-spring-boot-starter#704]
Please consider adding a property to enable/disable each of the three metric's that are generated for both client & server support. Users might not find utility in one and thus might want an easy way to disable it.

**Comment by ST-DDT** [comment]
Once again:
Please also report/request that feature there as we will eventually switch to that one.
https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc

**Comment by pluttrell** [comment]
A [Micrometer PR](https://github.com/micrometer-metrics/micrometer/issues/3222) has been added to enable customization of the classes in Micrometer itself.

For this PR (in this starter repo), I'm hoping we can add configurable Spring Boot properties to configure these. I wonder if something like the following might make sense:

```yaml
grpc:
  server:
    metrics:
      processing-duration:
        enabled: true
```

**Comment by ST-DDT** [comment]
Since we are going to switch to the micrometer one in the next version, we won't implement this feature here for now.
