### ISSUE TITLE
Loading grpc channel properties  using PropertySourcesPlaceHolderConfigurer

### ISSUE THREAD

**Issue by prssnk** [yidongnan/grpc-spring-boot-starter#709]
In our application we have custom PropertySourcePlaceHolderConfigurer, which loads properties from various source into the application context  
```
import org.springframework.beans.factory.config.PropertyPlaceholderConfigurer;
public class AppPropertiesConfigurer extends PropertyPlaceHolderConfigurer  {
protected void loadProperties(Properties prop) {
//Load properites
}
```

We plan to load all application specific properties using this approach. The problem is we are not able to load GRPC channel properties defined for mygrpcchannel(see below) using AppPropertiesConfigurer. The properties are picked when it's stored in application.properties in MyGrpcClient code or  passed as command line arguments for application startup.

```
@Configuration
@GrpcClientBean(bean="app1", Clazz=CustomerService.CustomerServiceBlockingStub.class, client=@GrpcClient("mygrpcchannel"))
public MyGrpcClient {
}
```

```
//application.properties in client
grpc.mygrpcchannel.customerservice.address=dns:///locahost:9090
```

**Comment by ST-DDT** [comment]
Please make sure your bean is loaded early enough for the property to be picked up. Use breakpoints in constructors and related methods to get a grasp on the order.
Other than that there is hardly anything I can do to help you here, unless you are more specific about your question.

**Comment by prssnk** [comment]
@ST-DDT 
The issue does not happen we use PropertySourcesPlaceholderConfigurer of spring
