### ISSUE TITLE
Get data from gRPC cliient

### ISSUE THREAD

**Issue by MahdiyarTH** [yidongnan/grpc-spring-boot-starter#714]
**The context**

I have a GPS device that is using protobuf.

As i know, for sending data to a server using protobuf, must be at least a service specified in .proto files, and implement that service to get data. But in the [documentation](https://docs.mydolphin.org/Protocol.html) and .proto files in that document ([file1](https://docs.mydolphin.org/protocolFiles/Messages.proto), [file2](https://docs.mydolphin.org/protocolFiles/Config.proto)) does not mention any service

**The question**

How can i get data from this device, using Java, Spring boot when there is no service in .proto files?

**Comment by ST-DDT** [comment]
Have you checked that it actually uses gRPC as service implementation?
Protobuf is just the data definition and transfer format, but it can also be used without grpc.
