### ISSUE TITLE
Upgrade to 2.13.1.RELEASE new version cannot run, JVM environment problem occurs

### ISSUE THREAD

**Issue by FanForerver** [yidongnan/grpc-spring-boot-starter#715]
![image](https://user-images.githubusercontent.com/94419706/178395939-ac72944d-2332-4c1b-94e0-4456118a38e6.png)

**Comment by ST-DDT** [comment]
Sorry, I'm on vacation and wont be available for the next few weeks.

**Comment by ST-DDT** [comment]
Please try again the latest version and open a new ticket if the error still exists.
