### ISSUE TITLE
How to set Access-Control-Allow-Origin 

### ISSUE THREAD

**Issue by bianbian-org** [yidongnan/grpc-spring-boot-starter#72]
grpc-spring-server   <--->  grpc-webproxy <---> grpc-web-client

Failed to load https://xxxService/Xxx: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://xxx' is therefore not allowed access. The response had HTTP status code 415. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ST-DDT** [comment]
@bianbian-org Is the exception shown in the client or in the web proxy?
I guess its shown in the client, thus I assume that you have to configure your grpc-webproxy appropriately.
I think the CORS header is usually requested in an OPTIONS request and thus is unlikely to be processed by the grpc-spring-server. You could try to add the header in your responses though (using a `ServerInterceptor`).
