### ISSUE TITLE
请问什么时候能支持ETCD做服务注册和服务发现

### ISSUE THREAD

**Issue by lin-jesse** [yidongnan/grpc-spring-boot-starter#720]
我需要能够ETCD来做服务注册和服务发现，请问后续版本能支持吗？或者有开放接口能由我自己实现吗？

**Comment by ST-DDT** [comment]
Duplicate of https://github.com/yidongnan/grpc-spring-boot-starter/issues/557

**Comment by sunqb** [comment]
非常需要etcd的实现，这样可以实现springcloud和go的服务平滑调用
