### ISSUE TITLE
Is there any way I can make this boot-starter load local address config?

### ISSUE THREAD

**Issue by CYMWN211** [yidongnan/grpc-spring-boot-starter#724]
**The context**
Thanks for your kind reply
Hi,I am using this grpc-spring-boot-starter for my project,but considering of our team develop environment problems.I want to know how to configure grpc client's request address without configuration files like application.yml or application.properties. I can't find it by myself.

**The question**

My key problem is how to use this boot starter's custom configuration entrance which provide to developer to set client's request address.Our local way of configuration is reading config data form database

Of course,I have tried generate channel by setting address manually with @PostConstruct annoation like this:
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/49117342/183358707-fd341c5c-9ae7-4873-b24a-58c524abf8a1.png"> .But I consider this way of mixing config code with business service code is not elegant. I perfer a better way to set my request Url by using custom GrpcChannelFactory or some other way. Is there any way I can do this?

Hope to get your answer,thanks!

**Comment by ST-DDT** [comment]
There should be a way to pass these properties to spring, then it will use them the same as a config file.

https://stackoverflow.com/questions/46407230/load-spring-boot-app-properties-from-database

Does that answer your question?

**Comment by CYMWN211** [comment]
Thank you for this hint,I think this will be useful! On the other hand,I have tried this way of by using @Configuration and @Bean annotations to set my local grpcChannelsProperties
`@Configuration
public class GRPCCustomConfiguration {

    @Bean
    public GrpcChannelsProperties grpcChannelsProperties() {
        GrpcChannelsProperties grpcChannelsProperties = new GrpcChannelsProperties();

        GrpcChannelProperties singleChannel = new GrpcChannelProperties();
        singleChannel.setAddress("localhost:9092");
        singleChannel.setNegotiationType(NegotiationType.PLAINTEXT);
        grpcChannelsProperties.getClient().put("client-server-sync", singleChannel);

        return grpcChannelsProperties;
    }
}`
And it succeed ! But I think your option will be better, I will accept this. Thanks again!

**Comment by CYMWN211** [comment]
Thank you for this hint,I think this will be useful! On the other hand,I have tried this way of by using @configuration and @bean annotations to set my local grpcChannelsProperties
<img width="787" alt="image" src="https://user-images.githubusercontent.com/49117342/183542250-a75776c3-19d2-450c-8434-17f8a7cad21d.png">

And it also succeed ! But I think your option will be better, I will accept this. Thanks again!
