### ISSUE TITLE
How to get stub dynamically by server name

### ISSUE THREAD

**Issue by zuodimiaoyun** [yidongnan/grpc-spring-boot-starter#728]
**The context**

Our client-side business has all the server names, and needs to obtain stubs dynamically according to the business, rather than injecting specific stubs. 
But need to keep all features like @GrpcClient like grpc.client.__name__.* configuration, global interceptors etc.

**The question**

How can I get the stub like below:
```
@Component
public class StubProvider {

    public <T> T getStub(Class<T> stubClass, String serverName){
    // I can't inject stubs for all server names because when the server list changes, I want to change the configuration not the code.
        return null;
    }
}

```

**Comment by ST-DDT** [comment]
Currently there is no direct support for that.
However, you can use the [`GrpcChannelFactory`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/GrpcChannelFactory.java#L50) for that.
Please note that there is currently no way to close the connection/channel to that client.

A `StubProvider` (or something similar) is planned. I cannot find the issue/PR right now though.
Currently most of the logic is inside [`GrpcClientBeanPostProcessor`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java#L59), but I wish to extract it out of there.

**Comment by zuodimiaoyun** [comment]
Thanks for such a quick reply, I tried it as you suggested and it worked perfectly!
Regarding channel management, I read [this issue](https://github.com/yidongnan/grpc-spring-boot-starter/issues/397).
My scenario doesn't require the channel to be closed before the service is stopped.
So not being able to manage the lifetime of the channel doesn't matter to me.
But it's still necessary if someone needs to manage the channel dynamically.
