### ISSUE TITLE
cloud-grpc-server和cloud-grpc-client用mvn命令执行报错

### ISSUE THREAD

**Issue by Ivan97** [yidongnan/grpc-spring-boot-starter#73]
如题启动eureka后，通过`mvn spring-boot:run`命令执行会报错
测试的log见下面的链接👇
[Ivan97/cloud-grpc-server用mvn命令执行报错](https://gist.github.com/Ivan97/fa438b4dc69851812a0c33a1a6b227b1)

用`gradle bootRun`命令执行没有问题

**Comment by Ivan97** [comment]
maven、jdk以及系统信息如下
```
➜  grpc-spring-boot-starter git:(develop) mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T03:49:05+08:00)
Maven home: /usr/local/Cellar/maven-deluxe/3.5.3-0/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
```

**Comment by yidongnan** [comment]
@Ivan97 依赖冲突了，用最新版在试一下。

**Comment by Ivan97** [comment]
本地测试可以跑起来了

**Comment by Ivan97** [comment]
有个问题我就直接在这里问不开新issue了。。。
`INFO [cloud-grpc-server,,,] 27944`
`INFO [cloud-grpc-client,dc3c860155ff5a32,dc3c860155ff5a32,true] 27968`
日志里面中括号中的信息是在哪里输出的呢？代表的意义是什么呢？
springboot中默认的logback的${CONSOLE_LOG_PATTERN}也没有多余的字段啊。。
求指教
