### ISSUE TITLE
grpc-spring-boot-starter不支持spring-boot2.0

### ISSUE THREAD

**Issue by zhenghui317** [yidongnan/grpc-spring-boot-starter#74]
grpc-spring-boot-starter不支持spring-boot2.0，现在有没有支持2.0的计划呢？

**Comment by zchlwj** [comment]
支持啊，是不是有冲突？
如果有 试试这个。

<exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
</exclusions>
