### ISSUE TITLE
springboot2.7

### ISSUE THREAD

**Issue by jianyun** [yidongnan/grpc-spring-boot-starter#740]
有计划支持 springboot2.7 吗

**Comment by ST-DDT** [comment]
[English Translation](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/740?_x_tr_sl=auto&_x_tr_tl=en)

---

Yes. 
The next version will be build with 2.6.x though.
Is there an issue running the library with 2.7.x?

**Comment by marcindabrowski** [comment]
We are using it with spring boot 2.7, and it is OK.
But why you won't update to 2.7? Very soon it will be the last 2.x branch, so in my opinion, you should update it to 2.7.

**Comment by ST-DDT** [comment]
I would like to release one version with 2.6 and almost immedeately after a new one with 2.7.
There are some fragile out of repo dependencies with spring cloud that break with 2.7.

**Comment by ST-DDT** [comment]
We plan to release it soon (this year, probably sooner). Currently we are lacking reviews for #749
then I can tackle this refactor: [#741](https://github.com/yidongnan/grpc-spring-boot-starter/issues/741#issuecomment-1247148603) (includes #448 + #419 + #624 + #649)
which completes [2.14.0](https://github.com/yidongnan/grpc-spring-boot-starter/milestone/17) ([2.15.0](https://github.com/yidongnan/grpc-spring-boot-starter/milestone/18) with spring boot 2.7 dependencies) will be released immediately after that.

Please note: You can use the current version with Spring Boot 2.7.x already. If you encounter any please report them.

**Comment by ST-DDT** [comment]
Fixed with latest releasr.
