### ISSUE TITLE
About java pkcs8 and the OpenSSL pkcs1*

### ISSUE THREAD

**Issue by f1024557668** [yidongnan/grpc-spring-boot-starter#745]
I used the openssl to generate the server and client file,when I used them in my project.It throw an exception about this:
java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:351) ~[na:1.8.0_77]
	at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:356) ~[na:1.8.0_77]
	at sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:73) ~[sunec.jar:1.8.0_60]
	at sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237) ~[sunec.jar:1.8.0_60]
	at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165) ~[sunec.jar:1.8.0_60]
	... 28 common frames omitted
If I import the thrid jar like the bcprov-jdk15on-164.jar and bcpkix-jdk15on-164.jar,it would be OK?

**Comment by f1024557668** [comment]
I've transformed the .key file,but when run the program it throw Port xxxx was already in use.I'm sure there is no program used.

**Comment by ST-DDT** [comment]
If you post an error like this please also include at least the relevant parts of your configuration, such as cert file names.

--------------------

As for the original error. This sounds like an error where you use Java11/17 to create the keystore but use J8 to load it.
Some algorithms have been added in the later Java versions that fail on J8.
Adding bcprov/bcpkix might help to solve the issue, but that I'm not sure.
Another potential solution is to change the keystore extension as the default keystore type might not fit.

-------------------------------

As for the later error:

Please post the error message and relevant configuration.

**Comment by ST-DDT** [comment]
No feedback/information provided.
