### ISSUE TITLE
zipkin 链路client ,server没连接在一起

### ISSUE THREAD

**Issue by xiaomin0322** [yidongnan/grpc-spring-boot-starter#75]
zipkin 链路client ,server没连接在一起

**Comment by xjune123** [comment]
GrpcClientAutoConfiguration 中 
 if (bean instanceof Tracer) {
                    this.registry.addClientInterceptors(new TraceClientInterceptor((Tracer) bean, new MetadataInjector()));
                }
执行不到，你可以主动添加试试看，我这里自己加了就好了
`protected static class TraceClientAutoConfiguration {
        @Autowired
        Tracer tracer;

        @Bean
        public BeanPostProcessor clientInterceptorPostProcessor(GlobalClientInterceptorRegistry registry) {
            System.out.println(this.tracer);
            //解决调用链问题
            registry.addClientInterceptors(new TraceClientInterceptor(tracer, new MetadataInjector()));

            return new ClientInterceptorPostProcessor(registry);
        }

        private static class ClientInterceptorPostProcessor implements BeanPostProcessor {

            private GlobalClientInterceptorRegistry registry;

            public ClientInterceptorPostProcessor(
                    GlobalClientInterceptorRegistry registry) {
                this.registry = registry;
            }

            @Override
            public Object postProcessBeforeInitialization(Object bean,
                                                          String beanName)
                    throws BeansException {
                return bean;
            }

            @Override
            public Object postProcessAfterInitialization(Object bean,
                                                         String beanName)
                    throws BeansException {
                if (bean instanceof Tracer) {
                    this.registry.addClientInterceptors(new TraceClientInterceptor((Tracer) bean, new MetadataInjector()));
                }

                return bean;
            }
        }
    }`

**Comment by yidongnan** [comment]
@xiaomin0322  在 1.4.1.RELEASE 中已经 fix 了
