### ISSUE TITLE
客户端需要连接到多个GRPC服务

### ISSUE THREAD

**Issue by veione** [yidongnan/grpc-spring-boot-starter#753]
一个客户端需要连接到多个GRPC服务，这时候需要怎么处理呢，这个客户端又被其它服务端同时连接，现有的框架好像是只能支持一个服务链接，并且这个连接还是随着注册服务上线下线自动连接与断开连接。

**Comment by ST-DDT** [comment]
[English translation](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/753?_x_tr_sl=zh-TW&_x_tr_tl=en)

---------------

Please describe your usecase in a bit more detail.
- Why do you have to connect to multiple servers (of the same type?)?
- What are you doing with them? Status ping? Configuration?
- Why don't they connect to "your service"?

**Comment by veione** [comment]
For example, in the game server scenario, each server is independent, and it is necessary to obtain data from the corresponding remote service according to the server where the player is located. At this time, it is necessary to obtain the corresponding service according to the server ID.

**Comment by ST-DDT** [comment]
In that case you don't really have a fixed target so this library is limited in its abilities to help you.
Grpc Channels use EquivalentAddressGroups under the hood to target servers that are interchangeable, if you have multiple distinct servers then you have to connect to them distinctly.
You could inject the [`GrpcChannelFactory`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/GrpcChannelFactory.java) and request a Channel from it to connect to the new server, but other than that there is not much this library can do for you.

We plan to extend our feature set a bit for this usecase by splitting the injection logic from the stub creation logic so you could directly request a certain stub for a connection and allow management of connections. See more details here: https://github.com/yidongnan/grpc-spring-boot-starter/issues/741#issuecomment-1247148603

I don't know enough about your setup/requirements to give you advice on how this could be improved/require less coding.

**Comment by veione** [comment]
Thanks for your reply, I'm going to look at the code first and then expand it myself.
