### ISSUE TITLE
Call a remote api

### ISSUE THREAD

**Issue by akanzari** [yidongnan/grpc-spring-boot-starter#761]
**The context**

I have a spring boot application, for the moment i call a remote soap api using web-services and http api using webclient.

`payerConnector.callWebService(payerConnector.getDefaultUri(), jAXBElement);`

`webClient.post().uri(url).bodyValue(evt).retrieve().bodyToMono(BillerResponse.class).block();`

**The question**

How can i change the call of these 2 apis by grpc, knowing that the remote apis are not using spring boot and grpc.
If there's an example, please provided.

**Comment by ST-DDT** [comment]
If the target server does not support grpc, then you cannot call it with grpc.
You have to request grpc support from the service provider.

Note:
- SOAP is XML* (text), 
- REST is JSON* (text)
- but grpc is protobuf* (binary)

*usually

so these aren't compatible.

If you wish to start with grpc you might want to try our getting started docs:
https://yidongnan.github.io/grpc-spring-boot-starter/en/server/getting-started.html
https://yidongnan.github.io/grpc-spring-boot-starter/en/client/getting-started.html

You can find our examples here:
https://github.com/yidongnan/grpc-spring-boot-starter/tree/master/examples
