### ISSUE TITLE
是否支持K8S的服务注册与发现

### ISSUE THREAD

**Issue by f1024557668** [yidongnan/grpc-spring-boot-starter#769]
如果要使用K8S原生的服务注册与发现的话，是否可以直接用现有的配置，然后使用dns://？还是说需要自己扩展解析器？

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/769?_x_tr_sl=zh-TW&_x_tr_tl=en)

-----------

Kubernetes creates DNS entries for services, so you can use them directly (you might have to specify a port).

For more information refer to our documentation:

- https://yidongnan.github.io/grpc-spring-boot-starter/en/kubernetes.html
- Or WIP: https://github.com/yidongnan/grpc-spring-boot-starter/blob/document-zh-cn/docs/zh-CN/kubernetes.md

Does this answer your questions? Are there parts that need more explanations?
