### ISSUE TITLE
server不使用默认port，client怎么找到port？

### ISSUE THREAD

**Issue by lcb1208** [yidongnan/grpc-spring-boot-starter#78]

**Comment by zhenghui317** [comment]
把你的服务端注册到eureka，客户端在Channel上注解服务名称就可以正常访问了。例子里面有，你可以找下。
@yidongnan 还是快点把支持2.0吧，而且现在zipkin Client和Server确实没有链接到一起，能否一起解决下。

**Comment by yidongnan** [comment]
@zhenghui317 我这周看看你说的问题和2.0的事情。

**Comment by chuanchenzz** [comment]
作者是将port放到springBoot中的metaData中的map里面,key是gRpc

**Comment by lcb1208** [comment]
结案了，自己理解的有问题
