### ISSUE TITLE
CallCredentials bean defined but not used

### ISSUE THREAD

**Issue by jpbassinello** [yidongnan/grpc-spring-boot-starter#781]
**The context**

I have a simple configuration with a single grpc-server and a grpc-client, both using spring-security.
I am trying to use exactly what the docs say to configure a CallCredentials @Bean:

If you have exactly one CallCredentials in your application context, we’ll automatically create a StubTransformer for you and configure all Stubs to use it. If you wish to configure different credentials per stub, then you use our helper methods in the [CallCredentialsHelper](https://javadoc.io/page/net.devh/grpc-client-spring-boot-autoconfigure/latest/net/devh/boot/grpc/client/security/CallCredentialsHelper.html) utility.

**The bug**

The CallCredentials @Bean is not getting used by the stub transformation. Actually, debugging the client call, I can see it wrapped into the `callOptions` but never gets called.
A breakpoint in the lambda below is never reached:
`
@Bean
CallCredentials bearerAuthForwardingCredentials() {
    return CallCredentialsHelper.bearerAuth(() -> KeycloakSecurityContext.getTokenString());
}
`

**Stacktrace and logs**

No stacktrace. The grpc-server responds UNAUTHENTICATED

**Steps to Reproduce**

**The application's environment**

Which versions do you use?
* Spring (boot): 2.7.5
* grpc-java: 1.42.2
* grpc-spring-boot-starter: 2.13.1.RELEASE
* java: version + architecture (64bit?) 17 - 64
* spring-security-oauth2-resouce-server:5.7.4

**Additional context**

**Comment by ST-DDT** [comment]
2.31.1 has a bug in that method that doesn't call `get` on the supplier, sorry for that:

https://github.com/yidongnan/grpc-spring-boot-starter/blob/v2.13.1.RELEASE/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java#L195

Please use the implementation of the method as a workaround:

https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java#L195

Also please check whether the following line gets called during the call:

https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java#L276

**Comment by jpbassinello** [comment]
Thank you. It worked.
