### ISSUE TITLE
请问如何根据消息体内容选择服务调用呢？

### ISSUE THREAD

**Issue by HKMV** [yidongnan/grpc-spring-boot-starter#793]
老师您好，我现在有个场景是需要根据调用时参数对象值，进行选择要调用的服务。

我的想法是自己写一个自定义选择策略，但是琢磨了半天，没找到怎么从选择方法中获取参数对象，请问有什么方法可以取到吗？

或者您有更好的方案吗？

期待您的指点。

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/793?_x_tr_sl=zh-TW&_x_tr_tl=en)

----

Do you have a fixed set of targets (prod, dev, stage) that you have to switch between or is it generic?

Currently there is no easy way to do that only:

- inject the channel factory,
- create/get a channel based on the given parameter
- and create a stub for it

But, then there is no injection support for the stub/channel.

I plan to create a injection factory: https://github.com/yidongnan/grpc-spring-boot-starter/issues/741#issuecomment-1247148603

Then you can do:

- inject the GrpcClientInjector
- call `grpcClientInjector.get("targetName", Stub.class)`

Does this answer your question?

**Comment by HKMV** [comment]
> [English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/793?_x_tr_sl=zh-TW&_x_tr_tl=en)
> 
> ----
> 
> Do you have a fixed set of targets (prod, dev, stage) that you have to switch between or is it generic?
> 
> Currently there is no easy way to do that only:
> 
> - inject the channel factory,
> - create/get a channel based on the given parameter
> - and create a stub for it
> 
> But, then there is no injection support for the stub/channel.
> 
> I plan to create a injection factory: https://github.com/yidongnan/grpc-spring-boot-starter/issues/741#issuecomment-1247148603
> 
> Then you can do:
> 
> - inject the GrpcClientInjector
> - call `grpcClientInjector.get("targetName", Stub.class)`
> 
> Does this answer your question?

不是固定的，调用的服务端是会变化的，需要在监听到服务变化时，更新要调用的地址；感谢您提供的思路我去测试一下。

**Comment by HKMV** [comment]
> 

暂时已通过自定义DiscoveryClientResolverFactory实现，期待2.15.0版本的GrpcClientInjector实现，使用GrpcClientInjector应该可以更好的解决我的问题。

**Comment by ST-DDT** [comment]
Thanks for your feedback.
