### ISSUE TITLE
Grpc Server never starts when using Spring Boot 3.0.0

### ISSUE THREAD

**Issue by lewimuchiri** [yidongnan/grpc-spring-boot-starter#795]
**The context**
```java
//build.gradle.kts

plugins {
    id("org.springframework.boot") version "3.0.0"
}

dependencies {
    implementation(platform("org.springframework.boot:spring-boot-dependencies:3.0.0"))
    implementation("org.springframework.boot:spring-boot-starter")

    implementation("net.devh:grpc-server-spring-boot-starter:2.14.0.RELEASE")
}

//CarService.java

@GrpcService
public class CarServiceGrpcImpl extends CarServiceGrpc.CarServiceImplBase {
    @Override
    public void getCars(CarRequest request, StreamObserver<CarResponse> responseObserver) {
        CarResponse.Builder builder = CarResponse.newBuilder();
    
        ...
        responseObserver.onNext(builder.build());
        responseObserver.onCompleted();
    }
}
```

**The bug**
When you run the app, the Grpc server never gets started. When I downgrade to Spring Boot 2.7.5, it works as expected.

**Stacktrace and logs**

Is there a stacktrace or a hint in the logs? (very important)
Screenshots work as well, but don't screenshot your logs.

**The application's environment**

* Spring (boot): 3.0.0
* grpc-spring-boot-starter: 2.14.0.RELEASE
* java: version + architecture (64bit?): Java-17, 64-bit

**Comment by ST-DDT** [comment]
Currently Spring-Boot v3.0.0 is not yet supported.

Use this as a workaround: https://github.com/yidongnan/grpc-spring-boot-starter/pull/775#issuecomment-1329023335

**Comment by lewimuchiri** [comment]
Thank you. Will use the workaround in the meantime

**Comment by amithkumarg** [comment]
Since the #775 has been merged, this issue can be closed?
