### ISSUE TITLE
How to custome the thread pool executor?

### ISSUE THREAD

**Issue by sunway1988** [yidongnan/grpc-spring-boot-starter#797]
**The context**

The deault thread pool executor is `CachedThreadPool`, it will new too many threads when a large number of requests comming, then the CPU or Memory may ge exhausted.

**The question**

I did not find the config from document. So execuse me to ask how to custome the thread pool executor?

**Stacktraces and logs**

Not involved

**The application's environment**

Not involved

**Additional information**

Not involved

**Comment by ST-DDT** [comment]
https://github.com/yidongnan/grpc-spring-boot-starter/issues/434#issuecomment-902733243

Does that answer your question?

**Comment by sunway1988** [comment]
> [#434 (comment)](https://github.com/yidongnan/grpc-spring-boot-starter/issues/434#issuecomment-902733243)
> 
> Does that answer your question?

Great! Thanks

**Comment by HunterSherms** [comment]
@ST-DDT FYI your link is broken for anyone who stumbles upon this today.

**Comment by ST-DDT** [comment]
Try this one:

- https://github.com/grpc-ecosystem/grpc-spring/issues/434#issuecomment-902733243
