### ISSUE TITLE
在使用Stream的情况下，服务端如何监控客户端断开了？

### ISSUE THREAD

**Issue by 792620616** [yidongnan/grpc-spring-boot-starter#800]
**The context**

What do you wish to achieve?

**The question**

What's the problem? What's not working? What's missing and why do you need it?

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot):
* grpc-java:
* grpc-spring-boot-starter:
* java: version + architecture (64bit?)
* Other relevant libraries...

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment]
This question is not related to this library and more related to grpc-java.
Please ask these questions there.

a) https://github.com/grpc/grpc-java/issues/6456#issuecomment-557344313
b) https://groups.google.com/g/grpc-io/c/quToVM4NhdQ/m/c-w48nfBAgAJ
