### ISSUE TITLE
How to handle the RejectedExecutionException from server executor pool?

### ISSUE THREAD

**Issue by sunway1988** [yidongnan/grpc-spring-boot-starter#801]
**The context**

I am trying to replace grpc server default executor(CachedThreadPool) with a self-defined ThreadPoolExecutor, which will throw RejectedExecutionException when it is EXHAUSTED. In that situation, a StreamException occurs in NettyServerHandler.

**The question**

My question is how to handle the RejectedExecutionException from server executor pool. I tried to user @GrpcAdvice, but it did'nt work. Execuse me to ask this question, I am a newbie to grpc-java.

**Comment by ST-DDT** [comment]
No feedback or information provided.
