### ISSUE TITLE
Changing server address at runtime based on user input

### ISSUE THREAD

**Issue by Philipp-p** [yidongnan/grpc-spring-boot-starter#817]
**The context**

I develop a CLI client that needs to change the target server at runtime based on a user input.

**The question**

I implemented based on #519 a custom ```NameResolverProvider``` that is supposed to target only one server based on user input and did not specify any server in my application.properties:

```java
public class FixedStaticNameResolverProvider extends NameResolverProvider {
  private static final String SCHEME = "static";
  private static String DEFAULT_HOST;
  private final StaticNameResolverProvider provider = new StaticNameResolverProvider();

  public FixedStaticNameResolverProvider(String defaultHost) {
    this.DEFAULT_HOST = "static://" + defaultHost + ":6565";
  }

  @Override
  public NameResolver newNameResolver(URI targetUri, Args args) {
    try {
      System.out.println("targetUri: " + targetUri);
      System.out.println("args: " + args);

      NameResolver dnsNameResolver = provider.newNameResolver(new URI(DEFAULT_HOST), args);
      return dnsNameResolver;
    } catch (URISyntaxException e) {
      log.error("NameResolver creation failed", e);
      return null;
    }
  }

  @Override
  protected boolean isAvailable() {
    return true;
  }

  @Override
  protected int priority() {
    return 10; // higher than everything else
  }

  @Override
  public String getDefaultScheme() {
    return SCHEME;
  }
}
```
Here ```StaticNameResolverProvider``` is [`StaticNameResolverProvider`](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/StaticNameResolver.java).

Then I create and register it based on https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#custom-nameresolverprovider as a bean with my application context, where ```grpcServerAddress``` is my user input (for my test case localhost):

```java
appContext.registerBean("tmpServer", NameResolverProvider.class, () -> new FixedStaticNameResolverProvider(grpcServerAddress));
```

I then make an gRPC call. It does never execute my prints and therefore never invokes ```newNameResolver```. Instead it throws this exception:

```java
io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host grpc-server
```

The same happens if I follow the documentation of grpc-java and register my ```NameResolverProvider``` like in the code below and execute a gRPC call.

```java
NameResolverProvider nameResolverProvider = new FixedStaticNameResolverProvider(grpcServerAddress);
NameResolverRegistry.getDefaultRegistry().register(nameResolverProvider);
```

My question is if I am simply overlooking something or if I have to achieve this functionality by hot reloading my spring application properties and then refresh my application context? I have also seen #753 and #793, is this the way and I have to create a new channel for every request, since the Discovery used in #793 seems not to be the right solution for my problem?

**The application's environment**

Which versions do you use?
* Spring (boot): 2.6.13
* grpc-java: 1.51.0
* grpc-spring-boot-starter: 2.14.0.RELEASE
* java: 18 64bit

**Additional information**

* Did it ever work before?

The CLI client works fine if a server address is specified by the application.properties file. Even if the code above is included,  it still targets the server stated in the application.properties file and everything works, but also in this case my prints in ```FixedStaticNameResolverProvider``` are never executed.

Any input or help is highly appreciated!

**Comment by ST-DDT** [comment]
There are two potential causes for this:

The registry doesnt accept your name resolver for whatever reason, you might want to debug into the name resolver registry for more insights.

The second possibility is that the bean is registered to late and thus is never considered for the resolution.
Please check the bean initialization order in comparison to the grpc channel factory/injection.

**Comment by Philipp-p** [comment]
Thanks for the quick answer! I'll look into this tomorrow.

**Comment by Philipp-p** [comment]
> There are two potential causes for this:
> 
> The registry doesnt accept your name resolver for whatever reason, you might want to debug into the name resolver registry for more insights.

I debugged into the registry, it does accept the resolver changes the default scheme for dns to static automatically and so on.

> The second possibility is that the bean is registered to late and thus is never considered for the resolution. Please check the bean initialization order in comparison to the grpc channel factory/injection.

The bean is definitely way later then the grpc channel factory/injection. I need to boot up my CLI and if the user decides, for some reason, to contact another server during the use of the CLI I need to change the target server of the CLI. It looks like a restart of the CLI with a changed application.properties seems the way here or is the solution from #753 the right way?

**Comment by ST-DDT** [comment]
> > The second possibility is that the bean is registered to late and thus is never considered for the resolution. Please check the bean initialization order in comparison to the grpc channel factory/injection.
> 
> The bean is definitely way later then the grpc channel factory/injection.

The name resolver has to be registered by the time the [`NameResolverFactory` returned/powered by the `NameResolverRegistry`](https://grpc.github.io/grpc-java/javadoc/io/grpc/NameResolverRegistry.html#asFactory--) is invoked first. (Which I think happens during the first use of the stub/channel)

There are two ways to achieve that:
- First register the related beans earlier
- Register your `NameResolverProvider` via java [ServiceConfig](https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-client-spring-boot-autoconfigure/src/main/resources/META-INF/services/io.grpc.NameResolverProvider) and use static fields to set the current target.

Please make sure that you set the correct target to the `NameResolver` created by your `NameResolverFactory`.
https://github.com/yidongnan/grpc-spring-boot-starter/blob/aa230f84207b2407fd45a9ff7a509647830f4e94/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/StaticNameResolver.java#L81

Creating the stub on demand sounds like a good idea as well, since this allows you to use all registered schemes to resolve grpc server addresses (instead of only static/ips).

**Comment by Philipp-p** [comment]
Thanks for the insights! I'll try it out!

**Comment by ST-DDT** [comment]
Just for FFR: I plan to simplify the injection of grpc channels/stubs in the future by providing a specialized injection/provider bean:

https://github.com/yidongnan/grpc-spring-boot-starter/issues/741#issuecomment-1247148603
