### ISSUE TITLE
Use channelz with grpc spring boot starter

### ISSUE THREAD

**Issue by saumyasuhagiya** [yidongnan/grpc-spring-boot-starter#820]
**The context**

Get insights of channels and subchannels.

**The question**

How can we integrate channelz with grpc spring boot starter?
I am new to grpc and this project. Not sure if I have missed any documentation or straight forward method to integrate both.

**Stacktraces and logs**

NA

**The application's environment**

Which versions do you use?
* Spring (boot): 2.5.8
* grpc-java: 1.51
* grpc-spring-boot-starter: 2.14
* java: version + architecture (64bit?)
* Other relevant libraries...

**Additional information**

* Did it ever work before? No
* How can we reproduce it? No
* Do you have a demo? No

**Comment by ST-DDT** [comment]
In order to help you, I first need to know, how you use `channelz` without this library/in general.
Could you give me a some code examples?

**Comment by saumyasuhagiya** [comment]
@ST-DDT 
Thanks for quick response.

This is a short introduction to channelz.
https://grpc.io/blog/a-short-introduction-to-channelz/

I was able to find simple implementation here.
https://github.com/helloworlde/grpc-java-sample/blob/main/channelz/src/main/java/io/github/helloworlde/grpc/ChannelzServer.java

**Comment by ST-DDT** [comment]
It should be as easy as adding the folling to your configuration beans:

````java
// @Bean
@GrpcService
ChannelzService channelzService()
    return ChannelzService.newInstance(100);
}
````
