### ISSUE TITLE
Upgrade Micrometer to latest release

### ISSUE THREAD

**Issue by dsyer** [yidongnan/grpc-spring-boot-starter#828]
The version of Micrometer currently building with this project is old and doesn't contain the new tracing/observation APIs. If we upgrade to 1.10.3 (or later) there shouldn't be any problems for the build or for existing users because existing APIs are unchanged, and it will clear a path to supporting Spring Boot 3 properly.

**Comment by ST-DDT** [comment]
See https://github.com/yidongnan/grpc-spring-boot-starter/pull/829#issuecomment-1398815889
