### ISSUE TITLE
gRPC Server响应延迟5s

### ISSUE THREAD

**Issue by charlesbabyxu** [yidongnan/grpc-spring-boot-starter#833]
使用是2.12.0-release版本的gRPC server starter构建
一个简单的接口调用，正常响应时间是15ms以内，但是会间歇性、在一个长时间轴上不规律的分布零星调用响应时间需要5s左右

5s数值非常奇怪，我想知道是什么原因导致的。

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/833?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

I dont know. Your questions is vage and doesnt contain much details.

If your requests are very rare I could imagine that the TCP connection is closed and that the client has to re-resolve the server address or that there is other network overhead.

Please check for slow:

- DNS/Servive-Registries
- TCP Handshakes
- Server Responses (Some cloud providers shut the service down temporirly if it isnt used, or the server has the same problem as the client and has to re-establish the connections as well)

Does that help you?

**Comment by charlesbabyxu** [comment]
> [English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/833?_x_tr_sl=zh-TW&_x_tr_tl=en)
> 
> I dont know. Your questions is vage and doesnt contain much details.
> 
> If your requests are very rare I could imagine that the TCP connection is closed and that the client has to re-resolve the server address or that there is other network overhead.
> 
> Please check for slow:
> 
> * DNS/Service-Registries
> * TCP/SSL Handshakes
> * Server Responses (Some cloud providers shut the service down temporirly if it isnt used, or the server has the same problem as the client and has to re-establish the connections as well)
> 
> You could try Wireshark or a similar tool to narrow down the cause.
> 
> Does that help you?

我会尝试下你提供的建议，谢谢。
之前也考虑过netty工作线程的可能性。

**Comment by charlesbabyxu** [comment]
![image](https://user-images.githubusercontent.com/59246908/216938588-3ccfb688-4cce-474f-923f-9ea7dd624c36.png)

**Comment by bingyang001** [comment]
By default, there is 1 I/O thread and available CPU working threads. In theory, it is unlikely to be a problem with Netty. You can dump the thread stack and see what is causing the blockage
