### ISSUE TITLE
我想在gRPC 服务端使用ServerInterceptor 记录请求参数，该怎么做？

### ISSUE THREAD

**Issue by gebizhuxiaowang** [yidongnan/grpc-spring-boot-starter#843]
ServerInterceptor 怎么才能获取到请求参数？ 像servlet filter那样，通过request流获取requstbody

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/843?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

> How can ServerInterceptor get the request parameters? Like servlet filter, get requestbody through request flow

By adding a ServerCallListener in the interceptor:

Like this:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/d4ebf476a8e1c4ff4e41cc3346bd8a53c0e259c9/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerInterceptor.java#L131-L148
https://github.com/yidongnan/grpc-spring-boot-starter/blob/d4ebf476a8e1c4ff4e41cc3346bd8a53c0e259c9/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerCallListener.java#L61-L65

These questions are unrelated to this library. Please ask them on stackoverflow or grpc-java directly.
