### ISSUE TITLE
支持springboot3.0

### ISSUE THREAD

**Issue by lsm1998** [yidongnan/grpc-spring-boot-starter#846]
有没有支持springboot3.0的计划？

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/846?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

Yes, in the meantime use this workaround: https://github.com/yidongnan/grpc-spring-boot-starter/pull/775#issuecomment-1329023335
