### ISSUE TITLE
如何去动态创建channel

### ISSUE THREAD

**Issue by saiyujs** [yidongnan/grpc-spring-boot-starter#848]
我有多个服务端，其中有10个服务端在机房A，服务名叫xxxx-A；有另外10个服务端在机房B，服务名叫xxx-B。
需求有的请求必须要请求服务xxx-A，有的请求必须要请求服务xxx-B。
以后可能还会有机房C，所以如何可以动态创建channel？
其功能就是类似rest+@LoadBalanced，可以通过我传入的服务名，动态选择channel。
感谢回复！！

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/848?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

Currently, there is no easy way to do that.
One way is creating the Channel via the GrpcChannelFactory and create the Stub yourself in the calling code (potentially cached).
We plan to make the stubs directly accessible/requestable as described here: https://github.com/yidongnan/grpc-spring-boot-starter/issues/741#issuecomment-1247148603

Closing as duplicate.

**Comment by saiyujs** [comment]
![image](https://user-images.githubusercontent.com/62423061/220566645-d1df39ac-26cc-4549-be86-65d0dcb04614.png)
![image](https://user-images.githubusercontent.com/62423061/220566692-ab9e51e3-6a5a-42df-bdd1-800e07bb0809.png)
分享一下解决方法。
通过https://github.com/yidongnan/grpc-spring-boot-starter/issues/741#issuecomment-1247148603里面的架构图，得到启发，thx!!!
