### ISSUE TITLE
GrpcClient的断线重连

### ISSUE THREAD

**Issue by f1024557668** [yidongnan/grpc-spring-boot-starter#851]
你好，请问，server端突然宕机了，然后重启后，客户端依然还是报未连接。客户端有什么配置可以保持重连吗？

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/851?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

AFAIK the client should automatically reconnect.
I noticed that some service-registries are kind of slow in detecting service unavailability and thus the requests get sent to the old server for up to a minute or so. If I remember my integration tests with these systems correctly, then nacos was the fastest.
If you dont use a service discovery/discovery client, then I dont know the reason.
Please ask grpc-java directly.

**Comment by f1024557668** [comment]
The runtime environment was k8s,and the service with the DNS discovery.And now I found that the server been restarted,but the client was always UNAVAILABLE.I found the class ManagedChannelImplBuilder,if I use this class to set the method which names maxRetryAttempts,it will work?

**Comment by ST-DDT** [comment]
> but the client was always UNAVAILABLE

If it is always unavailable that sounds like the address/port is wrong.

**Comment by f1024557668** [comment]
Because I've not use the ManagedChannelImplBuilder,and I see the default setting retry times was five.So I guess maybe the server  was cost too long time that the client have retried the limit?
