### ISSUE TITLE
loadblance bug?

### ISSUE THREAD

**Issue by saiyujs** [yidongnan/grpc-spring-boot-starter#854]
version: grpc-client-spring-boot-starter-2.13.1.RELEASE

i do the test. 
i have one client program, two server program(server program--same serverName, different ip)

two ways to create channel:

````java
Channel channel = ManagedChannelBuilder.forTarget("discovery:///" + serverName).defaultLoadBalancingPolicy("round_robin").usePlaintext().build();
Channel channel = ManagedChannelBuilder.forTarget("static://hostA:port,hostB:port").defaultLoadBalancingPolicy("round_robin").usePlaintext().build();
````

i send 10 request from client to server. 
first test 10 request loadblance fail, all request on hostA，but after first test, then second test, third test.......request loadblance success
the test result by two ways of create channel are same. this is a bug?

**Comment by ST-DDT** [comment]
I dont understand your test setup/question.
What is the expected result from the discovery-service. Is it the same as the other server?

Please also post your error logs.

**Comment by saiyujs** [comment]
![image](https://user-images.githubusercontent.com/62423061/222612530-832392fc-48a3-4e3e-a567-f44dc601a9c0.png)

grpc-client
![image](https://user-images.githubusercontent.com/62423061/222612594-daa7ca03-ca56-4d94-8289-a422532bfe99.png)
![image](https://user-images.githubusercontent.com/62423061/222612694-7f57b7c3-b76e-4adc-91ca-f47794f0a912.png)

when grpc-server receive request will print log.

my expected result : if send 10 request, hostA grpc-server receive 5 request(print 5 log),  hostB grpc-server receive 5 request(print 5 log)
actuality result: first time to wget /test, hostA grpc-server receive 10 request(10 log), hostB grpc-server receive 0 request(0 log)
                         second time to wget /test, hostA grpc-server receive 5 request(5 log),  hostB grpc-server receive 5 request(5 log)

first time loadblance fail

**Comment by saiyujs** [comment]
my test result: when first time request finished, await 10 sec, loadblance will be working
![image](https://user-images.githubusercontent.com/62423061/222615276-1431441d-850a-4acc-853c-598b82f76952.png)

**Comment by ST-DDT** [comment]
> first time loadblance fail

Please show me the error log.

**Comment by saiyujs** [comment]
no error log.....

**Comment by ST-DDT** [comment]
So only the load balancing part fails getting host a 100% of the requests?

Does this happen regardless of whether you are using [dns, static, discovery schemes](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/configuration.html#choosing-the-target)?

**Comment by saiyujs** [comment]
yes，I just used static and discovery to test。
It feels like the host address synchronization was incomplete at the beginning。so only the load balancing part fails

**Comment by ST-DDT** [comment]
Please also test the dns one.
If it is also affected please ask grpc-java directly for help as that is outside of my knowledge.

**Comment by saiyujs** [comment]
https://github.com/grpc/grpc-java/issues/9936#issuecomment-1457404647

**Comment by saiyujs** [comment]
thank you very much!!!
