### ISSUE TITLE
gRPC Server unavailable just after restart/deployment

### ISSUE THREAD

**Issue by RupavJain** [yidongnan/grpc-spring-boot-starter#863]
**The context**

What do you wish to achieve?
Reestablish the connection with gRPC Server after Server is restarted (or new instance gets deployed)

**The question**

What's the problem? What's not working? What's missing and why do you need it?
Once Server is restarted, Client which had already established channel with the server, now unable to reach to client - and gives unavailability error.

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot): 2.7.5
* grpc-java: 
* grpc-spring-boot-starter: 2.14.0.RELEASE
* java: Java 11
* Other relevant libraries...

**Additional information**

* Did it ever work before?
No
* How can we reproduce it?
By Restarting the server (and ensuring client is hitting the server just after restarting)
* Do you have a demo?

**Comment by ST-DDT** [comment]
How do you access the server/resolve the address?
It is likely that I'm unable to help you with this issue as this might have something to do on how grpc java handles connections.
You might have to configure connection timeouts or request retry and for that you have to ask on the grpc-java repo or stackoverflow for help.
If there is a property for that, that I could add support for please let me know.

**Comment by ST-DDT** [comment]
Looks like there is nothing we can do here.

**Comment by gaoxingliang** [comment]
add the below configurations will help:
```
      enableKeepAlive: true
      keepAliveWithoutCalls: true
```
