### ISSUE TITLE
support connections num in metrics

### ISSUE THREAD

**Issue by zhaomoran** [yidongnan/grpc-spring-boot-starter#866]
**The problem**

We are missing metric data for the current number of connections.

**The solution**
Definition `TransportFilter` to monitor transportReady and transportTerminated.

**Comment by ST-DDT** [comment]
The metric implementation has been moved to micrometer.
Please open an issue there and I will implement support for it here once it is merged.

**Comment by zhaomoran** [comment]
@ST-DDT I just found out that it rely on micrometer.The grpc implementation is also you.I will work on a micrometer.Thanks!

**Comment by ST-DDT** [comment]
Yes, the original micrometer implementation was created/published by me, but in the meantime they superseded(?)/extended upon it with their `Observable`(?)/different variant.

If you open an issue there, please link it here, so I can subscribe to it and keep up to date with the changes.

**Comment by zhaomoran** [comment]
https://github.com/yidongnan/grpc-spring-boot-starter/issues/866#issue-1628885619

**Comment by ST-DDT** [comment]
Thanks. I will integrate the new beans when this gets implemented.

**Comment by ST-DDT** [comment]
I subscribed to the linked issue and will close zhis issue until the linked issue gets implemented.
