### ISSUE TITLE
客户端无法发起经过(Kong-gateway)网关的请求-The gRPC client can not request a server via a Kong-gateway

### ISSUE THREAD

**Issue by LaiJinwen** [yidongnan/grpc-spring-boot-starter#872]
**The context**

我期望的是：
  gRPC -client > Kong-gateway(gRPC reverse proxy) > gRPC -server,（client and server are not in the same network environment.）
client 和 server是在不通区域的网络，彼此不互联的。全链路的调用都是gRPC 方式。
The full request chain are using gRPC method.

**The question**
网络是正常的。
但是现在我本机gRPC client 中@GrpcClient("be-stamp-app")本地ip地址的stab能正常发起调用，然而@GrpcClient("kong-gateway")使用网关的域名时候就会报错io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 302 ！
Network connection are ok.
Now, in my laptop environment , When I use @GrpcClient("be-stamp-app") (static ip address), the gRPC client can request correctly , however , when i use @GrpcClient("kong-gateway") (Kong-gateway domain address), i get "io.grpc.StatusRuntimeException: NKNOWN: HTTP status code 302 "

Important ! 
When I use @GrpcClient("kong-gateway") to request service via Kong-gateway, I do not see any access logs in Kong-gateway`s pods (The kong-gateway is running correctly, I can see access logs when i send a gRPC request using Kreya). 
As a result, I think mostly there is some logic function which is in-depth and imperceptible in gRPC client.

**Stacktraces and logs**

io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 302
invalid content-type: null
trailers: Metadata(:status=302,location=https://XXXXXXXXXXXXXXXXXXXXXX/demo.AuthDemo/login0,cache-control=no-cache,content-length=0)
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at com.etax.common.grpc.sdk.AuthDemoGrpc$AuthDemoBlockingStub.login0(AuthDemoGrpc.java:231)
        ..............................................

**The application's environment**

Which versions do you use?
* Spring (boot):3.0.4
* grpc-java:1.51.1
* grpc-spring-boot-starter:2.14
* java: version + architecture (64bit?) JDK17
* Other relevant libraries...

**Additional information**

* Did it ever work before? My first time to try.

**Comment by ST-DDT** [comment]
Are you sure the Kong-gateway is a grpc service and you are connecting to the right endpoint?

**Comment by LaiJinwen** [comment]
> Are you sure the Kong-gateway is a grpc service and you are connecting to the right endpoint?

Yes,Because I use Kreya to send a gRPC request to Kong-gateway and get the response I want.
Further, In Kong-gateway, the service and route are set to gRPC method and there is no plugin.
Route config detail:

{
  "name": "FeStampingRoutes",
  "path_handling": "v0",
  "protocols": [
    "http",
    "https"
  ],
  "service": {
    "id": "6d611b7c-c636-4fc4-ab08-f4c089a9c92c",
    "name": "FeStampingGrpc"
  },
  "regex_priority": 0,
  "created_at": 1678095024,
  "request_buffering": true,
  "response_buffering": true,
  "id": "ecda898c-fa14-4883-a2e2-48b4b0dd890a",
  "strip_path": false,
  "https_redirect_status_code": 426,
  "preserve_host": false,
  "updated_at": 1680166254,
  "paths": [
    "/demo.AuthDemo/"
  ]
}

Service config detail :

{
  "enabled": true,
  "retries": 5,
  "name": "FeStampingGrpc",
  "port": 20001,
  "protocol": "grpc",
  "connect_timeout": 60000,
  "read_timeout": 60000,
  "id": "6d611b7c-c636-4fc4-ab08-f4c089a9c92c",
  "host": "xxxxxxxxxxxxxx",
  "updated_at": 1678949465,
  "write_timeout": 60000,
  "created_at": 1678094821
}

**Comment by ST-DDT** [comment]
> trailers: Metadata(:status=302,location=https://xxxxxxxxxxxxxxxxxxxxxx/demo.AuthDemo/login0,cache-control=no-cache,content-length=0)

That looks like you get redirected to a login endpoint. grpc does not support redirects, so you have to pass the auth credentials directly with the request. See also our docs: [Client-Authentication](https://yidongnan.github.io/grpc-spring-boot-starter/en/client/security.html#authentication)

**Comment by LaiJinwen** [comment]
> so you have to pass the auth credentials directly with the request
Further, I add some important description !

I make it clear that "xxxxxxxxxxxxxxx" is my forwarder domain name, and "/demo.AuthDemo/login0" is my forwarded gRPC service.
As you said, I will  try finding some redirct logic in gRPC client or Kong-gateway.

**Comment by ST-DDT** [comment]
You can try grpcurl as an alternative client.
That might narrow the error to one component or the other or a client configuration issue.
