### ISSUE TITLE
grpc-spring-boot-starter支持 SSL 单向认证吗？

### ISSUE THREAD

**Issue by tclugao** [yidongnan/grpc-spring-boot-starter#893]
**The context**

What do you wish to achieve?

**The question**

What's the problem? What's not working? What's missing and why do you need it?
例如 client 根据配置的根证书 去connect服务器端（服务端配置相同的根证书），服务器端返回给客户端自己的公钥的证书，然后client去验证证书合法性？我看文档上没有介绍到这一点

**Stacktraces and logs**

Do you have any relevant stacktraces or logs of your attempts?

**The application's environment**

Which versions do you use?
* Spring (boot):
* grpc-java:
* grpc-spring-boot-starter:
* java: version + architecture (64bit?)
* Other relevant libraries...

**Additional information**

* Did it ever work before?
* How can we reproduce it?
* Do you have a demo?

**Comment by ST-DDT** [comment]
Yes

https://yidongnan.github.io/grpc-spring-boot-starter/en/server/security.html#enable-transport-layer-security
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/authentication/SSLContextGrpcAuthenticationReader.java

**Comment by tclugao** [comment]
oh, I also read this doc, but my server is implemented by another language: elixir, and grpc server is configured by server.crt and server.key and  ca.pem(which is root certificate)， our elixir grpc client configured the sam ca.pem(root certificate), in fact I want to consult how to configure java grpc client use ca.pem like elixir grpc client. I only found the config:
grpc.client.__name__.security.clientAuthEnabled=true
grpc.client.__name__.security.certificateChain=file:certificates/client.crt
grpc.client.__name__.security.privateKey=file:certificates/client.key
in the doc https://yidongnan.github.io/grpc-spring-boot-starter/en/client/security.html，
but i am not sure this will work for our case due to this is not configuring the ca.pem

**Comment by ST-DDT** [comment]
Sorry, I'm not sure what you are asking for exactly: 
1. You have a single pem that contains both the private key and the actual certificate and need a way to configure this lib with it?
2. Or you have a custom root certificate and need the client to accept that?

For 2. Have a look here: https://yidongnan.github.io/grpc-spring-boot-starter/en/client/security.html#trusting-a-server
