### ISSUE TITLE
Spring Boot 3 support?

### ISSUE THREAD

**Issue by SledgeHammer01** [yidongnan/grpc-spring-boot-starter#900]
Hi, is there going to be a Spring Boot 3 version?

**Comment by ST-DDT** [comment]
Please note that Spring Boot is already supported via workaround: https://github.com/yidongnan/grpc-spring-boot-starter/pull/775/files
(not released yet, just add the files yourself)

Duplicate of https://github.com/yidongnan/grpc-spring-boot-starter/issues/778
