### ISSUE TITLE
How to achieve load balancing

### ISSUE THREAD

**Issue by Layfolk-zcy** [yidongnan/grpc-spring-boot-starter#908]
**The postman call does not implement load balancing.The servers of both GRPCS start before the clients**

![image](https://github.com/yidongnan/grpc-spring-boot-starter/assets/59356890/57a1e3a3-0655-4669-957f-bc832ab96c16)
![image](https://github.com/yidongnan/grpc-spring-boot-starter/assets/59356890/c68165f3-5342-4d8b-9f1b-ebf2f2cf481c)

**result is constant.**
![image](https://github.com/yidongnan/grpc-spring-boot-starter/assets/59356890/2e6b705c-9a9a-4f17-a4a9-abb27df5712e)

**Comment by ST-DDT** [comment]
Postman doesnt need load balancing. If your call is like this `Postman -RestApi-> Server -grpc-> ServerN` and you want the load balancing to happen between the servers. One important thing to check is whether `Server` actually knows both `ServerN`s. You can debug that in https://github.com/yidongnan/grpc-spring-boot-starter/blob/ec610d22753dd38227c39f4d8c3ec251227e3cd7/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java#L309

If you have only one server there then there is an issue with the nacos registration. If two are there then this is a grpc-java behavioral question that is easier to directly ask there.



> result is constant.

Not sure why you added this comment.
I dont expect it to differ unless you changed the implementation of one of the servers.

Does that help you?

**Comment by Layfolk-zcy** [comment]
> Postman doesnt need load balancing. If your call is like this `Postman -RestApi-> Server -grpc-> ServerN` and you want the load balancing to happen between the servers. One important thing to check is whether `Server` actually knows both `ServerN`s. You can debug that in
> 
> https://github.com/yidongnan/grpc-spring-boot-starter/blob/ec610d22753dd38227c39f4d8c3ec251227e3cd7/grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java#L309
> 
> If you have only one server there then there is an issue with the nacos registration. If two are there then this is a grpc-java behavioral question that is easier to directly ask there/upstream. Also try to execute more requests in parallel, otherwise it might try to safe connections.
> 
> > result is constant.
> 
> Not sure why you added this comment. I dont expect it to differ unless you changed the implementation of one of the servers.
> 
> Does that help you?

I thought the @GrpcClient annotation would enable a custom implementation load on service instances in the nacos registry, so I sent a request through postman for a simple case test, but the request results were consistent so I raised the issue

**Comment by ST-DDT** [comment]
The `@GrpcClient` ist basically just a `@Autowired` annotation with some additional configuration from grpc.client properties for stubs and channels.

All grpc connection/load-balancing logic is provided by grpc-java and we just provide options to configure and inject them.
(The DiscoveryClient lookup is also provided by this library, but it is just a lookup like DNS, the actual connection is created and handled by grpc-java)
