### ISSUE TITLE
循环依赖时，无法启动成功，一直处于启动状态

### ISSUE THREAD

**Issue by HEEKDragonOne** [yidongnan/grpc-spring-boot-starter#909]
当SpringBoot出现循环依赖时，使用  spring.main.allow-circular-references: true解决后。启动项目会一直处于启动状态。
这里导致出现的循环依赖原因是自定义配置类存在循环依赖。

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/909?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

Please post the full stacktrace, otherwise I cannot help you/fix the issue.

**Comment by HEEKDragonOne** [comment]
> 

没有任何报错之类的信息，就项目启动时，项目一直处于启动状态，不能成功启动

**Comment by ST-DDT** [comment]
Spring usually reports which dependencies are circular or which beans failed to create.
Closing the issue because without that information there is nothing I can do.

**Comment by ST-DDT** [comment]
Or do you have an example project I can use for reproduction purposes?
