### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Writtscher** [yidongnan/grpc-spring-boot-starter#913]
Is this project still active? I think it is a great project but it is not up to date: Not the latest version of grpc / netty / spring.

Is anyone working on it?

**Comment by ST-DDT** [comment]
When I have time.

**Comment by panghy** [comment]
Looking to see if one can help :)

Specifically regarding: https://github.com/yidongnan/grpc-spring-boot-starter/issues/640#issuecomment-1526348497

Do you have any pointers as to how to approach the problem?

**Comment by DanielLiu1123** [comment]
I have created a project called [grpc-starter](https://github.com/DanielLiu1123/grpc-starter) to support the latest Spring Boot version and gRPC ecosystem. The project is still in its early stages, but if you are looking for an alternative, it's worth a try.

Thank you for the inspiration brought by this project.
