### ISSUE TITLE
grpc-netty-shaded 申威平台

### ISSUE THREAD

**Issue by celityowce** [yidongnan/grpc-spring-boot-starter#928]
FileNotFoundException:META-INF/native/libio_grpc_netty_shaded_netty_tcnative.so 有没有申威平台的这个so或者哪儿能弄到grpc-netty-shaded的源码在申威上自己编译

**Comment by ST-DDT** [comment]
[English](https://github-com.translate.goog/yidongnan/grpc-spring-boot-starter/issues/928?_x_tr_sl=zh-TW&_x_tr_tl=en)

---

You can find the source for grpc-netty in the  https://github.com/grpc/grpc-java repository. The shaded jar is build from it.
As for how to actually build for that plattform you have to ask over at grpc-java or maybe StackOverflow.

I hope this helps you.
