### ISSUE TITLE
Question related to gRPC retry 

### ISSUE THREAD

**Issue by banandh** [yidongnan/grpc-spring-boot-starter#932]
Hi,

Is there any support available in the grpc springboot starter to enable the retry based on gRPC status?

Ex: https://github.com/grpc/grpc-java/blob/v1.35.0/examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldClient.java#L74  

On the managedChannel builder , it registered a serviceonfig which specifies the retry config details. 

How to add these configs in the grpc-spring-boot-starter client

**Comment by ST-DDT** [comment]
Currently you have to use a GrpcChannel configurer, but we have a stale PR that tries to add support for it.

https://github.com/yidongnan/grpc-spring-boot-starter/pull/574

**Comment by banandh** [comment]
Thanks @ST-DDT . I'm using  2.14.0 version of grpc springboot starter but i dont see Method, Name Config and mentioned changes. 

Please help to provide the version details, and also if you have any reference how to configure this custom config please help to share.

**Comment by ST-DDT** [comment]
The PR is not yet added.

**Comment by banandh** [comment]
Its almost 2 years , any plan to add the changes? Tentatively when can we expect the retry support?
