### ISSUE TITLE
有人在SpringBoot 3.0以上版本JDK17 的项目里用这个start吗？需要做哪些改造

### ISSUE THREAD

**Issue by wjswk** [yidongnan/grpc-spring-boot-starter#946]
SpringBoot3.0
JDK17
需要改造什么。

**Comment by wuaoya** [comment]
版本问题很大，starter还没有支持到那一版，只能说这个组件对版本依赖挺强的

**Comment by Taogang00** [comment]
springboot3 自动注册的机制有编号，所以需要手动添加注册，新建以下类应该就能解决问题：

**Comment by yidongnan** [comment]
v2.15.0 is compatible with Spring Boot 3.0 and JAVA 17
