### ISSUE TITLE
迁移GO

### ISSUE THREAD

**Issue by s5364733** [yidongnan/grpc-spring-boot-starter#947]
请问该项目有GO的支持版本吗

**Comment by hellozdp** [comment]
你要不看看GO的gRPC Gateway项目？https://github.com/grpc-ecosystem/grpc-gateway

**Comment by hellozdp** [comment]
还有一个 gRPC middlewares项目: https://github.com/grpc-ecosystem/go-grpc-middleware

**Comment by yidongnan** [comment]
I think you are asking if there is a golang version of grpc, if that is the question, please refer directly to https://github.com/grpc/grpc-go
