### ISSUE TITLE
ETA for a new release?

### ISSUE THREAD

**Issue by ZeeD** [yidongnan/grpc-spring-boot-starter#962]
While I see some changes on the main branch, the latest release is from 2022, and - in my case - lacks some features like AutoConfiguration.imports that make impratical to use in a spring-boot 3 project
Are there plans to release a new version?

**Comment by Volodymyr-Maiboroda-Imprivata** [comment]
I second that, we are also waiting for the new release. Especially the spring boot 3.

**Comment by yidongnan** [comment]
v2.15.0 has been released

**Comment by ZeeD** [comment]
thanks!
