### ISSUE TITLE
Support for TLS usage in client

### ISSUE THREAD

**Issue by uweschaefer** [yidongnan/grpc-spring-boot-starter#97]
Referring to net.devh.springboot.autoconfigure.grpc.client.AddressChannelFactory:

Here is what i did before using your lib to connec a clientt to a TLS enabled Server:

```
ManagedChannel channel = ManagedChannelBuilder.forAddress(HOST,PORT)
                .useTransportSecurity()
                .enableFullStreamDecompression()
                .build();
```
I don't seem to find a way to achieve a similar thing using the client starter. Am i missing something?

If not:
Would it be possible to add two properties according the use of TLS and streamCompression? Would you consider a PR for that?

**Comment by yidongnan** [comment]
``plaintext`` properties set to false, the client negotiation type default is TLS.

**Comment by uweschaefer** [comment]
thanks
