### ISSUE TITLE
grpcurl调用 nginx ingress 暴露出来的服务成功，但是 starter client 调用失败了

### ISSUE THREAD

**Issue by Jamel-jun** [yidongnan/grpc-spring-boot-starter#971]
我不是很懂 grpc。
我通过 grpcurl -insecure -authority xxx.com xxx.com:443 list 是没有问题的。

这是我的 client 配置。

  server:
    max-connection-age: 60
    port: 9090
    security:
      client-auth: none
  client:
    GLOBAL:
      negotiation-type: tls
      enable-keep-alive: true
      keep-alive-without-calls: true
      security:
        client-auth-enabled: false

  xx-services:
    address: 'dns:///xxx.com:443'

**Comment by Jamel-jun** [comment]
可以了，解决了，信任服务器的证书就行

**Comment by Cedric9352** [comment]
> 可以了，解决了，信任服务器的证书就行

请教下哪里可以设置信任服务器的证书？

**Comment by ST-DDT** [comment]
For more information:

https://grpc-ecosystem.github.io/grpc-spring/en/server/security.html#configuring-the-server

You can use

- `file:<relative-path>`
- `file:</absolute-path>`
- `classpath:...`
- ...
