### ISSUE TITLE
v2.15.0 release artifact not available in maven central.

### ISSUE THREAD

**Issue by thirumurthis** [yidongnan/grpc-spring-boot-starter#972]
Noticed that the `v2.15.0` release successfully, but in Maven central didn't see the artifact for `v2.15.0` or `v2.15.0-RELEASE`. 
Is there a timeline when this will be pushed out?

**Comment by yidongnan** [comment]
https://central.sonatype.com/artifact/net.devh/grpc-server-spring-boot-starter/overview

**Comment by yidongnan** [comment]
Other repositories may take some time to sync

**Comment by thirumurthis** [comment]
I do see the artifacts in maven repo.
